project:
  type: website

website:
  title: "CEMAVE - Repositório de publicações"
  navbar:
    right:
      #- sobre.qmd
      - icon: youtube
        href: https://www.youtube.com/c/CEMAVEICMBio
      - icon: instagram
        href: https://www.instagram.com/icmbio.cemave/  
      
        
    left:
      - href: index.qmd
        text: Início
      - href: publicacoes.qmd
        text: Publicações
      # - href: apresentacoes.qmd
      #   text: Apresentações
      - href: sobre.qmd
        text: Sobre
      
format:
  html:
    theme: 
    - cosmo
    

    css: styles.css
    
editor: visual

