---
title: " "
---

<center>

## **PUBLICAÇÕES TÉCNICO-CIENTÍFICAS DO CEMAVE**

#### Digite **"CTR + F"** para fazer buscas nas referências

</center>

</br>

#### **2022-2020**

- [**FECCHIO A. ET AL. 2022. BETA DIVERSITY, PREVALENCE, AND SPECIFICITY OF AVIAN HAEMOSPORIDIAN PARASITES THROUGHOUT THE ANNUAL CYCLE OF CHILEAN ELAENIA (ELAENIA CHILENSIS), A NEOTROPICAL AUSTRAL MIGRANT. PARASITOLOGY 149:1760–1768 (10.1017/S0031182022001317)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Arquivo_13102660_Avian_malaria_in_Chilean_Elaenias_Parasitology_2022.pdf) *Artigo completo*

- [**FIALHO M.S. & GOMES FILHO A. (ORG). 2022. RELATÓRIO DE ÁREAS DE CONCENTRAÇÃO DE AVES MIGRATÓRIAS NO BRASIL. 4A EDIÇÃO. ICMBIO/MMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/RELATORIO_MIGRATORIAS_2022_opt.pdf) *Relatório*

- [**BIASOTTO L.D. ET AL. 2022. POWER LINE ELECTROCUTION AS AN OVERLOOKED THREAT TO LEAR'S MACAW (ANODORHYNCHUS LEARI). IBIS (10.1111/IBI.13139)**](https://onlinelibrary.wiley.com/doi/10.1111/ibi.13139) *Nota*

- [**ALEXANDRINHO E.R. ET AL. 2022. WHICH BIRDS ARE BRAZILIANS SEEING ON URBAN AND NON‑URBAN FEEDERS? AN ANALYSIS BASED ON A COLLECTIVE ONLINE BIRDING. ORNITHOLOGY RESEARCH 30:104–117 (10.1007/S43388-022-00094-1)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Alexandrino_et_al_2022_-_Which_birds_are_brazilians_seeing_on_urban_and_non-urban_feeders.pdf) *Artigo completo*

- [**COSTA-ARAÚJO R. ET AL. 2022. PRIMATE CONSERVATION IN THE ARC OF DEFORESTATION: A CASE STUDY OF VIEIRA'S TITI MONKEY PLECTUROCEBUS VIEIRAI. ORYX (10.1017/S003060532100171X)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/primate-conservation-in-the-arc-of-deforestation-a-case-study-of-vieiras-titi-monkey-plecturocebus-vieirai.pdf) *Artigo completo*

- [**NASCIMENTO G.D ET AL. 2022. PREVALÊNCIA E TIPOS DE PLÁSTICOS EM ALBATROZES E PETRÉIS (AVES: PROCELLARIIFORMES): RECORTE ESPACIAL DA COSTA SUDESTE E SUL DO BRASIL, DE 2015 A 2019. BIODIVERSIDADE BRASILEIRA 12(1):15-24**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1855-Texto_do_Artigo-11423-1-10-20220113.pdf) *Artigo completo*

- [**VANSTREELS R.E.T. ET AL. 2021. INGESTION OF PLASTICS AND OTHER DEBRIS BY COASTAL AND PELAGIC BIRDS ALONG THE COAST OF ESPÍRITO SANTO, EASTERN BRAZIL. MARINE POLLUTION BULLETIN 173:113046**](https://www.sciencedirect.com/science/article/abs/pii/S0025326X21010808?via%3Dihub) *Artigo completo*

- [**OLIVEIRA T.R.S. ET AL. 2021. PREDAÇÃO DE NINHOS ARTIFICIAIS NA FLORESTA NACIONAL DA RESTINGA DE CABEDELO. XII SEMINÁRIO DE PESQUISA E XIII ENCONTRO DE INICIAÇÃO DO ICMBIO. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Oliveira_etal_Resumo_SeminarioICMBio_2021.pdf) *Resumo*

- [**NASCIMENTO T.R.S. ET AL. 2021. SENTINELAS DOS OCEANOS II: DETECÇÃO DE FTALATOS ORIUNDOS DE CONTAMINAÇÃO POR PLÁSTICO EM ALBATROZES E PETRÉIS NA COSTA BRASILEIRA. XII SEMINÁRIO DE PESQUISA E XIII ENCONTRO DE INICIAÇÃO DO ICMBIO. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_Resumo_SeminarioICMBio_2021.pdf) *Resumo*

- [**GALLO L. ET AL. 2021. MÉTODOS PARA AVALIAÇÃO DA EXPOSIÇÃO A POLUENTES PLÁSTICOS EM PROCELLARIIFORMES: REVISÃO E PADRONIZAÇÃO DE PROTOCOLOS. BIODIVERSIDADE BRASILEIRA 11(3):1-16 (10.37002/BIOBRASIL.V11I3.1829)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1829-Texto_do_Artigo-11282-1-10-20211216.pdf) *Artigo completo*

- [**TOMAS W. M. ET AL. 2021. DISTANCE SAMPLING SURVEYS REVEAL 17 MILLION VERTEBRATES DIRECTLY KILLED BY THE 2020'S WILDFIRES IN THE PANTANAL, BRAZIL. SCIENTIFIC REPORTS 11(1) (10.1038/S41598-021-02844-5)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/s41598-021-02844-5.pdf) *Artigo completo*

- [**FECCHIO A. ET AL. 2021. GLOBAL DRIVERS OF AVIAN HAEMOSPORIDIAN INFECTIONS VARY ACROSS ZOOGEOGRAPHICAL REGIONS. GLOBAL ECOLOGY AND BIOGEOGRAPHY, 00, 1–14**](https://onlinelibrary.wiley.com/doi/10.1111/geb.13390) *Artigo completo*

- [**(10.1111/GEB.13390)**](https://doi.org/10.1111/geb.13390)- [ ](https://onlinelibrary.wiley.com/doi/10.1111/geb.13390) *Artigo completo*

- [**RASEIRA M.B. ET AL. 2021. O ENCONTRO DOS SABERES NA PERSPECTIVA DOS PESQUISADORES. IN: ENCONTRO DOS SABERES: UMA NOVA FORMA DE CONVERSAR A CONSERVAÇÃO. IPÊ, NAZARÉ PAULISTA, BRASIL**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cap_8_EncontroDeSaberes.pdf) *Capítulo*

- [**LUGARINI C. ET AL. 2021. FREE-LIVING BIRDS FROM CAATINGA AND ATLANTIC FOREST OF NORTHEAST BRAZIL AS HOSTS OF ENTEROBACTERALES, MYCOPLASMA SPP., AND CHLAMYDIA PSITTACI. ORNITHOLOGY RESEARCH 29:149–159 (10.1007/S43388-021-00063-0)**](https://link.springer.com/article/10.1007%2Fs43388-021-00063-0) *Artigo completo*

- [**LÖWEN L.C. ET AL. 2021. WEST NILE VIRUS IN THE STATE OF CEARÁ, NORTHEAST BRAZIL. MICROORGANISMS 9, 1699.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/microorganisms-09-01699-v4.pdf) *Artigo completo*

- [**(10.3390/MICROORGANISMS9081699)**](https://doi.org/10.3390/microorganisms908169)

- [ ](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1746_Lugarini_et_al._2021.pdf) *Artigo completo*

- [**LUGARINI C. ET AL. 2021. A CONSERVAÇÃO DA ARARINHA-AZUL, CYANOPSITTA SPIXII (WAGLER, 1832): DESAFIOS E CONQUISTAS. BIODIVERSIDADE BRASILEIRA 11(3):1-16**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1746_Lugarini_et_al._2021.pdf) *Artigo completo*

- [**FECCHIO A. ET AL. 2021. LOSS OF FOREST COVER AND HOST FUNCTIONAL DIVERSITY INCREASES PREVALENCE OF AVIAN MALARIA PARASITES IN THE ATLANTIC FOREST. INTERNATIONAL JOURNAL FOR PARASITOLOGY 51:719-728**](https://www.sciencedirect.com/science/article/abs/pii/S002075192100093X?via%3Dihub) *Artigo completo*

- [**NASCIMENTO G.D. ET AL. 2021. PREVALÊNCIA E TIPOS DE PLÁSTICOS EM ALBATROZES E PETRÉIS (AVES: PROCELLARIIFORMES) NA COSTA SUDESTE E SUL DO BRASIL. XXVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PORTO ALEGRE, BRASIL (VIRTUAL).**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_resumo_XXVIICBO_2021.pdf) *Resumo*

- [**BOVO A.A.A. ET AL. 2021. WIKIAVES COMO UMA FERRAMENTA PARA A CONSERVAÇÃO. XXVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PORTO ALEGRE, BRASIL (VIRTUAL).**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Bovo_etal_resumo_XXVIICBO_2021.pdf) *Resumo*

- [**AMARANTE R.T. ET AL. 2021. REPRESENTATIVIDADE DE AVES QUASE AMEAÇADAS E AMEAÇADAS DE EXTINÇÃO NO SISTEMA NACIONAL DE UNIDADES DE CONSERVAÇÃO DA NATUREZA. XXVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PORTO ALEGRE, BRASIL (VIRTUAL).**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Amarante_etal_resumo_XXVIICBO_2021.pdf) *Resumo*

- [**SERAFINI P.P. 2021. ESTRATÉGIAS NACIONAIS E INTERNACIONAIS PARA A CONSERVAÇÃO DE ESPÉCIES DE AVES AMEAÇADAS E MIGRATÓRIAS SENDO IMPLEMENTADAS OU PLANEJADAS PARA O BRASIL: IMPORTÂNCIA DA INTEGRAÇÃO (SIMPÓSIO). XXVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PORTO ALEGRE, BRASIL (VIRTUAL).**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_simposio_XXVIICBO_2021.pdf) *Resumo*

- [**CAMPOS I.B. ET AL. 2021. ASSESSING THE POTENTIAL OF ACOUSTIC INDICES FOR PROTECTED AREA MONITORING IN THE SERRA DO CIPÓ NATIONAL PARK, BRAZIL. ECOLOGICAL INDICATORS 120 (106953)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1-s2.0-S1470160X2030892X-main.pdf) *Artigo completo*

- [**FECCHIO A. ET AL. 2021. MIGRATION AND SEASON EXPLAIN TICK PREVALENCE IN BRAZILIAN BIRDS.**](https://onlinelibrary.wiley.com/doi/10.1111/mve.12532) *Artigo completo*

- [**MEDICAL AND VETERINARY ENTOMOLOGY 1:1-9 (10.1111/MVE.12532)**](https://onlinelibrary.wiley.com/doi/10.1111/mve.12532) *Artigo completo*

- [**SILVA B.R. ET AL. 2021. MOLECULAR DIAGNOSIS OF AVIAN VIRUSES IN GRASSLAND PASSERINES AND CAPTIVE YELLOW CARDINALS *GUBERNATRIX CRISTATA* IN BRAZIL. PESQUISA VETERINÁRIA BRASILEIRA 41:E06840**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/2021_Avian_viruses_passeriformes_cardeal_amarelo_PVB.pdf) *Artigo completo*

- [**MARTINS T.F. ET AL. 2021. TICKS (PARASITIFORMES: IXODIDA) ON NEW WORLD WILD PRIMATES IN BRAZIL. INTERNATIONAL JOURNAL OF ACAROLOGY (10.1080/01647954.2020.1870554)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ticks_Parasitiformes_Ixodida_on_new_world_wild_primates_in_Brazil.pdf) *Artigo completo*

- [**PINHEIRO L.V.S. ET AL 2021. PRIMEIRO REGISTRO DOCUMENTADO DE *LEUCOPTERNIS MELANOPS* (LATHAM, 1790) (AVES; ACCIPITRIDAE) NO ESTADO DO MARANHÃO E ATUALIZAÇÕES DA DISTRIBUIÇÃO GEOGRÁFICA DA ESPÉCIE NO BRASIL. BOLETIM DO MUSEU PARAENSE EMÍLIO GOELDI. CIÊNCIAS NATURAIS 16(1):131-143**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Leucopternis_melanops.pdf) *Nota*

- [**LUGARINI C. & VERCILLO U.E. 2021. COMO REALIZAR A GESTÃO DE UM PROJETO DE ALTO RISCO? O RELATO DA REPATRIAÇÃO DAS ARARINHAS-AZUIS AO BRASIL. BIODIVERSIDADE BRASILEIRA 11(1):1-10 (10.37002/BIOBRASIL.V11I1.1880)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1880-Texto_do_Artigo-9714-1-10-20210531.pdf) *Artigo completo*

- [**GOLDBERG D.W. ET AL. 2021. UNFORESEEN CONSEQUENCES OF THE COVID-19 PANDEMIC: INCREASED FREQUENCY OF KITE-STRING INJURIES IN MAGNIFICENT FRIGATEBIRDS (*FREGATA MAGNIFICENS*) IN RIO DE JANEIRO STATE, BRAZIL. ANIMAL WELFARE 30:109-116 (10.7120/09627286.30.2.109)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/2021_Goldberg_et_al_Frigatebirds_and_unforeseen_consequences_of_COVID19_pandemics.pdf) *Artigo completo*

- [ ](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/2021_Goldberg_et_al_Frigatebirds_and_unforeseen_consequences_of_COVID19_pandemics.pdf) *Artigo completo*

- [**BOVO A.A.A. ET AL. 2021. REMAINING SUITABLE AREAS FOR THE CRITICALLY ENDANGERED BRAZILIAN MERGANSER (*MERGUS OCTOSETACEUS*; AVES, ANSERIFORMES) ARE THREATENED BY HYDROELECTRIC POWER PLANTS. PERSPECTIVES IN ECOLOGY AND CONSERVATION (10.1016/J.PECON.2021.04.002)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1-s2.0-S253006442100047X-main.pdf) *Artigo completo*

- [**CARVALHO M.P.N. ET AL. 2021. CARDIAC DISEASE IN THE SPIX MACAW (*CYANOPSITTA SPIXII*): TWO CASES. AUSTRALIAN VETERINARY JOURNAL (10.1111/AVJ.13097)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/2021_Cardiac_disease_in_Spix_Macaw_2_cases.pdf) *Artigo completo*

- [**FECCHIO A. ET AL. 2021. LOSS OF FOREST COVER AND HOST FUNCTIONAL DIVERSITY INCREASES PREVALENCE OF AVIAN MALARIA PARASITES IN THE ATLANTIC FOREST. INTERNATIONAL JOURNAL FOR PARASITOLOGY (10.1016/J.IJPARA.2021.01.001)**](https://www.sciencedirect.com/science/article/abs/pii/S002075192100093X) *Artigo completo*

- [**PEDROBOM J.H. ET AL. 2021. INTRASPECIFIC VARIATION OF TRACE ELEMENTS IN THE KELP GULL (*LARUS DOMINICANUS*): INFLUENCE OF AGE, SEX AND LOCATIONE. HELIYON 7(1): 05994**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/1-s2.0-S2405844021000992-main.pdf) *Artigo completo*

- [**ARAÚJO V.M. ET AL. 2021. ÁREAS DE VIDA DE JUVENIS DE MARACANÃ (*PRIMOLIUS MARACANA*) NA APA E REVIS DA ARARINHA AZUL, ESTADO DA BAHIA. XI SEMINÁRIO DE PESQUISA E XII ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Araujo_etal_2021_Resumo.pdf) *Resumo*

- [**SILVA W.J. ET AL. 2021. AS CONDIÇÕES SOCIOECONÔMICAS E A EXPOSIÇÃO AO MEIO AMBIENTE INFLUENCIAM O CONHECIMENTO E USO DA AVIFAUNA POR POPULAÇÕES HUMANAS NA ÁREA DE PROTEÇÃO AMBIENTAL E REFÚGIO DE VIDA SILVESTRE DA ARARINHA AZUL. XI SEMINÁRIO DE PESQUISA E XII ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Silva_etal_2021_Resumo.pdf) *Resumo*

- [**NASCIMENTO G.D. ET AL. 2020. SENTINELAS DOS OCEANOS: INVESTIGAÇÃO DA PREVALÊNCIA E TIPO DE MACROPLÁSTICO PRESENTE EM ALBATROZES E PETRÉIS ENCONTRADOS NA COSTA BRASILEIRA. XI SEMINÁRIO DE PESQUISA E XII ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_Resumo_2020.pdf) *Resumo*

- [**PALUDO D. ET AL. 2020. MONITORAMENTO PARTICIPATIVO DE AVES LIMÍCOLAS MIGRATÓRIAS NAS RESERVAS EXTRATIVISTAS DO PARÁ E MARANHÃO. XI SEMINÁRIO DE PESQUISA E XII ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Paludo_etal_Resumo_2020.pdf) *Resumo*

- [**SALGE P.G. ET AL. 2020. MONITORAMENTO PARTICIPATIVO EM ÉPOCA DE PANDEMIA: AJUSTANDO A GESTÃO DA PESCA TRADICIONAL DO CAMARÃO-ROSA (*PENAEUS PAULENSIS*) NO PARQUE NACIONAL DA LAGOA DO PEIXE (PNLP). XI SEMINÁRIO DE PESQUISA E XII ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Salge_etal_Resumo_2020.pdf) *Resumo*

- [**SANTOS L.P.S. ET AL. 2020. FENOLOGIA REPRODUTIVA DE AVES MARINHAS RESIDENTES NO ARQUIPÉLAGO DE FERNANDO DE NORONHA. XI SEMINÁRIO DE PESQUISA E XII ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Santos_etal_Resumo_2020.pdf) *Resumo*

- [**SOUSA A.E.B.A. & SERAFINI P.P. (ORG). 2020. MANUAL DE ANILHAMENTO DE AVES SILVESTRES. 3A EDIÇÃO, ICMBIO/CEMAVE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/manual_de_anilhamento_de_aves_silvestres_3.pdf) *Manual*

- [**ROSA C.A. ET AL. 2020. NEOTROPICAL ALIEN MAMMALS: A DATA SET OF OCCURRENCE AND ABUNDANCE OF ALIEN MAMMALS IN THE NEOTROPICS. ECOLOGY 101(11): E03115**](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.3115) *Artigo completo*

- [**ROCHA D.G. ET AL. 2020. WILD DOGS AT STAKE: DEFORESTATION THREATENS THE ONLY AMAZON ENDEMIC CANID, THE SHORT-EARED DOG (*ATELOCYNUS MICROTIS*). ROYAL SOCIETY OPEN SCIENCE 7: 190717**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rocha_etal_2020_wild_dogs.pdf) *Artigo completo*

- [**PHALAN B. ET AL. 2020. AVALIAÇÃO EX SITU PARA PLANEJAMENTO INTEGRADO DE CONSERVAÇÃO PARA GALLIFORMES E TINAMIFORMES NO BRASIL. IUCN SSC GRUPO ESPECIALISTA EM PLANEJAMENTO DE CONSERVAÇÃO – BRASIL. FOZ DO IGUAÇU, BRASIL.**](https://cpsg.org/sites/cbsg.org/files/documents/RELATORIO_POR%20Galliformes%20and%20Tinamiformes%2017.12.2020%20.pdf) *Relatório*

- [**GIANUCA D. ET AL. 2020 INTENTIONAL KILLING AND EXTENSIVE AGGRESSIVE HANDLING OF ALBATROSSES AND PETRELS AT SEA IN THE SOUTHWESTERN ATLANTIC OCEAN. BIOLOGICAL CONSERVATION 252:108817**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Gianuca_etal_2020.pdf) *Artigo completo*

- [**VANSTREELS R.E.T. ET AL. 2020. PRINCIPAIS ENFERMIDADES. IN: REABILITAÇÃO DE PROCELLARIIFORMES (ALBATROZES, PETRÉIS E PARDELAS). EDITORA COMUNNICAR, SANTOS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cap_14_Enfermidades.pdf) *Capítulo*

- [**SERAFINI P.P. 2020. CONSIDERAÇÕES DE BIOSSEGURANÇA PARA ATIVIDADES DE CAMPO. IN: REABILITAÇÃO DE PROCELLARIIFORMES (ALBATROZES, PETRÉIS E PARDELAS). EDITORA COMUNNICAR, SANTOS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cap_15_Biosseguranca.pdf) *Capítulo*

- [**MICHELETTI T. ET AL. 2020. TERRESTRIAL INVASIVE SPECIES ON FERNANDO DE NORONHA ARCHIPELAGO: WHAT WE KNOW AND THE WAY FORWARD. IN: INVASIVE SPECIES: ECOLOGY, IMPACTS AND POTENTIAL USES. NOVA SCIENCE PUBLISHERS, NOVA YORK, EUA.**](https://novapublishers.com/shop/invasive-species-ecology-impacts-and-potential-uses/) *Capítulo*

- [**FERREIRA A. ET AL. 2020. CARACTERIZAÇÃO DOS PADRÕES DE MUDAS EM AVES DE SANTA CATARINA, BRASIL. XI ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ferreira_etal_2020.pdf) *Resumo*

- [**REZENDE S.T. ET AL. 2020. AVES MARINHAS ENCONTRADAS NA COSTA BRASILEIRA: QUAIS SÃO SEUS VALORES HEMATOLÓGICOS E BIOQUÍMICOS SÉRICOS DE REFERÊNCIA PARA ORIENTAR DECISÕES DE MANEJO, SOLTURA APÓS REABILITAÇÃO E AVALIAÇÃO DA SAÚDE DAS POPULAÇÕES DE ESPÉCIES AMEAÇADAS? XI ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rezende_etal_2020.pdf) *Resumo*

- [**SARAIVA M.D.M.S. ET AL. 2020. STAPHYLOCOCCUS SCIURI AS A RESERVOIR OF MEC A TO STAPHYLOCOCCUS AUREUS IN NON-MIGRATORY SEABIRDS FROM A REMOTE OCEANIC ISLAND. MICROBIAL DRUG RESISTANCE 10.1089/MDR.2020.0189.**](https://www.liebertpub.com/doi/abs/10.1089/mdr.2020.0189?journalCode=mdr) *Artigo completo*

- [**UHART M. ET AL. 2020. SAMPLING GUIDELINES TO ASSESS PLASTIC INGESTION IN ACAP SPECIES. AGREEMENT ON THE CONSERVATION OF ALBATROSSES AND PETRELS.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Uhart_etal_2020.pdf) *Nota*

- [**HTTPS://ACAP.AQ/EN/RESOURCES/ACAP-CONSERVATIONGUIDELINES/. DATE DOWNLOADED**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Uhart_etal_2020.pdf) *Nota*

**2019-2010**

- [**BARBOSA C.M. ET AL. 2019. DIVERGENT CORONAVIRUSES DETECTED IN WILD BIRDS IN BRAZIL, INCLUDING A CENTRAL PARK IN SÃO PAULO. BRAZILIAN JOURNAL OF MICROBIOLOGY 50(2):547-556**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/DivergentCoronavirus-Brazilian_Journal_of_Microbiology.pdf) *Artigo completo*

- [**BASSINI-SILVA R. ET AL. 2019. *EUTROMBICULA TINAMI* (OUDEMANS, 1910) (TROMBIDIFORMES: TROMBICULIDAE) IN BRAZIL: A NEGLECTED ECTOPARASITE OF SEVERAL ANIMALS INCLUDING HUMANS. ACAROLOGIA 59(4):412-423**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Bassini-Silva_etal_2019.pdf) *Artigo completo*

- [**RODRIGUES R.C. ET AL. 2019. ATLANTIC BIRD TRAITS: A DATA SET OF BIRD MORPHOLOGICAL TRAITS FROM THE ATLANTIC FORESTS OF SOUTH AMERICA. ECOLOGY 100(6): E02647**](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecy.2647) *Artigo completo*

- [**BARBOSA A.E.A. & TELLA J.L. 2019. HOW MUCH DOES IT COST TO SAVE A SPECIES FROM EXTINCTION? COSTS AND REWARDS OF CONSERVING THE LEAR'S MACAW. ROYAL SOCIETY OPEN SCIENCE 6:190190**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Barbosa_e_Tella_RSOS.pdf) *Artigo completo*

- [**LANCTOT R. ET AL. 2019. THE ARCTIC MIGRATORY BIRDS INITIATIVE: WORKPLAN 2019-2023. CAFF STRATEGIES SERIES NO. 30, AKUREYRI, ISLÂNDIA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AMBI_Workplan_2019-2023_May_2019.pdf) *Plano de trabalho*

- [**BARBOSA A.E.A. ET AL. 2019. RELATÓRIO ANUAL DE ROTAS E ÁREAS DE CONCENTRAÇÃO DE AVES MIGRATÓRIAS NO BRASIL. ICMBIO/MMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Aves_migratorias_compressed.pdf) *Relatório*

- [**UHART M. ET AL. 2019. SAMPLING GUIDELINES TO ASSESS PLASTIC INGESTION IN ACAP SPECIES. FIFTH MEETING OF THE POPULATION AND CONSERVATION STATUS WORKING GROUP FLORIANÓPOLIS, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Sampling_plastics_UHART_et_al.pdf) *Resumo expandido*

- [**REZENDE S.T. ET AL. 2019. HAEMATOLOGICAL AND BIOCHEMICAL VALUES FOR PROCELLARIIFORMES FOUND ON THE BRAZILIAN COAST. FIFTH MEETING OF THE POPULATION AND CONSERVATION STATUS WORKING GROUP FLORIANÓPOLIS, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Haematology_Procellariiformes_TAIXEIRA_REZENDE_et_al.pdf) *Resumo*

- [**PEREIRA A. ET AL. 2019. POTENTIAL ROLE OF THE BRAZILIAN ALBATROSS AND PETREL SAMPLE BANK TO ACAP SPECIES RESEARCH AND CONSERVATION. FIFTH MEETING OF THE POPULATION AND CONSERVATION STATUS WORKING GROUP FLORIANÓPOLIS, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Brazil_Sample_Bank_Procellariiformes_PEREIRA_et_al.pdf) *Resumo*

- [**GOULART S. ET AL. 2019. ANTHROPOGENIC SOLID RESIDUES AS STOMACH CONTENT OF STRANDED SEABIRDS IN BRAZILIAN COAST (SANTOS BASIN). FIFTH MEETING OF THE POPULATION AND CONSERVATION STATUS WORKING GROUP FLORIANÓPOLIS, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Anthropogenic_solids_stranded_seabirds_GOULART_et_al.pdf) *Resumo*

- [**SANTOS L.P.S. ET AL. 2019. DINÂMICA ESPACIAL CIRCADIANA DA GARÇA-VAQUEIRA (*BUBULCUS IBIS*) NO ARQUIPÉLAGO DE FERNANDO DE NORONHA. IX SEMINÁRIO BRASILEIRO SOBRE ÁREAS PROTEGIDAS E INCLUSÃO SOCIAL-SAPIS E IV ENCONTRO LATINO AMERICANO SOBRE ÁREAS PROTEGIDAS E INCLUSÃO SOCIAL-ELAPIS, RECIFE, BRASIL. (POSTER)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Banner_SAPIS_Bub_ibi_2019.pdf) *Resumo*

- [**FERREIRA L.C.L. ET AL. 2019. MONITORAMENTO DE AVES MARINHAS COMO FERRAMENTA PARA GESTÃO DE UNIDADES DE CONSERVAÇÃO. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ferreira_etal_2019.pdf) *Resumo*

- [**LICARIÃO C. ET AL. 2019. PREGANDO PARA NÃO CONVERTIDOS – CIÊNCIA E TURISMO EM PROL DA CONSERVAÇÃO ATRAVÉS DO PROJETO AVES DE NORONHA. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Licariao_etal_2019.pdf) *Resumo*

- [**MATINATA B. ET AL. 2019. MONITORAMENTO DA RIQUEZA DE AVES EM ÁREA DE ECÓTONO AMAZÔNIA-CERRADO E A IMPORTÂNCIA DE ESTUDOS DE LONGO PRAZO. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Matinata_etal_2019.pdf) *Resumo*

- [**RODRIGUES D.A.S. ET AL. 2019. USO DO MAR PELA GRAZINA-DE-BICO-VERMELHO (*PHAETHON AETHEREUS*) EM ABROLHOS DURANTE O PERÍODO REPRODUTIVO. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rodrigues_etal_2019.pdf) *Resumo*

- [**CAMPOLINA C. ET AL. 2019. RESILIÊNCIA POPULACIONAL DA FRAGATA (*FREGATA MAGNIFICENS*) NO PARQUE NACIONAL MARINHO DOS ABROLHOS, BAHIA. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Campolina_etal_2019.pdf) *Resumo*

- [**SILVA B.R. ET AL. 2019. PARÂMETROS LEUCOCITÁRIOS E HEMOPARASITAS DE CARDEAL-AMARELO (GUBERNATRIX CRISTATA) DE CATIVEIRO E DE VIDA LIVRE. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Silva_etal_2019.pdf) *Resumo*

- [**REZENDE S.T. ET AL. 2019. VALORES HEMATOLÓGICOS E BIOQUÍMICOS DE REFERÊNCIA PARA TESOURÃO (*FREGATA MAGNIFICENS*) EM ÁREA DE DISTRIBUIÇÃO NO SUL DO BRASIL. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rezende_etal_2019.pdf) *Resumo*

- [**FERREIRA L.C.L. ET AL. 2019. MONITORAMENTO REPRODUTIVO DA GRAZINA-DO-BICO-VERMELHO (*PHAETHON AETHEREUS*) NO PARNAMAR DOS ABROLHOS: RESULTADOS E PERSPECTIVAS . XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ferreira_etal_2019b.pdf) *Resumo*

- [**SILVA B.R. 2019. MICROBIOTA CLOACAL E DE OROFARINGE DE CARDEAIS-AMARELOS (*GUBERNATRIX CRISTATA*) DE CATIVEIRO E DE VIDA LIVRE. XXVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, VILA VELHA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Silva_etal_2018.pdf) *Resumo*

- [**FERNANDES K.C. ET AL. 2019. AVALIAÇÃO DE CONSERVAÇÃO *EX SITU* PARA A CONSERVAÇÃO INTEGRADA DO PAN PAPAGAIOS E PERIQUITO-CARA-SUJA NO BRASIL. UICN CSE GRUPO ESPECIALISTA EM PLANEJAMENTO DE CONSERVAÇÃO – BRASIL, FOZ DO IGUAÇU, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Fernandes_etal_2019_RelatorioExsituPapagaios.pdf) *Relatório*

- [**ALTEFF E.F. ET AL. 2018. THE RAREST OF THE RARE: REDISCOVERY AND STATUS OF THE CRITICALLY ENDANGERED BELEM CURASSOW, CRAX FASCIOLATA PINIMA (PELZELN, 1870). PAPÉIS AVULSOS DE ZOOLOGIA 59:1-6**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Alteff_etal_2018.pdf) *Artigo completo*

- [**SOMENZARI M. ET AL. 2018. AN OVERVIEW OF MIGRATORY BIRDS IN BRAZIL. PAPÉIS AVULSOS DE ZOOLOGIA 58:1-66**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Somenzari_etal_2018.pdf) *Artigo completo*

- [**MASELLO J.F. ET AL. 2018. CAN THE INTAKE OF ANTIPARASITIC SECONDARY METABOLITES EXPLAIN THE LOW PREVALENCE OF HEMOPARASITES AMONG WILD PSITTACIFORMES? PARASITES & VECTORS 11:357**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Masello2018_Article_CanTheIntakeOfAntiparasiticSec.pdf) *Artigo completo*

- [**LUGARINI C. ET AL. 2018. LACK OF DETECTION OF AVIAN INFLUENZA, NEWCASTLE DISEASE, AND WEST NILE VIRUSES IN WILD BIRDS OF NORTHEASTERN BRAZIL. JOURNAL OF WILDLIFE DISEASES 54(2):422-425**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lugarini_etal_LackAvianInfluenza.pdf) *Artigo completo*

- [**SILVA J.M.C. ET AL. 2018. NICHE EXPANSION OF THE COMMON WAXBILL (*ESTRILDA ASTRILD*) IN ITS NON-NATIVE RANGE IN BRAZIL. BIOLOGICAL INVASIONS 20:2635-2646**](https://link.springer.com/article/10.1007%2Fs10530-018-1723-2) *Artigo completo*

- [**PALUDO D. ET AL. 2018. REPRODUCTION OF EUDOCIMUS RUBER IN THE IGUAPE ESTUARY COMPLEX, SÃO PAULO, BRAZIL. ATUALIDADES ORNITOLÓGICAS 202:8-15**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Paludo_Eudocimus_SP.pdf) *Artigo completo*

- [**LUGARINI C. ET AL. 2018. ENDOPARASITES IN BIRDS OF GUARIBAS BIOLOGICAL RESERVA, ATLANTIC FOREST, PARAÍBA, BRASIL. CIÊNCIA ANIMAL BRASILEIRA 19:1-8**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lugarini_etal_2018.pdf) *Artigo completo*

- [**FERREIRA A. ET AL. 2018. ESTRATÉGIA E EXTENSÃO DE MUDA DE PASSERIFORMES EM UNIDADES DE CONSERVAÇÃO DA ILHA DE SANTA CATARINA E ARVOREDO, SANTA CATARINA. XXV CONGRESSO BRASILEIRO DE ORNITOLOGIA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ferreira_etal_2018.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2018. VALORES HEMATOLÓGICOS E BIOQUÍMICOS DE REFERÊNCIA PARA ATOBÁ-MARROM (*SULA LEUCOGASTER*) EM ÁREA DE DISTRIBUIÇÃO NO SUL DO BRASIL. XXV CONGRESSO BRASILEIRO DE ORNITOLOGIA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_etal_2018.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2018. VALORES HEMATOLÓGICOS E BIOQUÍMICOS DE REFERÊNCIA PARA GAIVOTÃO (*LARUS DOMINICANUS*) EM ÁREA DE DISTRIBUIÇÃO NO SUL DO BRASIL. XXV CONGRESSO BRASILEIRO DE ORNITOLOGIA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_etal_2018b.pdf) *Resumo*

- [**SOUSA N. ET AL. 2018. CAPTURA E TRÁFICO DE PSITACÍDEOS NA REGIÃO DE CURAÇÁ, BAHIA: UMA AMEAÇA À REINTRODUÇÃO DA ARARINHA-AZUL (*CYANOPSITTA SPIXII*). XXV CONGRESSO BRASILEIRO DE ORNITOLOGIA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Sousa_etal_2018.pdf) *Resumo*

- [**PRATES C.S.F. ET AL. 2018. CARACTERÍSTICAS DA CAVIDADE-NINHO E DO MICROHÁBITAT QUE INFLUENCIAM O SUCESSO REPRODUTIVO DA MARACANÃ, PRIMOLIUS MARACANA, NA REGIÃO DE CURAÇÁ, BAHIA. XXV CONGRESSO BRASILEIRO DE ORNITOLOGIA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Prates_etal_2018.pdf) *Resumo*

- [**LUGARINI C. ET AL. 2018. IMMATURE STAGES OF TICKS IN TERRRESTRIAL BIRDS OF TWO PROTECTED ÁREAS LOCALIZED IN ISLANDS OF SOUTHESTERN BRAZILIAN ATLANTIC FOREST. XXV CONGRESSO BRASILEIRO DE ORNITOLOGIA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lugarini_etal_2018b.pdf) *Resumo*

- [**SOUSA A.E.B.A. ET AL. 2018. ESTIMATIVA DE DENSIDADE POPULACIONAL DE AVES AMEAÇADAS DA RESERVA BIOLÓGICA GUARIBAS. MEMÓRIAS DA REUNIÃO DE PESQUISA E CONSERVAÇÃO DA NATUREZA NO LITORAL NORTE DA PARAÍBA, MAMANGUAPE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Emanuel_etal_resumo_2018.pdf) *Resumo*

- [**MENDES D.L. ET AL. (ORG). 2018. PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DAS AVES DA CAATINGA. INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Livro_PAN_Aves_da_Caatinga.pdf) *Livro*

- [**MACHADO B.B. & SERAFINI P.P. 2018. ALBATROZES E PETRÉIS ENCONTRADOS NA COSTA BRASILEIRA: QUAIS SÃO SEUS VALORES HEMATOLÓGICOS DE REFERÊNCIA PARA ORIENTAR A SOLTURA DE AVES OCEÂNICAS AMEAÇADAS? X SEMINÁRIO DE PESQUISA E X ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE PESQUISAS ESTRATÉGICAS PARA O DESENVOLVIMENTO SOCIOAMBIENTAL. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Machado__Serafini_2018.pdf) *Resumo*

- [**FERREIRA A. ET AL. 2018. CARACTERIZAÇÃO DOS PADRÕES DE MUDAS EM AVES DE SANTA CATARINA, BRASIL. X SEMINÁRIO DE PESQUISA E X ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE PESQUISAS ESTRATÉGICAS PARA O DESENVOLVIMENTO SOCIOAMBIENTAL. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ferreira_etal_2018b.pdf) *Resumo*

- [**LUGARINI C. ET AL. 2018. COMO POTENCIALIZAR A OBSERVAÇÃO DE AVES NAS UNIDADES DE CONSERVAÇÃO?. IX CONGRESSO BRASILEIRO DE UNIDADES DE CONSERVAÇÃO, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cOMO_POTENCIALIZAR_OBSERVA%C3%87%C3%83O_DE_AVES_EM_ucS_-_CBUC_2018.pdf) *Resumo*

- [**PALUDO D. ET AL. 2018. DISTRIBUIÇÃO E MANEJO DE AVES LIMÍCOLAS MIGRATÓRIAS NO LITORAL NORTE DO BRASIL. IX CONGRESSO BRASILEIRO DE UNIDADES DE CONSERVAÇÃO, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/trabalho_mapeamento_PA_MA_Cbuc.pdf) *Resumo expandido*

- [**ARAUJO J. ET AL. 2017. MIGRATORY BIRDS IN SOUTHERN BRAZIL ARE A SOURCE OF MULTIPLE AVIAN INFLUENZA VIRUS SUBTYPES. INFLUENZA OTHER RESPI VIRUSES 12:220–231**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/araujo_etal_2017.pdf) *Artigo completo*

- [**VAZ F.F. ET AL. 2017. SURVEY OF PATHOGENS IN THREATENED WILD RED-TAILED AMAZON PARROT (*AMAZONA BRASILIENSIS*) NESTLINGS IN RASA ISLAND, BRAZIL. BRAZILIAN JOURNAL OF MICROBIOLOGY 48(4):747-753**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Vaz_etal_2017.pdf) *Artigo completo*

- [**SCHMIDT E.M.S. ET AL. 2017. PLASMA PROTEIN CONCENTRATIONS OF THE YOUNG AND ADULT *AMAZONA BRASILIENSIS* PARROTS. VETERINARSKI GLASNIK 71(1):44-51**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Schmidt_etal_2017.pdf) *Artigo completo*

- [**LIMA D.M. ET AL. 2017. OBSERVATION OF SCAVENGING EVENTS ON SHELLS OF MEGALOBULIMUS (GASTROPODA, PULMONATA) BY LEAR'S MACAWS. THE FESTIVUS 49(4):328-331**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lima_et_al_2017_Observation_of_scavenging_events_on_shells_of_Megalobulimus_by_Lear27s_macaws.pdf) *Artigo completo*

- [**ELLIS V.A. ET AL. 2017. PREVALENCE OF AVIAN HAEMOSPORIDIAN PARASITES IS POSITIVELY RELATED TO THE ABUNDANCE OF HOST SPECIES AT MULTIPLE SITES WITHIN A REGION. PARASITOLOGY RESEARCH 116:73-80**](https://link.springer.com/article/10.1007/s00436-016-5263-3) *Artigo completo*

- [**BERKUNSKY I. ET AL. 2017. CURRENT THREATS FACED BY NEOTROPICAL PARROT POPULATIONS. BIOLOGICAL CONSERVATION 214:278-287**](https://www.sciencedirect.com/science/article/abs/pii/S0006320717306298) *Artigo completo*

- [**BERKUNSKY I. ET AL. 2017. CURRENT THREATS FACED BY NEOTROPICAL PARROT POPULATIONS. ORNITHOLOGICAL CONGRESS OF THE AMERICAS, PUERTO IGUAZU, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Berkunsky_etal_resumo_2017.pdf) *Resumo*

- [**LUGARINI C. ET AL. 2017. REPRODUCTIVE BIOLOGY OF THE BLUE-WINGED MACAW (*PRIMOLIUS MARACANA*) IN THE REGION OF CURAÇÁ, BAHIA, BRAZIL. ORNITHOLOGICAL CONGRESS OF THE AMERICAS, PUERTO IGUAZU, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lugarini_etal_2017.pdf) *Resumo*

- [**PALUDO D. 2017. THE NEED FOR AND THE IMPORTANCE OF SHOREBIRD DATA ON A BRAZILIAN PERSPECTIVE. ORNITHOLOGICAL CONGRESS OF THE AMERICAS, PUERTO IGUAZU, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Paludo_Resumo_TheNeedForAndImportanceShorebirdData.pdf) *Resumo*

- [**FERREIRA A. ET AL. 2017. SEX AND AGE DETERMINATION OF CREAMY-BELLIED THRUSH, *TURDUS AMAROCHALINUS*, AT CARIJÓS ECOLOGICAL STATION, SANTA CATARINA, BRAZIL. ORNITHOLOGICAL CONGRESS OF THE AMERICAS, PUERTO IGUAZU, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ferreira_etal_2017.pdf) *Resumo*

- [**CARDOSO D.A. ET AL. 2017. BACTERIAL RESISTANCE TO ANTIBIOTICS IN PROCELLARIIFORMES: THREATS FOR ENDANGERED OCEANIC BIRDS OR SIGNS OF COEVOLUTION? ORNITHOLOGICAL CONGRESS OF THE AMERICAS, PUERTO IGUAZU, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Alves_etal_2017.pdf) *Resumo*

- [**SOMENZARI M. ET AL. 2017. RED-BROWED PARROT PROJET (*AMAZONA RHODOCORYTHA*): CONSERVATION AT MINAS GERAIS AND RIO DE JANEIRO STATES, BRAZIL. ORNITHOLOGICAL CONGRESS OF THE AMERICAS, PUERTO IGUAZU, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Somenzari_etal_2017.pdf) *Resumo*

- [**SERAFINI P.P. 2017. NATIONAL BANDING SCHEME OF BRAZIL: LINKING BANDERS AND BIRD CONSERVATION ACROSS THE COUNTRY. ORNITHOLOGICAL CONGRESS OF THE AMERICAS, PUERTO IGUAZU, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_2017.pdf) *Resumo*

- [**PALUDO D. 2017. PLANO DE AÇÃO PARA A CONSERVAÇÃO DAS AVES LIMICOLAS MIGRATORIAS NO BRASIL: AVALIAÇÃO DOS PRIMEIRO QUATRO ANOS (2013-2017). LIBRO DE RESUMENES 7MA REUNIAO DEL GRUPO DE AVES PLAYERAS DEL HEMISFERIO OCCIDENTAL, LIMA, PERU.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Paludo_2017.pdf) *Resumo*

- [**RAMA A.C. ET AL. 2017. CARACTERIZAÇÃO DE AVES E MAMÍFEROS TERRESTRES DE MÉDIO E GRANDE PORTE NA FLORESTA NACIONAL DO JAMARI, RONDÔNIA, BRASIL. IX SEMINÁRIO DE PESQUISA E IX ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rama_etal_2017.pdf) *Resumo*

- [**FERREIRA A. ET AL. 2017. CARACTERIZAÇÃO DOS PADRÕES DE MUDAS EM AVES DA ESTAÇÃO ECOLÓGICA CARIJÓS, SANTA CATARINA, BRASIL. IX SEMINÁRIO DE PESQUISA E IX ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ferreira_etal_2017b.pdf) *Resumo*

- [**PRATES C. ET AL. 2017. DESENVOLVIMENTO DE FILHOTES DE MARACANÃ (PRIMOLIUS MARACANA) NA REGIÃO DE OCORRÊNCIA HISTÓRICA DA ARARINHA-AZUL (CYANOPSITTA SPIXII). IX SEMINÁRIO DE PESQUISA E IX ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Prates_etal_2017.pdf) *Resumo*

- [**CARDOSO D.A. & SERAFINI P.P. 2017. RESISTÊNCIA BACTERIANA EM PROCELLARIIFORMES: RISCOS PARA A CONSERVAÇÃO DE AVES OCEÂNICAS AMEAÇADAS OU COEVOLUÇÃO? IX SEMINÁRIO DE PESQUISA E IX ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cardoso__Serafini_2017.pdf) *Resumo*

- [**ANDRADE M.V. & SERAFINI P.P. 2017. PERFIL SANITÁRIO DE CARDEAIS-AMARELOS (*GUBERNATRIX CRISTATA*) EM CATIVEIRO E DE PASSERIFORMES EM ÁREA SELECIONADA PARA SOLTURA EXPERIMENTAL VISANDO A REINTRODUÇÃO DE ESPÉCIE CRITICAMENTE AMEAÇADA DE EXTINÇÃO. IX SEMINÁRIO DE PESQUISA E IX ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Andrade_etal_2017.pdf) *Resumo*

- [**SIPINSKI E.A. ET AL. 2016. PAPAGAIOS DO BRASIL. SOCIEDADE DE ZOOLÓGICOS E AQUÁRIOS DO BRASIL & ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cartilha_Papagaios_do_Brasil.pdf) *Cartilha*

- [**PALUDO D. ET AL. 2016. AVES MARINHAS. IN: VIDA MARINHA DE SANTA CATARINA. 2ED., ED. DA UFSC, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/VidaMarinha_Aves.pdf) *Capítulo*

- [**MANCINI P.L. ET AL. 2016. BREEDING SEABIRD POPULATIONS IN BRAZILIAN OCEANIC ISLANDS: HISTORICAL REVIEW, UPDATE AND A CALL FOR CENSUS STANDARDIZATION. REVISTA BRASILEIRA DE ORNITOLOGIA 24(2):94-115**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mancini_etal_2016.pdf) *Artigo completo*

- [**MESTRE L.A.M. ET AL. 2016. HABITAT ASSOCIATIONS OF LAND BIRDS IN FERNANDO DE NORONHA, BRAZIL. ORNITOLOGÍA NEOTROPICAL 27:27-34**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_etal_2016.pdf) *Artigo completo*

- [**LEAL G.R. ET AL. 2016. BREEDING OF WHITE-TAILED TROPICBIRDS (*PHAETHON LEPTURUS*) IN THE WESTERN SOUTH ATLANTIC. BRAZILIAN JOURNAL OF BIOLOGY 76(3):559-567**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Leal_etal_2016.pdf) *Artigo completo*

- [**SILVA V.R.F. ET AL. 2016. HEMATOLOGIC REFERENCE VALUES OF VINACEOUS-BREASTED AMAZON (*AMAZONA VINACEA*). CIÊNCIA RURAL 46(12):2135-2141**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Silva_etal_2016.pdf) *Artigo completo*

- [**ANDRADE L.H.M. ET AL. 2016. OCORRÊNCIA DE ANTICORPOS ANTI-TOXOPLASMA GONDII EM AVES SILVESTRES DE TRÊS UNIDADES DE CONSERVAÇÃO FEDERAIS DA PARAÍBA E DA BAHIA. PESQUISA VETERINÁRIA BRASILEIRA 36(2):103-107**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Andrade_etal_2016.pdf) *Artigo completo*

- [**VIEIRA B.P. & SERAFINI P.P. 2016. GUIDELINES FOR MANAGING AND MONITORING SEABIRDS IN THE ARVOREDO MARINE BIOLOGICAL RESERVE, SOUTHERN BRAZIL. BIODIVERSIDADE BRASILEIRA 6(1):174-189**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Vieira__Serafini_2016.pdf) *Artigo completo*

- [**OLIVEIRA A.C. ET AL. 2016. RELATÓRIO ANUAL DE ROTAS E ÁREAS DE CONCENTRAÇÃO DE AVES MIGRATÓRIAS NO BRASIL. ICMBIO/MMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rel_Migratorias_2016-MarcaDagua.pdf) *Relatório*

- [**MENDES D.L. ET AL. 2016. AVIFAUNA DE UMA ÁREA DE CAATINGA ARBÓREA E AMBIENTES ASSOCIADOS NO SERTÃO PARAIBANO, BRASIL. ORNITHOLOGIA 9(2):80-97**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mendes_etal_2016.pdf) *Artigo completo*

- [**MEDEIROS R.C.S. ET AL. 2016. INVENTÁRIO DA AVIFAUNA DA RESERVA BIOLÓGICA DA CONTAGEM, BRASÍLIA/DF. XXIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PIRENÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2016_RebioContagem.pdf) *Resumo*

- [**MEDEIROS R.C.S. 2016. O PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DE AVES AMEAÇADAS E O TRÁFICO DE ANIMAIS. XXIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PIRENÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Medeiros_Simposio_2016.pdf) *Resumo*

- [**SCHMITZ A.C. ET AL. 2016. MICROBIOTA CLOACAL E DE OROFARINGE DE CARDEAIS-AMARELOS, GUBERNATRIX CRISTATA (VIEILLOT, 1817), VINCULADOS AO PROGRAMA DE CATIVEIRO. XXIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PIRENÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2016_MicrobiotaCloacal.pdf) *Resumo*

- [**LUGARINI C. ET AL. 2016. ASSEMBLAGE OF AVIAN HAEMOSPORIDIAN IN TWO ECOSYSTEMS OF NORTHEAST BRAZIL. XXIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, PIRENÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2016_AssemblageHaemosporidian.pdf) *Resumo*

- [**PACIFICO E. ET AL. 2015. THE DISCOVERY OF TWO THREATENED BREEDING SUBPOPULATIONS OF THE ENDANGERED LEAR'S MACAW AND THE EMERGING THREATS HIDDEN IN THE UNKNOWN CAATINGA DRY-FOREST OF BRAZIL. 9TH ANNUAL PARROTS INTERNATIONAL SYMPOSIUM, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Pacifico_etal_2015.pdf) *Resumo*

- [**KANAAN V.T. ET AL. 2015. REHABILITATION OF VINACEOUS-BREASTED PARROT (AMAZONA VINACEA) FOR REINTRODUCTION AT THE ARAUCÁRIAS NATIONAL PARK, SANTA CATARINA, BRAZIL. 9TH ANNUAL PARROTS INTERNATIONAL SYMPOSIUM, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/KANAAN_2015._REHABILITATION.pdf) *Resumo*

-LUGARINI C. ET AL. 2015. **ACTION PLAN FOR THE CONSERVATION OF SPIX'S MACAW (*CYANOPSITTA SPIXII*): 2012 TO 2015**. 9TH ANNUAL PARROTS INTERNATIONAL SYMPOSIUM, CAMPO GRANDE, BRASIL.

- LUGARINI C. ET AL. 2015. **SUCCESS OF CYANOPSITTA SPIXII CAPTIVE PROGRAM**. SYMPOSIUM: RESTORING BIRD POPULATIONS: MANAGEMENT STRATEGIES FOR THE CONSERVATION THREATENED SPECIES. X NEOTROPICAL ORNITHOLOGICAL CONGRESS & XXII CONGRESSO BRASILEIRO DE ORNITOLOGIA, MANAUS, BRASIL.

- LUGARINI C. ET AL. 2015. **EVALUATION OF PATHOGENS ASSOCIATED WITH BIRDS IN PROTECTED AREAS IN CAATINGA AND ATLANTIC FOREST OF NORTHEAST BRAZIL**. SYMPOSIUM: PATHOGENS OF THE WILD BIRD POPULATIONS: THE VALUE OF SURVEYS TO UNDERSTANDING BASIC SCIENCE, IMPROVING PUBLIC AND ENVIRONMENTAL HEALTH, AND INFORMING MANAGEMENT DECISIONS. X NEOTROPICAL ORNITHOLOGICAL CONGRESS & XXII CONGRESSO BRASILEIRO DE ORNITOLOGIA, MANAUS, BRASIL.

- [**LUGARINI C. ET AL. 2015. RICKETTSIAL AGENTS IN AVIAN IXODID TICKS IN NORTHEAST BRAZIL. TICKS AND TICK-BORNE DISEASES 6(3):364-375**](https://pubmed.ncbi.nlm.nih.gov/25800099/) *Artigo completo*

- [**ELLIS V.A. ET AL. 2015. LOCAL HOST SPECIALIZATION, HOST-SWITCHING, AND DISPERSAL SHAPE THE REGIONAL DISTRIBUTIONS OF AVIAN HAEMOSPORIDIAN PARASITES. PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES OF AMERICA 112:11294-11299**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ellis_etal_2015.pdf) *Artigo completo*

- [**DEL LAMA S.N. ET AL. 2015. POST-BREEDING MOVEMENTS OF WOOD STORKS IN BRAZIL AND ARGENTINA. JOURNAL OF FIELD ORNITHOLOGY 86(4):283-287**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/10.1111jofo.12122.pdf) *Artigo completo*

- [**VIEIRA B.P. ET AL. 2015. BIRDS OF THE ARVOREDO MARINE BIOLOGICAL RESERVE, SOUTHERN BRAZIL. CHECK LIST 11(1):1532**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Vieira_etal_2015.pdf) *Artigo completo*

- [**SERAFINI P.P. ET AL. 2015. O USO DA MICROBIOLOGIA COMO FERRAMENTA PARA A CONSERVAÇÃO DE AVES AMEAÇADAS: DADOS PRELIMINARES PARA O PAPAGAIO-DE-CARA-ROXA, AMAZONA BRASILIENSIS (AVES: PSITTACIDAE) NO PARANÁ. ARQUIVOS DE CIÊNCIAS VETERINÁRIAS E ZOOLOGIA DA UNIPAR 18(1):65-69**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_etal_2015.pdf) *Artigo completo*

- [**FARIAS F.B. ET AL. 2015. AVES DA ESTAÇÃO ECOLÓGICA DE CARIJÓS. ICMBIO/ESTAÇÃO ECOLÓGICA DE CARIJÓS, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Aves_EECarijos.pdf) *Guia*

- [**FOLETTO V. ET AL. 2015. AVALIAÇÃO SANITÁRIA DE UM FILHOTE DE PAPAGAIO-DE-PEITO-ROXO (*AMAZONA VINACEA*) RESGATADO EM ÁREA DE REINTRODUÇÃO DA ESPÉCIE. XVII CONGRESSO XXIV ENCONTRO ABRAVAS, CANELA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ResumoCongressoABRAVAS2015.jpg) *Resumo*

- [**ROSSATO R.M. ET AL. 2015. AVIAN INVENTORY OF THE RECANTO DAS ARARAS DE TERRA RONCA EXTRACTIVE RESERVE (GOIÁS, BRAZIL). X NEOTROPICAL ORNITHOLOGICAL CONGRESS & XXII CONGRESSO BRASILEIRO DE ORNITOLOGIA, MANAUS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rossato_resumo_2015.pdf) *Resumo*

- [**MEURER R. ET AL. 2015. FUNGAL CHARACTERIZATION IN OCCUPIED NESTS BY FREE-LIVING AMAZONA BRASILIENSIS. X NEOTROPICAL ORNITHOLOGICAL CONGRESS & XXII CONGRESSO BRASILEIRO DE ORNITOLOGIA, MANAUS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Meurer_etal_resumo_2015.pdf) *Resumo*

- [**MARIZ D. ET AL. 2015. ESPÉCIES ENDÊMICAS E ÁREAS PRIORITÁRIAS PARA A CONSERVAÇÃO DA CAATINGA. X NEOTROPICAL ORNITHOLOGICAL CONGRESS & XXII CONGRESSO BRASILEIRO DE ORNITOLOGIA, MANAUS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mariz_etal_resumo_2015.pdf) *Resumo*

- [**KANAAN V. ET AL. 2015. ANALYSIS OF BIOMETRIC DATA AND CHEST CIRCUMFERENCE OF AMAZONA VINACEA. X NEOTROPICAL ORNITHOLOGICAL CONGRESS & XXII CONGRESSO BRASILEIRO DE ORNITOLOGIA, MANAUS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Kanaan_etal_resumo_2015.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2015. CURRENT HEALTH AND REPRODUCTIVE STATUS OF CAPTIVE *CYANOPSITTA SPIXII* IN BRAZIL. X NEOTROPICAL ORNITHOLOGICAL CONGRESS & XXII CONGRESSO BRASILEIRO DE ORNITOLOGIA, MANAUS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2015_CurrentHealth.pdf) *Resumo*

- [**OLIVEIRA R.C.R. ET AL. 2014. A CRIAÇÃO DE ÁREAS DE PROTEÇÃO AMBIENTAL MARINHAS: A PROTEÇÃO DO MAR QUE NOS ENVOLVE E DO LITORAL. IN: CONSERVAÇÃO DE ÁREAS COSTEIRAS MARINHAS, IOESP, SÃO PAULO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cap_14_Oliveira_etal_2014.pdf) *Capítulo*

- [**VASCONCELOS N.C.T. ET AL. 2014. IDENTIFICAÇÃO DE CARRAPATOS EM AVES DE UNIDADES DE CONSERVAÇÃO FEDERAIS DO NORDESTE DO BRASIL E SUA IMPLICAÇÃO COMO VETORES DE RICKETTSIA SPP.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Vasconcelos_VI_S_ICMBio_2014.pdf) *Resumo* - [**VI SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Vasconcelos_VI_S_ICMBio_2014.pdf) *Resumo*

- [**PAZ A.V. & SERAFINI P.P. 2014. MONITORAMENTO DE AVES MARINHAS OCEÂNICAS: AVALIAÇÃO DA MICROBIOTA CLOACAL E DE OROFARINGE DE AVES SILVESTRES NAS UNIDADES DE CONSERVAÇÃO MARINHO-COSTEIRAS DE SANTA CATARINA E NAS ZONAS DE AMORTECIMENTO ESTABELECIDAS. VI SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Paz_VI_S_ICMBio_2014.pdf) *Resumo*

- [**MEURER R. & SERAFINI P.P. 2014. AVALIAÇÃO DA MICROBIOTA CLOACAL E DE OROFARINGE DE PAPAGAIOS-DE-CARA-ROXA (*AMAZONA BRASILIENSIS*) EM VIDA LIVRE. VI SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Meurer_VI_S_ICMBio_2014.pdf) *Resumo*

- [**MEURER R. ET AL. 2014. CARACTERIZAÇÃO FÚNGICA EM NINHEGOS DE *AMAZONA BRASILIENSIS*: DADOS PRELIMINARES. XXI CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Meurer_etal_XXICBO.pdf) *Resumo*

- [**MARINHO M.F.A. ET AL. 2014. DISTRIBUIÇÃO E CONSERVAÇÃO DE *TANGARA FASTUOSA* (LESSON, 1831) (AVES, THRAUPIDAE) PARAÍBA. VI SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASÍLIA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Marinho_VI_S_ICMBio_2014.pdf) *Resumo*

- [**LUCENA W.G. ET AL. 2014. CARACTERIZAÇÃO DA AVIFAUNA DA MATA DO BURAQUINHO, JOÃO PESSOA, PARAÍBA. VI SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Lucena_VI_S_ICMBio_2014.pdf) *Resumo*

- [**SERAFINI P.P. & LUGARINI C. 2014. PROCELLARIIFORMES E OUTRAS AVES DE AMBIENTES MARINHOS (ALBATROZ, PETREL, FRAGATA, ATOBA, BIGUA E GAIVOTA). IN: TRATADO DE ANIMAIS SELVAGENS: MEDICINA VETERINÁRIA. 2ED. ROCA, SÃO PAULO, BRASIL.**](https://www.amazon.com/Tratado-Animais-Selvagens-Medicina-Veterinaria/dp/8527726181) *Capítulo*

- [**LUGARINI C. ET AL. 2014. PROTOCOLO CEMAVE: PROJETO DE MONITORAMENTO DA AVIFAUNA EM UNIDADES DE CONSERVAÇÃO FEDERAIS DO BIOMA CAATINGA. MMA/ICMBIO/CEMAVE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/protocolo_cemave_2014.pdf) *Relatório técnico*

- [**ARAUJO J. ET AL. 2014. AVIAN INFLUENZA VIRUS (H11N9) IN MIGRATORY SHOREBIRDS WINTERING IN THE AMAZON REGION, BRAZIL. PLOS ONE 9(10):E110141**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Araujo_etal_2014.pdf) *Artigo completo*

- [**HURTADO R.F. ET AL. 2014. AQUATIC WILD BIRDS KEPT CAPTIVE AT REMOTE COASTAL COMMUNITIES IN NORTHERN BRAZIL. BOLETÍN CHILENO DE ORNITOLOGÍA 20(1-2):17-22**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Hurtado_etal_2014.pdf) *Artigo completo*

- [**OLIVEIRA A. ET AL. 2014. OCCURRENCE OF PINNIPEDS IN SANTA CATARINA BETWEEN 2000 AND 2010. LATIN AMERICAN JOURNAL OF AQUATIC MAMMALS 9:145-149**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Oliveira_etal_2014.pdf) *Artigo completo*

- [**OLIVEIRA K.G. ET AL. 2014. MONITORING REINTRODUCED LEAR'S MACAWS (*ANODORHYNCHUS LEARI*) IN THE RASO DA CATARINA, BAHIA (BRAZIL). ORNITHOLOGIA 7(1):12-20**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Oliveira_etal_2014b.pdf) *Artigo completo*

- [**ARAUJO D.S. ET AL. 2014. REGISTRO DE NOVOS SÍTIOS REPRODUTIVO, DORMITÓRIO E ALIMENTAÇÃO DA ARARA-AZUL-DE-LEAR (*ANODORHYNCHUS LEARI*) NOS MUNICÍPIOS DE CANUDOS E NOVO TRIUNFO, BAHIA. ORNITHOLOGIA 7(1):21-22**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Araujo_etal_2014b.pdf) *Artigo completo*

- [**SIPINSKI E.A. ET AL. 2014. TENDÊNCIA POPULACIONAL DO PAPAGAIO-DE-CARA-ROXA (*AMAZONA BRASILIENSIS*) NO LITORAL DO ESTADO DO PARANÁ. ORNITHOLOGIA 6(2):136-143**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Sipinski_etal_2014.pdf) *Artigo completo*

- [**RIBAS J.M. ET AL. 2014. CHLAMYDOPHILA PSITTACI ASSESSMENT IN THREATENED RED-TAILED AMAZON (AMAZONA BRASILIENSIS) PARROTS IN PARANÁ, BRAZIL. ORNITHOLOGIA 6(2):144-147**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ribas_etal_2014.pdf) *Artigo completo*

- [**MENDES D.L. ET AL. 2014. DIETA POR ANODORHYNCHUS LEARI BONAPARTE, 1856 (AVES: PSITTACIDAE) EM PALMEIRA DE LICURI NA CAATINGA BAIANA. ATUALIDADES ORNITOLÓGICAS 178:50-54**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lima_etal_2014.pdf) *Artigo completo*

- [**FILETO-DIAS F. ET AL. 2014. AVALIAÇÃO DO PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DOS PAPAGAIOS DA MATA ATLÂNTICA NA CONSERVAÇÃO DESSAS ESPÉCIES. ATUALIDADES ORNITOLÓGICAS 181:33-45**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Fileto-Dias_etal_2014.pdf) *Artigo completo*

- [**OLIVEIRA A.C. ET AL. 2014. RELATÓRIO ANUAL DE ROTAS E ÁREAS DE CONCENTRAÇÃO DE AVES MIGRATÓRIAS NO BRASIL. ICMBIO/MMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rel_Migratorias_2014-MarcaDAgua.pdf) *Relatório*

- [**MELO D.C. ET AL. 2014. DISTRIBUTION OF THE ORANGE-WINGED PARROT *AMAZONA AMAZONICA* (LINNAEUS, 1766) (AVES, PSITTACIDAE) IN THE COASTAL REGION OF THE STATE OF PARAÍBA, BRAZIL. ACTA SCIENTIARUM. BIOLOGICAL SCIENCES 36(3):307-312**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Melo_etal_2014.pdf) *Artigo completo*

- [**MENDES D.L. ET AL. 2014. AN AVIFAUNAL INVENTORY AND CONSERVATION PROSPECTS FOR THE GURUPI BIOLOGICAL RESERVE, MARANHÃO, BRAZIL. REVISTA BRASILEIRA DE ORNITOLOGIA 22(4):317-338**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lima_etal_2014b.pdf) *Artigo completo*

- [**VIEIRA B.P. ET AL. 2014. BIRDS OF ESTAÇÃO ECOLÓGICA DE CARIJÓS, SOUTHERN BRAZIL. CHECK LIST 10(5):1110-1122**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Vieira_etal_2014.pdf) *Artigo completo*

- [**FREITAS M.A. ET AL. 2014. REGISTRO DE ABATE DE GAVIÕES-REAIS *HARPIA HARPYJA* (ACCIPITRIDAE) PARA CONSUMO HUMANO NO MARANHÃO, BRASIL. ATUALIDADES ORNITOLÓGICAS 178:12-15**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Abate_harpyja.pdf) *Artigo completo*

- [**PACÍFICO E.C. ET AL. 2014. BREEDING TO NON-BREEDING POPULATION RATIO AND BREEDING PERFORMANCE OF THE GLOBALLY ENDANGERED LEAR'S MACAW *ANODORHYNCHUS LEARI*: CONSERVATION AND MONITORING IMPLICATIONS. BIRD CONSERVATION INTERNATIONAL 24(4):466-476**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Pacifico_etal_2014.pdf) *Artigo completo*

- [**SANTANA R. ET AL. 2014. CONTRIBUTIONS FOR ACAP SPECIES CONSERVATION IN BRAZIL. INFO PAPER PUBLISHED ONLINE ANNALS EIGHTH MEETING OF THE ADVISORY COMMITTEE (AC8) - AGREEMENT ON THE CONSERVATION OF ALBATROSSES AND PETRELS, PUNTA DEL ESTE, URUGUAI.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AC8_2014_Serafini.pdf) *Resumo expandido*

- [**NASCIMENTO N.F.F. ET AL. 2014. CARACTERIZAÇÃO DA AVIFAUNA DA SERRA DE SANTA CATARINA, PARAÍBA, BRASIL. XXI CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/CBO_2014_Nascimento.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2014. PINGUINS-DE-MAGALHÃES (*SPHENISCUS MAGELLANICUS*) NO SUL DO ESTADO DE SANTA CATARINA NO INVERNO DE 2013 - CAUSAS E CONSEQUÊNCIAS DOS NÚMEROS OBSERVADOS. XXI CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2014_Serafini.pdf) *Resumo*

- [**VIEIRA-FILHO A.H. ET AL. 2014. MONITORAMENTO DE AVES EM PARQUES EÓLICOS NO LITORAL DO RIO GRANDE DO NORTE. XXI CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_XXI_Vieira-Filho.pdf) *Resumo*

- [**GHIZONI-JR I.R. ET AL. 2013. CHECKLIST DA AVIFAUNA DA ILHA DE SANTA CATARINA, SUL DO BRASIL. ATUALIDADES ORNITOLÓGICAS 171:50-75**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AO171_50.pdf) *Artigo completo*

- [**PAIXAO R.M.C. ET AL. 2013. ENTRE SABERES E OBSERVAÇÕES: A MANUTENÇÃO EM CATIVEIRO DE PASSERIFORMES SILVESTRES EM UMA COMUNIDADE DA ZONA DA MATA PARAIBANA. ATUALIDADES ORNITOLÓGICAS 174:54-59**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AO174_54.pdf) *Artigo completo*

- [**OMETTO T. ET AL. 2013. WEST NILE VIRUS SURVEILLANCE, BRAZIL, 2008-2010. TRANSACTIONS OF THE ROYAL SOCIETY OF TROPICAL MEDICINE AND HYGIENE 107(11):723-730**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ometto2013.pdf) *Artigo completo*

- [**DANTAS G.P.M. ET AL. 2013. EVIDENCE FOR NORTHWARD EXTENSION OF THE WINTER RANGE OF MAGELLANIC PENGUINS ALONG THE BRAZILIAN COAST. MARINE ORNITHOLOGY 41:195-197**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Dantas_etal_MarineOrnithology_2013.pdf) *Artigo completo*

- [**SERAFINI P.P. 2013. PROJETO NACIONAL DE MONITORAMENTO DO PINGUIM-DE-MAGALHÃES (*SPHENISCUS MAGELLANICUS*): 3 ANOS DE TRABALHO. BOLETIM PINGUINS NO BRASIL 3:1-2**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_PinguinsNoBrasil_2013.pdf) *Nota*

- [**NIEMEYER C. ET AL. 2013. PRESENÇA DE POX VÍRUS AVIÁRIO EM PINGUINS DE MAGALHÃES EM CENTROS DE REABILITAÇÃO NO BRASIL. BOLETIM PINGUINS NO BRASIL 3:3**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Niemeyer_etal_PinguinsNoBrasil_2013.pdf) *Nota*

- [**PRATES C.S.F. & TORRES I.M.D. 2013. AVES RECEBIDAS NO CENTRO DE TRIAGEM DE ANIMAIS SILVESTRES DA PARAÍBA. XX CONGRESSO BRASILEIRO DE ORNITOLOGIA, PASSO FUNDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2013_Prates.pdf) *Resumo*

- [**ROOS A.L. & SOUZA M.A. 2013. BANCO DE DADOS GEOGRÁFICO DAS AVES BRASILEIRAS. XX CONGRESSO BRASILEIRO DE ORNITOLOGIA, PASSO FUNDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2013_Roos.pdf) *Resumo*

- [**SERAFINI P.P. 2013. PLANOS DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DAS AVES BRASILEIRAS. XX CONGRESSO BRASILEIRO DE ORNITOLOGIA, PASSO FUNDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2013_Serafini.pdf) *Resumo*

- [**SERAFINI P.P. (ORG.). 2013. PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DOS PASSERIFORMES AMEAÇADOS DOS CAMPOS SULINOS E ESPINILHO. ICMBIO/MMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/livro-campos-sulinos-2013.pdf) *Plano de Ação Nacional*

- [**SIPINSKI E.A. ET AL. 2013. O PAPAGAIO -DE-CARA-ROXA (*AMAZONA BRASILIENSIS*) NO LITORAL DO ESTADO DO PARANÁ: ONZE ANOS DE CENSO POPULACIONAL. XX CONGRESSO BRASILEIRO DE ORNITOLOGIA, PASSO FUNDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2013_Sipinski.pdf) *Resumo*

- [**SOUZA M.A. ET AL. 2013. COMO ESTÃO REPRESENTADAS AS AVES NAS UNIDADES DE CONSERVAÇÃO FEDERAIS? UMA ANÁLISE A PARTIR DO BANCO DE DADOS DE AVES BRASILEIRAS. XX CONGRESSO BRASILEIRO DE ORNITOLOGIA, PASSO FUNDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2013_Souza.pdf) *Resumo*

- [**PRATES C.S.F. ET AL. 2013. AVIFAUNA DA FLORESTA NACIONAL CONTENDAS DO SINCORÁ - BAHIA - DADOS PRELIMINARES. XX CONGRESSO BRASILEIRO DE ORNITOLOGIA, PASSO FUNDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2014_Prates_etal.pdf) *Resumo*

- [**NIEMEYER C. ET AL. 2013. A NOVEL AVIPOXVIRUS ASSOCIATED TO CUTANEOUS AND DIFTERIC DISEASE IN MAGELLANIC PENGUINS (*SPHENISCUS MAGELLANICUS*) IN BRAZIL. WILDLIFE DISEASES ASSOCIATION (WDA) LATIN AMERICA MEETING 2013, SÃO PAULO, BRASIL**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/WDA_2013_Avipoxvirus.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2013. SEABIRDS POPULATION MONITORING: CAUSES OF DEATH AND HEALTH ASSESSMENT IN MARINE BIRDS IN SANTA CATARINA, BRAZIL. WILDLIFE DISEASES ASSOCIATION (WDA) LATIN AMERICA MEETING 2013, SÃO PAULO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/WDA_2013_Seabirds.pdf) *Resumo*

- [**PRATES C.S.F. ET AL. 2013. CARACTERIZAÇÃO DA AVIFAUNA DA ESTAÇÃO ECOLÓGICA RASO DA CATARINA, BAHIA. V SEMINÁRIO DE PESQUISA E V ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Prates_etal_2013.pdf) *Resumo*

- [**VASCONCELOS N.C.T. ET AL. 2013. OCORRÊNCIA DE ENDO E ECTOPARASITOS NAS AVES SILVESTRES DA ESTAÇÃO ECOLÓGICA RASO DA CATARINA, BAHIA. V SEMINÁRIO DE PESQUISA E V ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Vasconcelos_etal_2013.pdf) *Resumo*

- [**AMORIM M.M.R. ET AL. 2013. PESQUISA DE SALMONELLA SPP. NAS AVES DA RESERVA BIOLÓGICA GUARIBAS, PARAÍBA E ESTAÇÃO ECOLÓGICA RASO DA CATARINA, BAHIA. V SEMINÁRIO DE PESQUISA E V ENCONTRO DE INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Amorim_etal_2013.pdf) *Resumo*

- OLIVEIRA R.A.S. ET AL. 2013. **OCORRENCIA DE ANTICORPOS ANTI-TOXOPLASMA GONDII EM GALINHAS DE SUBSISTENCIA DO ENTORNO DA RESERVA BIOLOGICA GUARIBAS, ESTADO DA PARAÍBA**. II SIMPOSIO BRASILEIRO DE TOXOPLASMOSE, SAO PAULO, BRASIL.

- [**SILVA-NETO G.F. ET AL. 2012. NOVAS INFORMAÇÕES SOBRE A DIETA DA ARARA-AZUL-DE-LEAR, *ANODORHYNCHUS LEARI* BONAPARTE, 1856 (AVES, PSITTACIDAE). ORNITHOLOGIA 5(1):1-5**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SilvaNeto_etal_2012.pdf) *Artigo completo*

- [**ROOS A.L. ET AL. 2012. PRIMEIRO REGISTRO DOCUMENTADO DO JACU-ESTALO *NEOMORPHUS GEOFFROYI* TEMMINCK, 1820 PARA O BIOMA CAATINGA. REVISTA BRASILEIRA DE ORNITOLOGIA 20(1):81-85**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Roos_etal_2012.pdf) *Nota*

- [**SOUSA A.E.B.A. ET AL. 2012. AVIFAUNA OF THE CATIMBAU NATIONAL PARK IN THE BRAZILIAN STATE OF PERNAMBUCO, BRAZIL: SPECIES RICHNESS AND SPATIO-TEMPORAL VARIATION. REVISTA BRASILEIRA DE ORNITOLOGIA 20(3):230-245**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Sousa_etal_2012.pdf) *Artigo completo*

- [**SCHUNCK F. ET AL. 2012. BIRDS OF THE LOWER MIDDLE SÃO FRANCISCO RIVER. REVISTA BRASILEIRA DE ORNITOLOGIA 20(3):350-364**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Schunck_etal_2012.pdf) *Artigo completo*

- [**HURTADO R. ET AL. 2012. NORTHERNMOST RECORD OF BROWN SKUAS STERCORARIUS ANTARCTICUS (LESSON 1831) AT MARANHÃO STATE, NORTHERN BRAZIL. BOLETÍN CHILENO DE ORNITOLOGÍA 18(1-2):52-56**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Hurtado_etal_2012.pdf) *Artigo completo*

- [**RUOPPOLO V. ET AL. 2012. SURVIVAL AND MOVEMENTS OF MAGELLANIC PENGUINS REHABILITATED FROM OIL FOULING ALONG THE COAST OF SOUTH AMERICA, 2000-2010. MARINE POLLUTION BULLETIN 64:1309-1317**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ruoppolo2012.pdf) *Artigo completo* (- [**ERRATA**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Corrigendum_Ruoppolo2013.pdf) *Errata*

- [**HURTADO R. ET AL. 2012. AVIAN INFLUENZA VIRUS SURVEILLANCE IN WILD BIRDS IN BRAZIL. 61ST ANNUAL INTERNATIONAL CONFERENCE OF THE WILDLIFE DISEASE ASSOCIATION AND 10TH BIENNIAL EUROPEAN WILDLIFE DISEASE ASSOCIATION, LYON, FRANÇA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/WDA_2012_AvianInfluenza.pdf) *Resumo*

- [**OMETTO T. ET AL. 2012. O DESAFIO DA DETECÇÃO MOLECULAR DO VÍRUS DO OESTE DO NILO EM CAMPO. 1O CONFERÊNCIA BRASILEIRA EM SAÚDE SILVESTRE E HUMANA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBSSH2012_Resumo_Serafini_Isaac.pdf) *Resumo*

- [**OLIVEIRA C.J.B. ET AL. 2012. RESISTANT PATTERNS OF ENTEROBACTER CLOACAE AND ESCHERICHIA COLI FROM WILDLIFE SEABIRD POPULATIONS IN A BRAZILIAN ARQUIPELAGO. XXI CONGRESSO LATINO AMERICANO DE MICROBIOLOGIA, SANTOS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CLM2012_Resumo_Serafini.pdf) *Resumo*

- [**OLIVEIRA C.J. ET AL. 2012. METHICILLIN RESISTANCE OF STAPHYLOCOCCI FROM ENDANGERED SEABIRD POPULATIONS IN THE FERNANDO DE NORONHA ARCHIPELAGO. XXI CONGRESSO LATINO AMERICANO DE MICROBIOLOGIA, SANTOS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Oliveira_etal_resumo_2012.pdf) *Resumo*

- [**CHAVES R.A.H. ET AL. 2012. PESQUISA DE ECTO E ENDOPARASITOS EM AVES SILVESTRES E DOMÉSTICAS NA RESERVA BIOLÓGICA DE GUARIBAS E ENTORNO, PARAÍBA. IV SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE-IPERÓ/SP, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Chaves_etal_IV_S_ICMBIO.pdf) *Resumo*

- [**ENEDINO T.R. & ROOS A.L. 2012. COMUNIDADE DE AVES DA RESERVA BIOLÓGICA GUARIBAS, PARAÍBA, BRASIL. IV SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE-IPERÓ/SP, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Enedino_IV_S_ICMBIO.pdf) *Resumo*

- [**OLIVEIRA R.A.S. ET AL. 2012. OCORRÊNCIA DE ANTICORPOS ANTI-TOXOPLASMA GONDII EM AVES SILVESTRES E DOMÉSTICAS DA RESERVA BIOLÓGICA DE GUARIBAS E DO ENTORNO, ESTADO DA PARAÍBA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Oliveira_etal_IV_S_ICMBIO.pdf) *Resumo*

- [**IV SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE-IPERÓ/SP, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Oliveira_etal_IV_S_ICMBIO.pdf) *Resumo*

- [**PAIXAO R.M.C. ET AL. 2012. AVIFAUNA DA ESTAÇÃO ECOLÓGICA DO RASO DA CATARINA, BAHIA, BRASIL: COMPOSIÇÃO E BIOLOGIA. IV SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE-IPERÓ/SP, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Paixao_IV_S_ICMBIO.pdf) *Resumo*

- [**MACHADO P.O. & SERAFINI P.P. 2012. SAÚDE DAS AVES SILVESTRES DA REBIOMAR ARVOREDO E SUA ZONA DE AMORTECIMENTO PARA ANALISE DA EFETIVIDADE DA UNIDADE DE CONSERVAÇÃO. IV SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE-IPERÓ/SP, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Serafini_IV_S_ICMBIO.pdf) *Resumo*

- [**VIEIRA B.P. & SERAFINI P.P. 2012. AVES INDICADORAS DE CONSERVAÇÃO DA RESERVA BIOLÓGICA MARINHA DO ARVOREDO, SANTA CATARINA, BRASIL. IV SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE-IPERÓ/SP, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Serafini2_IV_S_ICMBIO.pdf) *Resumo*

- [**LUGARINI C. ET AL. (ORGS). 2012. PLANO DE AÇÃO NACIONAL PARA CONSERVAÇÃO DA ARARA-AZUL-DE-LEAR. 2ED. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/pan-arara-azul-de-lear-2012_livro.pdf) *Livro*

- [**BARBOSA A.E.A. ET AL. 2012, ARARA-AZUL-DE-LEAR. IN: PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DA ARARA-AZUL-DE-LEAR. 2ED. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Barbosa_etal_2012.pdf) *Capítulo*

- [**CAMPOS I.B. ET AL. 2012. ANÁLISE DE VIABILIDADE POPULACIONAL. IN: PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DA ARARA-AZUL-DE-LEAR. 2ED. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Campos_etal_2012.pdf) *Capítulo*

- [**SOUSA A.E.B.A. ET AL. 2012. LICURI NA ÁREA DE OCORRÊNCIA DA ARARA-AZUL-DE-LEAR. IN: PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DA ARARA-AZUL-DE-LEAR. 2ED. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Sousa_etal_2012b.pdf) *Capítulo*

- [**BARROS Y.M. ET AL (ORGS). 2012. PLANO DE AÇÃO NACIONAL PARA A CONSERVAÇÃO DA ARARINHA-AZUL CYANOPSITTA SPIXII. ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/pan-ararinha-azul-2012_livro.pdf) *Livro*

- [**DIAS D. ET AL. 2012. LEVANTAMENTO DE AVES NA ESTAÇÃO ECOLÓGICA DE CARIJÓS, ILHA DE SANTA CATARINA, BRASIL. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA. MACEIÓ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Dias_etal_2012b.pdf) *Resumo*

- [**DIAS D. ET AL. 2012. PARÂMETROS POPULACIONAIS DE PIA-COBRA (GEOTHLYPIS AEQUINOCTIALIS) NA ESTAÇÃO ECOLÓGICA DE CARIJÓS, ILHA DE SANTA CATARINA, BRASIL. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA. MACEIÓ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Dias_etal_2012.pdf) *Resumo*

- [**ENEDINO T.R. & ROOS A.L. 2012. AVES DA RESERVA BIOLÓGICA GUARIBAS, PARAÍBA, BRASIL: RESULTADOS 2011-2012. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA, MACEIÓ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Enedino__Roos_2012.pdf) *Resumo* (- [**POSTER**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CBO_2012_Thayz.PDF) *Poster*

- [**HOLDERBAUM J.M. ET AL. 2012. NOVOS REGISTROS DE AVES NA ESTAÇÃO ECOLÓGICA DO RASO DA CATARINA, BAHIA, BRASIL. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA, MACEIÓ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Holderbaum_etal_2012.pdf) *Resumo*

- [**LUGARINI C. & DIAS F.F. 2012. PLANO DE AÇÃO NACIONAL COMO INSTRUMENTO PARA A CONSERVAÇÃO DE PSITACÍDEOS. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lugarini__Fileto-Dias_2012.pdf) *Resumo*

- [**LUGARINI C. ET AL. 2012. MICROBIOTA CLOACAL DAS AVES SILVESTRES DA RESERVA BIOLÓGICA GUARIBAS, ESTADO DA PARAÍBA. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA, MACEIÓ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lugarini_etal_2012.pdf) *Resumo*

- [**MELO D.C. ET AL. 2012. CONHECIMENTO DA DISTRIBUIÇÃO DO PAPAGAIO-DO-MANGUE, AMAZONA AMAZONICA (LINNAEUS, 1766) (AVES, PSITTACIDAE) NO ESTADO DA PARAIBA. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA, MACEIÓ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Melo_etal_2012.pdf) *Resumo*

- [**VIEIRA B.P. ET AL. 2012. AVIFAUNA DA RESERVA BIOLÓGICA MARINHA DO ARVOREDO, SANTA CATARINA, BRASIL. XIX CONGRESSO BRASILEIRO DE ORNITOLOGIA, MACEIÓ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Vieira_etal_2012.pdf) *Resumo*

- OMETTO T. ET AL. 2012. **SURVEILLANCE OF WEST NILE VIRUS IN BRAZIL**. FAMERP-UTMB: EMERGING INFECTIONS IN THE AMERICAS - COMMON INTERESTS AND COLLABORATION BETWEEN BRAZIL AND USA (V.1), SÃO JOSÉ DO RIO PRETO, BRASIL.

- [**PAIXAO R.M.C. ET AL. 2012. ESTUDO DO HÁBITO DE APRISIONAR PASSERIFORMES NO MUNICÍPIO DE PILAR, PARAÍBA, BRASIL. XXIX CONGRESSO BRASILEIRO DE ZOOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Paixao_etal_2012.pdf) *Resumo*

- [**VANSTREELS R.E.T. (ORG.) ET AL. 2012. MANUAL DE CAMPO PARA A COLHEITA E ARMAZENAMENTO DE INFORMAÇÕES E AMOSTRAS BIOLÓGICAS PROVENIENTES DE PINGUINS-DE-MAGALHÃES (SPHENISCUS MAGELLANICUS). 2ED. CENTRO NACIONAL DE PESQUISA E CONSERVAÇÃO DE AVES SILVESTRES - CEMAVE, SÃO PAULO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Manual_Pinguins.pdf) *Manual*

- RUOPPPOLO V. ET AL. 2012. **REAVISTAMENTOS DE PINGUINS-DE-MAGALHÃES PETROLIZADOS, REABILITADOS E ANILHADOS NA AMÉRICA DO SUL, 2000-2010**. 2^O^ CONGRESSO LATINO-AMERICANO DE REABILITAÇÃO DE FAUNA MARINHA, RIO GRANDE, BRASIL.

- [**FAVARO F.L. 2011. AVES DO PARQUE NACIONAL DA SERRA DO PARDO, PARÁ, BRASIL: LEVANTAMENTO INICIAL. ORNITHOLOGIA 4(2):91-103**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Favaro_F_2011.pdf) *Artigo completo*

- [**SERAFINI P.P. ET AL. 2011. ANÁLISE NUTRICIONAL NA DIETA DO PAPAGAIO-DE-CARA-ROXA AMAZONA BRASILIENSIS NO LITORAL SUL DO ESTADO DE SÃO PAULO. ORNITHOLOGIA 4(2):104-109**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_etal_2011.pdf) *Artigo completo*

- [**ANJOS L. ET AL. 2011. BIRD SPECIES ABUNDANCE?OCCUPANCY PATTERNS AND SENSITIVITY TO FOREST FRAGMENTATION: IMPLICATIONS FOR CONSERVATION IN THE BRAZILIAN ATLANTIC FOREST. BIOLOGICAL CONSERVATION 144:2213-2222**](https://www.sciencedirect.com/science/article/abs/pii/S0006320711002114) *Artigo completo*

- [**SERAFINI P.P. 2011. INVESTIGAÇÃO SOROLÓGICA DE ANTICORPOS CONTRA LEPTOSPIRA SPP. EM ROEDORES SILVESTRES E MARSUPIAIS DE UNIDADES DE CONSERVAÇÃO DA ILHA RASA, GUARAQUEÇABA, PARANÁ, BRASIL. CIÊNCIA VETERINÁRIA NOS TRÓPICOS 14(1/2/3):54-58**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_etal_resumo_2011.pdf) *Comunicação*

- [**SCHUNCK F. ET AL. 2011. PLANO DE AÇÃO PARA A CONSERVAÇÃO DOS PAPAGAIOS DA MATA ATLÂNTICA. SÉRIE ESPÉCIES AMEAÇADAS 20, ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/PAN_Papagaios_2011.pdf) *Plano de Ação Nacional*

- [**VALENTE R. ET AL (ORGS.). 2011. CONSERVAÇÃO DE AVES MIGRATÓRIAS NEÁRTICAS NO BRASIL. CONSERVAÇÃO INTERNACIONAL, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Livro_Aves_migratorias_nearticas_no_brasil.pdf) *Livro*

- [**NASCIMENTO J.L.X. 2011. PARQUE NACIONAL DA LAGOA DO PEIXE. IN: CONSERVAÇÃO DE AVES MIGRATÓRIAS NEÁRTICAS NO BRASIL. CONSERVAÇÃO INTERNACIONAL, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Livro_Aves_migratorias_nearticas_no_brasil_Conservation_International.pdf) *Capítulo*

- [**OLIVEIRA A.C. ET AL. 2011. GUIA PARA OBSERVAÇÃO DAS AVES DO PARQUE NACIONAL DE BRASÍLIA. INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/GUIA-AVES-PNB-COMPLETO.pdf) *Guia*

- [**SERAFINI P. 2011. SISTEMA NACIONAL DE ANILHAMENTO (CEMAVE) E OS PINGUINS-DE-MAGALHÃES. BOLETIM PINGUINS NO BRASIL 1:5**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_PinguinsNoBrasil_2011.pdf) *Nota*

- [**ALVES F. ET AL. 2011. O CONHECIMENTO ORNITOLÓGICO NA BACIA HIDROGRÁFICA DO RIO SÃO FRANCISCO. IN: DIAGNÓSTICO DO MACROZONEAMENTO ECOLÓGICO-ECONÔMICO DA BACIA HIDROGRÁFICA DO RIO SÃO FRANCISCO. IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/O_conhecimento_ornitologico_da_BHSF.pdf) *Capítulo*

- [**ALBUQUERQUE M.C.F. ET AL. 2011. ECTOPARASITES, HEMOPARASITES AND GASTROINTESTINAL PARASITES IN WILD BIRDS OF GUARIBAS BIOLOGICAL RESERVE, PARAÍBA STATE, BRASIL. PRELIMINARY RESULTS. IX CONGRESSO DE ORNITOLOGIA NEOTROPICAL, CUSCO, PERU.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Feitosa_etal_resumo_2011.pdf) *Resumo*

- [**BRAGA I.C. ET AL. 2011. POPULATION VIABILITY ANALYSIS OF LEAR'S MACAW ANODORHYNCHUS LEARI. IX CONGRESSO DE ORNITOLOGIA NEOTROPICAL, CUSCO, PERU.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Braga_etal_Peru.pdf) *Resumo*

- [**ROOS A.L. ET AL. 2011. ESTRATEGIA BRASILEÑA PARA LA CONSERVACIÓN DE LAS AVES. IX CONGRESSO DE ORNITOLOGIA NEOTROPICAL, CUSCO, PERU.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Roos_etal_Peru.pdf) *Resumo*

- [**MELO D.C. ET AL. 2011. CONHECIMENTO DA DISTRIBUIÇÃO DO PAPAGAIO-DO-MANGUE, AMAZONA AMAZONICA (LINNAEUS, 1766) (AVES, PSITTACIDAE) NO ESTADO DA PARAÍBA. III SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE-IPERÓ/SP, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_Melo_etal_III_S_ICMBio.pdf) *Resumo*

- SCHMIDT E.M.S. ET AL. 2011. **DETERMINAÇÃO DAS CONCENTRAÇÕES DE PROTEÍNAS PLASMÁTICAS TOTAIS DE PAPAGAIO-DA-CARA-ROXA (AMAZONA BRASILIENSIS, LINNAEUS, 1758) E PAPAGAIO-VERDADEIRO (AMAZONA AESTIVA, LINNAEUS, 1758) POR REFRATOMETRIA E PELO MÉTODO DO BIURETO**. CONGRESSO MEDVEP DE ESPECIALIDADES VETERINÁRIAS, CURITIBA, BRASIL.

- [**HURTADO R.F. ET AL. 2011. REAL TIME RT-PCR DETECTION OF AVIAN INFLUENZA VIRUS AND NEWCASTLE DISEASE VIRUS IN PELAGIC BIRDS FROM FERNANDO DE NORONHA ARCHIPELAGO, BRAZIL. 60TH ANNUAL INTERNATIONAL CONFERENCE OF THE WILDLIFE DISEASE ASSOCIATION (WDA), QUEBEC, CANADA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/WDA_2011_RealTimeRTPCRInfluenza.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2011. SEABIRD POPULATION HEALTH MONITORING IN A BRAZILIAN OCEANIC ISLAND: CHLAMYDOPHILA PSITTACI SURVEYS ON BREEDING PROCELARIIFORMES AND PHAETHONTIFORMES. 60TH INTERNATIONAL CONFERENCE OF THE WILDLIFE DISEASE ASSOCIATION (WDA), QUEBEC, CANADA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/WDA_2011_Seabirdhealth.pdf) *Resumo*

- [**MESTRE L.A.M. ET AL. 2010. ANÁLISE DAS RECUPERAÇÕES NO BRASIL DE AVES ANILHADAS NO EXTERIOR ENTRE 1927 E 2006. ORNITHOLOGIA 4(1):15-35**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_etal_Recuperacoes_2010.pdf) *Artigo completo*

- [**ERRATA (MESTRE L.A.M. ET AL. 2010. ANÁLISE DAS RECUPERAÇÕES NO BRASIL DE AVES ANILHADAS NO EXTERIOR ENTRE 1927 E 2006. ORNITHOLOGIA 4(1):15-35)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/errata_Mestre.pdf) *Errata*

- [**BARBOSA-FILHO R.C. & VOOREN C.M. 2010. ABUNDÂNCIA, ESTRUTURA ETÁRIA E RAZÃO SEXUAL DO ATOBÁ-MARROM SULA LEUCOGASTER (PELECANIFORMES: SULIDAE) NO ARQUIPÉLAGO DE SÃO PEDRO E SÃO PAULO, BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 18(3):157-163**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BarbosaFilhoVooren_2010.pdf) *Artigo completo*

- [**CARVALHO D.L. ET AL. 2010. PRIMEIRO REGISTRO DO ALBATROZ-DE-NARIZ-AMARELO THALASSARCHE CHLORORHYNCHOS (PROCELLARIIFORMES: DIOMEDEIDAE) NO ESTADO DO MARANHÃO, BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 18(3):258-260**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Carvalho_etal_2010.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. & SANTOS P.J.P. 2010. PREPARAÇÃO PRÉ-MIGRATÓRIA DE STERNA HIRUNDO (CHARADRIIFORMES, STERNIDAE) NO PARQUE NACIONAL DA LAGOA DO PEIXE, RIO GRANDE DO SUL. REVISTA BRASILEIRA DE ORNITOLOGIA 18(4):307-314**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento__Santos_2010.pdf) *Artigo completo*

- [**NUNES M.F.C. ET AL. 2010. THE CATTLE EGRET (BUBULCUS IBIS) ON FERNANDO DE NORONHA ARCHIPELAGO: HISTORY AND POPULATION TRENDS. REVISTA BRASILEIRA DE ORNITOLOGIA 18(4):315-327**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nunes_etal_2010.pdf) *Artigo completo*

- [**BUEHLER D.M. ET AL. 2010. LOCAL MORTALITY EVENTS IN MIGRATING SANDPIPERS (CALIDRIS) AT A STAGING SITE IN SOUTHERN BRAZIL. WADER STUDY GROUP BULLETIN 117(3):150–156**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Buehler_etal_2010WSGB.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. & SANTOS P.J.P. 2010. MONITORING OF WHITE-RUMPED SANDPIPER (CALIDRIS FUSCICOLLIS) IN LAGOA DO PEIXE NATIONAL PARK, RIO GRANDE DO SUL, BRAZIL. ORNITOLOGÍA NEOTROPICAL 21:371-381**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/MONITORING_OF_WHITE-RUMPED_SANDPIPER_CAL.pdf) *Artigo completo*

- [**NILES L.J. ET AL. 2010. UPDATE TO THE STATUS OF THE RED KNOT CALIDRIS CANUTUS IN THE WESTERN HEMISPHERE, APRIL 2010. WADER STUDY GROUP BULLETIN 117:1-19**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/redknot_update4-10.pdf) *Artigo completo*

- [**AMORIM F.A. ET AL. 2010. AVIFAUNA FROM THE SÃO FRANCISCO RIVER BASIN. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/945_Amorim_et_al_2010.pdf) *Resumo*

- [**LACERDA R. ET AL. 2010. WORKSHOP: LINKING BANDERS AND BIRD CONSERVATION ACROSS THE HEMISPHERE. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/993_Lacerda_et_al_2010.pdf) *Resumo*

- [**MESTRE L.A.M. ET AL. 2010. ESTIMATING POPULATION SIZE OF PHAETON LEPTURUS IN FERNANDO DE NORONHA ARCHIPELAGO (NORTHEAST BRAZIL). 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/776__Mestre_et_al_2010.pdf) *Resumo* - [**(POSTER)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_etal_2010.jpg) *Poster*

- [**MESTRE L.A.M. ET AL. 2010. ABUNDANCE OF TERRESTRIAL ENDEMIC BIRDS OF FERNANDO DE NORONHA ARCHIPELAGO (BRAZIL). 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/613_Mestre_et_al_2010.pdf) *Resumo* - [**(POSTER)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_etal_Noronha_2010.jpg) *Poster*

- [**NUNES M.F.C. ET AL. 2010. POPULATION STATUS OF BIRDS IN THE MURICI ECOLOGICAL STATION, ALAGOAS, BRAZIL. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/875_Nunes_et_al_2010.pdf) *Resumo*

- [**OLIVEIRA K.G. ET AL. 2010. MONITORED RELEASE OF LEAR'S MACAW BACK TO THE WILD (ANODORHYNCHUS LEARI, AVES: PSITTACIDAE) IN BAHIA, BRAZIL. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/826_Oliveira_et_al_2010.pdf) *Resumo*

- [**OLIVEIRA A.C. & MACEDO R.H. 2010. INTERACION BETWEEN BUFF-NECKED IBISES AND TOWERS FOR HIGH VOLTAGE TRANSMISSION LINES IN BRAZIL. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/966_Ailton.pdf) *Resumo*

- [**SANTOS-NETO J.R. ET AL. 2010. POPULATION ACTIVE IN REPRODUCTION AND POPULATION ASSESSMENT OF LEAR'S MACAW (ANODORHYNCHUS LEARI) IN BAHIA, BRAZIL. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SantosNeto_etal_Abstract_IOC_2010.pdf) *Resumo*

- [**SIMAO-NETO I. & SERAFINI P.P. 2010. LONG-TERM BANDING DATA FROM A RAMSAR SITE IN SOUTHERN BRAZIL. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/675_Simao__Serafini_2010.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2010. BANDING AND MONITORING PROGRAMS OF MAGELLANIC PENGUINS ON THE BRAZILIAN COAST IN 2008. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_et_al_Banding_2010.pdf) *Resumo* - [**(POSTER)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_etal_2010.jpg) *Poster*

- [**SOUZA E.A. ET AL. 2010. AVIFAUNA FROM BOQUEIRÃO DA ONÇA REGION, SÃO FRANCISCO RIVER BASIN, BAHIA, BRAZIL. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS, CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/894_Souza_et_al_2010.pdf) *Resumo*

- AMORIM M.S. ET AL. 2010. **BANCO DE DADOS SOBRE AVES AMEAÇADAS DA FLORESTA ATLÂNTICA NORDESTINA**. XXVIII CONGRESSO BRASILEIRO DE ZOOLOGIA, BELÉM, BRASIL.

- [**SERRANO I.L. 2010. DISTRIBUIÇÃO E CONSERVAÇÃO DE AVES MIGRATÓRIAS NEÁRTICAS DA ORDEM CHARADRIIFORMES (FAMÍLIAS CHARADRIIDAE E SCOLOPACIDAE) NO BRASIL. TESE DE DOUTORADO, UFPA/MPEG, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Tese_Ines_2010.pdf) *Tese*

- [**NASCIMENTO J.L.X. 2010. MONITORAMENTO DE AVES MIGRATÓRIAS DA ORDEM CHARADRIIFORMES NO PARQUE NACIONAL DA LAGOA DO PEIXE, RIO GRANDE DO SUL. TESE DE DOUTORADO, UFPE, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/TeseMonitoramentoCharadriiLPJLXN_-_Final.pdf) *Tese*

- [**ANJOS L. ET AL. 2010. TÉCNICAS DE LEVANTAMENTO QUANTITATIVO DE AVES EM AMBIENTE FLORESTAL: UMA ANÁLISE COMPARATIVA BASEADA EM DADOS EMPÍRICOS. ORNITOLOGIA E CONSERVAÇÃO: CIÊNCIA APLICADA, TÉCNICAS DE PESQUISA E LEVANTAMENTO. TECHNICAL BOOKS, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Anjos_etal_2010.pdf) *Capítulo*

- [**SERAFINI P.P. ET AL. 2010. REPORT OF BILATERAL OCULAR LESIONS ASSOCIATED WITH PROTEUS IN A GIANT PETREL (MACRONECTES HALLI) IN SOUTHERN BRAZIL. 59TH ANNUAL INTERNATIONAL CONFERENCE OF THE WILDLIFE DISEASE ASSOCIATION (WDA), IGUAZÚ, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/WDA_2010_ReportlesionMacronectes.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2010. REPORT OF A SERRATIA MARCESCENS RECURRENT INFECTION IN THE ENDANGERED VINACEOUS-BREASTED PARROT (AMAZONA VINACEA) WITH POOR RESPONSE TO SURGERY AND ANTIBIOTIC THERAPY. 59TH ANNUAL INTERNATIONAL CONFERENCE OF THE WILDLIFE DISEASE ASSOCIATION (WDA), IGUAZÚ, ARGENTINA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/WDA_2010_Serratia.pdf) *Resumo*

- [**GOMES A.L.M. ET AL. 2010. PROJETO NACIONAL DE MONITORAMENTO DO PINGUIM-DE-MAGALHÃES SPHENISCUS MAGELLANICUS. ICMBIO/MMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cartilha_Projeto_Nacional_Pinguin.pdf) *Cartilha*

- [**KOLESNIKOVAS C.K.M. ET AL. 2010. COLETA E ANÁLISE DE DADOS BIOMÉTRICOS DE PASSERIFORMES NO CENTRO DE TRIAGEM DE ANIMAIS SILVESTRES (CETAS) DE FLORIANÓPOLIS/SC. V SIMPÓSIO BRASILEIRO SOBRE ANIMAIS SILVESTRES E SELVAGENS, VIÇOSA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Kolesnikovas_etal_2010.pdf) *Resumo*

- [**SERAFINI P.P. ET AL. 2010. CRIAÇÃO DA REDE DE ENCALHES DE AVES MARINHAS DENTRO DA ÁREA DE PROTEÇÃO AMBIENTAL DA BALEIA FRANCA NO SUL DO BRASIL. V SIMPÓSIO BRASILEIRO SOBRE ANIMAIS SILVESTRES E SELVAGENS, VIÇOSA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Serafini_et_al_2010.pdf) *Resumo*

- [**ARAUJO J.L.B. & ROOS A.L. 2010. ESTUDO DA DIETA DA AVIFAUNA DE TABULEIRO NA REBIO GUARIBAS, PARAÍBA, BRASIL. II SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/II_Sem_ICMBio_2010.pdf) *Resumo*

- [**TEIXEIRA G.D. & ROOS A.L. 2010. ESTUDO DA REPRODUÇÃO E MUDA DE PENAS DA AVIFAUNA DE TABULEIRO NA REBIO GUARIBAS. II SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO INSTITUTO CHICO MENDES DE CONSERVAÇÃO DA BIODIVERSIDADE, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/II_Sem_ICMBio_2010.pdf) *Resumo* - [**(POSTER)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Pibic_2011_Dryander.jpg) *Poster*

- [**PALUDO D. ET AL. 2010. POPULATION EXPANSION OF THE ENDANGERED SCARLET IBIS (EUDOCIMUS RUBER) IN THE SOUTHEAST OF BRAZIL. 25TH INTERNATIONAL ORNITHOLOGICAL CONGRESS. CAMPOS DO JORDÃO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Paludo_etal_Resumos-IOC-2010.pdf) *Resumo*

- [**ROOS A.L. 2010. CAPTURANDO AVES. IN: ORNITOLOGIA E CONSERVAÇÃO: CIÊNCIA APLICADA, TÉCNICAS DE PESQUISA E LEVANTAMENTO. EDITORA TECHNICAL BOOKS, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Capturando_aves_Roos_2010.pdf) *Capítulo*

**2009-2000**

- [**BARBOSA-FILHO R.C. ET AL. 2009. A GARÇA VAQUEIRA (BULBUCUS IBIS LINNAEUS, 1758) E O ATOBÁ-DE-PÉ-VERMELHO (SULA SULA LINNAEUS, 1766) NO ARQUIPÉLAGO DE FERNANDO DE NORONHA: UMA ABORDAGEM ECOLÓGICA COMPARATIVA. ORNITHOLOGIA 3(2):101-114**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BarbosaFilho_etal_2009.pdf) *Artigo completo*

- [**FAVARO F.L. & FLORES J.M. 2009. AVES DA ESTAÇÃO ECOLÓGICA TERRA DO MEIO, PARÁ, BRASIL: RESULTADOS PRELIMINARES. ORNITHOLOGIA 3(2):115-131**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Favaro__Flores_2009.pdf) *Artigo completo*

- [**PAGANO I.S.A. ET AL. 2009. AVES DEPOSITADAS NO CENTRO DE TRIAGEM DE ANIMAIS SILVESTRES NA PARAÍBA: UMA AMOSTRA DO TRÁFICO DE AVES SILVESTRES NO ESTADO. ORNITHOLOGIA 3(2):132-144**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Pagano_etal_2009.pdf) *Artigo completo*

- [**SOUZA E.A. ET AL. 2009. AMPLIAÇÃO DA ÁREA DE OCORRÊNCIA DO BEIJA-FLOR-DE-GRAVATINHA-VERMELHA AUGASTES LUMACHELLA (LESSON, 1838) (TROCHILIDAE). ORNITHOLOGIA 3(2):145-148**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Souza_etal_2009.pdf) *Nota*

- [**VOLPATO G.H. ET AL. 2009. THE USE OF THE POINT COUNT METHOD FOR BIRD SURVEY IN THE ATLANTIC FOREST. REVISTA BRASILEIRA DE ZOOLOGIA 26:74-78**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Volpato_etal_2009.pdf) *Artigo completo*

- [**MESTRE L.A.M. ET AL. 2009. DADOS BIOLÓGICOS DE PUFFINUS LHERMINIERI ANILHADOS EM FERNANDO DE NORONHA EM 2005 E 2006. REVISTA BRASILEIRA DE ORNITOLOGIA 17(1):65-69**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_etal_2009.pdf) *Nota*

- [**GILLINGS S. ET AL. 2009. STAGING BEHAVIOR IN RED KNOT (CALIDRIS CANUTUS) IN DELAWARE BAY: IMPLICATIONS FOR MONITORING MASS AND POPULATION SIZE. THE AUK 126(1):54-63**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/auk.2009.06247.pdf) *Artigo completo*

- [**ALTEFF E. ET AL. 2009. AVIFAUNA DA ESTAÇÃO ECOLÓGICA SERRA DAS ARARAS, PORTO ESTRELA/CÁCERES - MT: REGISTROS OBTIDOS DURANTE O CURSO REGIONAL DE ANILHAMENTO DE AVES UFMT/CEMAVE, 2008. XVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, ARACRUZ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Avifauna_Araras_XVIICBO.pdf) *Resumo*

- [**SOUZA E A. 2009. TABELA DE VIDA DE ZENAIDA AURICULATA (DES MURS, 1847) (AVES, COLUMBIDAE): INFORMAÇÃO IMPORTANTE À CONSERVAÇÃO E O MANEJO. XVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, ARACRUZ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ellivan_XVIICBO.pdf) *Resumo*

- [**SOUSA A.E.B.A. ET AL. 2009. NOVOS REGISTROS DE AVES PARA O PARQUE NACIONAL DO CATIMBAU, PERNAMBUCO, BRASIL. XVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, ARACRUZ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Emanuel_Catimbau_XVIICBO.pdf) *Resumo*

- [**ROOS A.L. ET AL. 2009. ANÁLISE DAS RECUPERAÇÕES DE AVES ANILHADAS NO EXTERIOR ENTRE 1928 E 2006. XVII CONGRESSO BRASILEIRO DE ORNITOLOGIA, ARACRUZ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Roos_Anilhadas_XVIICBO.pdf) *Resumo*

- [**MESTRE L.A.M. & BIERREGAARD JR R.O. 2009. THE ROLE OF AMAZONIAN RIVERS FOR WINTERING OSPREYS (PANDION HALIAETUS): CLUES FROM NORTH AMERICAN BAND RECOVERIES IN BRAZIL BETWEEN 1937 AND 2006. STUDIES ON NEOTROPICAL FAUNA AND ENVIRONMENT 44(3):141–147**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_SNFE_2009.pdf) *Artigo completo*

- [**AMORIM M.S. & ROOS A.L. 2009. BANCO DE DADOS SOBRE AVES BRASILEIRAS AMEAÇADAS DE EXTINÇÃO: ESTIMATIVA DO TAMANHO POPULACIONAL. I SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_I_S_ICMBio_Amorim.pdf) *Resumo*

- [**SANTOS D.S. & ROOS A.L. 2009. BANCO DE DADOS SOBRE AVES BRASILEIRAS AMEAÇADAS DE EXTINÇÃO: ATUALIZAÇÃO DOS MAPAS DE DISTRIBUIÇÃO E AVALIAÇÃO DA IMPORTANCIA DAS UNIDADES DE CONSERVAÇÃO. I SEMINÁRIO DE PESQUISA E INICIAÇÃO CIENTÍFICA DO ICMBIO, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_I_S_ICMBio_Santos.pdf) *Resumo*

- [**KOLESNIKOVAS C.K.M. ET AL. 2009. RECUPERAÇÃO DE PINGUINS DE MAGALHÃES CONTAMINADOS POR ÓLEO EM FLORIANÓPOLIS/SC, BRASIL. XII CONGRESSO E XVIII ENCONTRO DA ASSOCIAÇÃO BRASILEIRA DE VETERINÁRIOS DE ANIMAIS SELVAGENS (ABRAVAS), ÁGUAS DE LINDÓIA, BRASIL**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Kolesnikovas_etal_resumo_2009.pdf) *Resumo*

- [**SANTOS D.S. ET AL. 2009. REPRESENTATIVIDADE DE ESPÉCIES DE AVES AMEAÇADAS NO TRÁFICO ILEGAL NA PARAÍBA A PARTIR DE DADOS DO CETAS/IBAMA/PB. IX CONGRESSO DE ECOLOGIA DO BRASIL, SÃO LOURENÇO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Santos_etal_2009.pdf) *Resumo expandido*

- SOUZA E.A. & SILVA L.F.G. 2009. **CONTRIBUIÇÃO AO PROJETO DE MANEJO INTEGRADO DA BACIA DO RIO GRAMAME PB**. A BACIA DO RIO GRAMAME: BIODIVERSIDADE, USO E CONSERVAÇÃO. EDUEPB, CAMPINA GRANDE, BRASIL.

- [**SOUSA A.E.B.A. & BARBOSA A.E.A. 2008. REGISTRO DE OCORRÊNCIA DA ARARA-AZUL-DE-LEAR ANODORHYNCHUS LEARI (BONAPARTE 1856) NO MUNICÍPIO DE MONTE SANTO, BAHIA. ORNITHOLOGIA 3(1):64-66**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Sousa__Barbosa_NotaAleari_2008.pdf) *Nota*

- [**SANTOS-NETO J.R. & CAMANDAROBA M. 2008. MAPEAMENTO DOS SÍTIOS DE ALIMENTAÇÃO DA ARARA-AZUL-DE-LEAR ANODORHYNCHUS LEARI (BONAPARTE, 1856). ORNITHOLOGIA 3(1):1-17**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Santos_Neto__Camandaroba_Aleari_2008.pdf) *Artigo completo*

- [**SCHULZ-NETO A. ET AL. 2008. MUDA E PARÂMETROS BIOMÉTRICOS DE AVES MIGRATÓRIAS NO NORTE DO BRASIL. ORNITHOLOGIA 3(1):21-33**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Schulz-Neto_etal_migratorias_2008.pdf) *Artigo completo*

- [**BARBOSA-FILHO R.C. ET AL. 2008. 33 ANOS DE ANILHAMENTO NO BRASIL. XVI CONGRESSO BRASILIEIRO DE ORNITOLOGIA, PALMAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BarbosaFilho_etal_Resumo_2008.pdf) *Resumo*

- [**OLIVEIRA A.C. 2008. OCUPAÇÃO AMBIENTAL E CARACTERÍSTICAS POPULACIONAIS DE CURICACAS THERISTICUS CAUDATUS EM LINHAS DE TRANSMISSÃO DE ALTA TENSÃO. DISSERTAÇÃO DE MESTRADO. UNB, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AiltonCarneirodeOliveira_2008.pdf) *Dissertação de Mestrado*

- [**SOUZA E.A. ET AL. 2008. AS AVES DO PARQUE NACIONAL DO CABO ORANGE: GUIA DE CAMPO. CEMAVE/ICMBIO, JOÃO PESSOA, PB.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/aves-do-parque-nacional-do-cabo-orange.pdf) *Guia*

- [**BARBOSA-FILHO R.C. & SOUZA A.E.B. 2008. MONITORAMENTO DA GARÇA-VAQUEIRA (BULBUCUS IBIS) NO PARQUE NACIONAL MARINHO E NA ÁREA DE PROTEÇÃO AMBIENTAL DE FERNANDO DE NORONHA. BOLETIM ELETRÔNICO DO CEMAVE 2(2):2**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BarbosaFilho_BCE_2008.pdf) *Nota de divulgação científica*

- [**LACERDA R.C.A. & RODRIGUES R.C. 2008. PROPOSTA PARA MARCAÇÃO DE CHARADRIIFORMES MIGRATÓRIOS NO BRASIL COM O USO DE BANDEIROLAS COLORIDAS CODIFICADAS. XVI CONGRESSO BRASILEIRO DE ORNITOLOGIA, PALMAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/LacerdaRodrigues_XVICBO.pdf) *Resumo*

- [**ROOS A.L. 2008. PINGUINS-DE-MAGALHÃES (SPHENISCUS MAGELLANICUS) NO NORDESTE: MIGRANTES OU ERRANTES. BOLETIM ELETRÔNICO DO CEMAVE 2(2):1**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Roos_BEC_2008.pdf) *Nota de divulgação científica*

- [**MORRISON R.I.G. ET AL. 2008. BIRDS IN THE PANTANAL: DISTRIBUTION OF NEARTIC SHOREBIRDS AND OTHER WATER SPECIES IN THE PANTANAL. WWF-BRASIL, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Shorebirds_Pantanal.pdf) *Livro*

- [**MORRISON R.I.G. ET AL. 2008. AVES MIGRATÓRIAS NO PANTANAL: DISTRIBUIÇÃO DE AVES LIMÍCOLAS NEÁRTICAS E OUTRAS ESPÉCIES AQUÁTICAS NO PANTANAL. WWF-BRASIL, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Shorebirds_Pantanal_Portugues.pdf) *Livro*

- [**PAGANO I.S.A. 2008. AVES DEPOSITADAS NO CENTRO DE TRIAGEM DE ANIMAIS SILVESTRES DO IBAMA NA PARAÍBA: UMA AMOSTRA DO TRÁFICO DE AVES SILVESTRES NO ESTADO. MONOGRAFIA DE GRADUAÇÃO, UFPB, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/MONO_ISALES___COMPLETA.pdf) *Monografia*

- [**MESTRE L.A.M. 2007. RECUPERAÇÕES NO BRASIL DE FALCÕES-PEREGRINOS (FALCO PEREGRINUS) ANILHADOS NA AMÉRICA DO NORTE ENTRE 1967 E 2001. ORNITHOLOGIA 2(2):72-80**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_RecuperacoesFalco_2007.pdf) *Artigo completo*

- [**MESTRE L.A.M. 2007. REGISTROS DAS MIGRAÇÕES DE TRINTA-RÉIS-BOREAL STERNA HIRUNDO: ANÁLISE DAS RECUPERAÇÕES DE INDIVÍDUOS MARCADOS NA AMÉRICA DO NORTE (1928 – 2005) E BRASIL (1983 – 2005). ORNITHOLOGIA 2(2):81-87**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mestre_RecuperacoesSterna_2007.pdf) *Artigo completo*

- [**BARBOSA FILHO R.C. ET AL. 2007. INFORMATIVO DO SISTEMA NACIONAL DE ANILHAMENTO (1973-1985). ORNITHOLOGIA 2(2):88-118**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BarbosaFilho_etal_SNA_2007.pdf) *Artigo completo*

- [**EFE M.A. ET AL. 2007. AVIFAUNA DA ESTAÇÃO ECOLÓGICA DE CARIJÓS, FLORIANÓPOLIS - SC. ORNITHOLOGIA 2(1):1-13**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_etal_AvifaunaCarijos_2007.pdf) *Artigo completo*

- [**BARBOSA FILHO R.C. ET AL. 2007. INFORMATIVO DO SISTEMA NACIONAL DE ANILHAMENTO (1986-1995). ORNITHOLOGIA 2(2):119-169**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BarbosaFilho_etal_SNA_2007b.pdf) *Artigo completo*

- [**EFE M.A. ET AL. 2007. AVIFAUNA DA ÁREA DE PROTEÇÃO AMBIENTAL DO IBIRAPUITÃ, RIO GRANDE DO SUL, BRASIL. ORNITHOLOGIA 2(1):14-24**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_etal_AvifaunaIbirapuita_2007.pdf) *Artigo completo*

- [**CARDOSO T.A.L. & NASCIMENTO J.L.X. 2007. AVALIAÇÃO DE ATIVIDADES TURÍSTICAS PREJUDICIAIS À PERMANÊNCIA DE AVES MIGRATÓRIAS NA COROA DO AVIÃO, PERNAMBUCO, BRASIL. ORNITHOLOGIA 2(2):170-177**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cardoso__Nascimento_2007.pdf) *Artigo completo*

- [**SOUZA E.A. ET AL. 2007. ESTIMATIVAS POPULACIONAIS DE AVOANTES ZENAIDA AURICULATA (AVES COLUMBIDAE, DES MURS, 1874) EM COLÔNIAS REPRODUTIVAS NO NORDESTE DO BRASIL. ORNITHOLOGIA 2(1):28-33**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Souza_etal_EstimativasZenaida_2007.pdf) *Artigo completo*

- [**SANTOS-NETO J.R. & CAMANDAROBA M. 2007. AMPLIAÇÃO DA ÁREA DE OCORRÊNCIA DA ARARA-AZUL-DE-LEAR ANODORHYNCHUS LEARI (BONAPARTE 1856). ORNITHOLOGIA 2(1):63-64**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Santos_Neto__Camandaroba_nota_2007.pdf) *Nota*

- [**BARBOSA-FILHO R.C. & VOOREN C.M. 2007. CENSOS DE AVES OCEÂNICAS NO NORDESTE DO BRASIL. XV CONGRESSO BRASILEIRO DE ORNITOLOGIA, PORTO ALEGRE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BarbosaFilhoVooren_XVCBO.pdf) *Resumo*

- [**PAGANO I.S.A. ET AL. 2007. AVES DEPOSITADAS NO CENTRO DE TRIAGEM DE ANIMAIS SILVESTRES DO IBAMA NA PARAÍBA: UMA AMOSTRA DO TRÁFICO DE AVES SILVESTRES NO ESTADO. XV CONGRESSO BRASILEIRO DE ORNITOLOGIA, PORTO ALEGRE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Pagano_etal_XVCBO.pdf) *Resumo*

- [**SILVA-NETO G.F. ET AL. 2007. COMPORTAMENTO ALIMENTAR DE ARARAS-AZUIS-DE-LEAR ANODORHYNCHUS LEARI, EM CATIVEIRO E EM VIDA LIVRE. XV CONGRESSO BRASILEIRO DE ORNITOLOGIA, PORTO ALEGRE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SilvaNeto_etal_XVCBO.pdf) *Resumo*

- [**NILES L.J. ET AL. 2007. STATUS OF THE RED KNOT (CALIDRIS CANUTUS RUFA) IN THE WESTERN HEMISPHERE. U.S. FISH AND WILDLIFE SERVICE, PLEASANTVILLE, USA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Niles_etal_Calidris_canutus_2007.pdf) *Livro*

- [**NUNES M.F.C. & GALETTI M. 2007. USE OF FOREST FRAGMENTS BY BLUE-WINGED MACAWS (PRIMOLIUS MARACANA) WITHIN A FRAGMENTED LANDSCAPE. BIODIVERSITY AND CONSERVATION 16:953-967**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/nunes2006.pdf) *Artigo completo*

- [**NUNES M.F.C. ET AL. 2007. ARE LARGE-SCALE DISTRIBUTIONAL SHIFTS OF THE BLUE-WINGED MACAW (PRIMOLIUS MARACANA) RELATED TO CLIMATE CHANGE? JOURNAL OF BIOGEOGRAPHY 34:816-827**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/nunes2007.pdf) *Artigo completo*

- [**COSTA E.S. & ROOS A.L. 2007. ANÁLISE DO IMPACTO DA CAÇA DA AVIFAUNA DO ESTADO DA PARAÍBA. IV SEMINÁRIO DE INICIAÇÃO CIENTÍFICA DO IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Emanuelle.pdf) *Resumo*

- [**ALVES F.A.A. & NASCIMENTO J.L.X. 2007. MONITORAMENTO DE AVES MIGRATÓRIAS NA ILHA DA COROA DO AVIÃO/PE. IV SEMINÁRIO DE INICIAÇÃO CIENTÍFICA DO IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Fabio_Anderson.pdf) *Resumo*

- [**SILVA-NETO G.F. ET AL. 2007. COMPORTAMENTO ALIMENTAR DE ARARAS-AZUIS-DE-LEAR, ANODORHYNCHUS LEARI (BONPARTE, 1856) PSITTACIDAE EM CATIVEIRO E EM VIDA LIVRE. IV SEMINÁRIO DE INICIAÇÃO CIENTÍFICA DO IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Gilberto.pdf) *Resumo*

- [**PAGANO I.S.A. ET AL. 2007. AVES DEPOSITADAS NO CENTRO DE TRIAGEM DE ANIMAIS SILVESTRES DO IBAMA NO ESTADO DA PARAÍBA, BRASIL. IV SEMINÁRIO DE INICIAÇÃO CIENTÍFICA DO IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Isales.pdf) *Resumo*

- [**SANTOS-NETO J.R. & GOMES D.M. 2007. PREDAÇÃO DE MILHO POR ARARA-AZUL-DE-LEAR, ANODORHYNCHUS LEARI (BONAPARTE, 1856) (AVES: PSITTACIDAE) EM SUA ÁREA DE OCORRÊNCIA NO SERTÃO DA BAHIA. ORNITHOLOGIA 2(1):41-46**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SantosNeto_Gomes_2007.pdf) *Artigo completo*

- [**OLIVEIRA A.C. & MACEDO R.H. 2007. BIOLOGIA REPRODUTIVA E MONITORAMENTO DE CURICACA (THERISTICUS CAUDATUS) EM LINHAS DE TRANSMISSÃO DE ENERGIA DA EXPANSION. IV CONGRESSO DE INOVAÇÃO TECNOLÓGICA EM ENERGIA ELÉTRICA - CITINEL, ARAXÁ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Oliveira__Macedo_BioReprCuricaca_LT_2007.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2006. MONITORAMENTO DA MARRECA-PARDA, ANAS GEORGICA (GMELIN, 1781) (ANSERIFORMES, ANATIDAE) NO RIO GRANDE DO SUL. ORNITHOLOGIA 1(2):115-120**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_MonitoramentoAnas_2006.pdf) *Artigo completo*

- [**EFE M.A. & FILIPPINI A. 2006. NIDIFICAÇÃO DO JOAO-DE-BARRO, FURNARIUS RUFUS (PASSERIFORMES, FURNARIIDAE) EM ESTRUTURAS DE DISTRIBUIÇÃO DE ENERGIA ELÉTRICA EM SANTA CATARINA. ORNITHOLOGIA 1(2):121-124**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/EfeFilippini_Furnariusrufus_2006.pdf) *Artigo completo*

- [**EFE M.A. ET AL. 2006. ANÁLISE DOS DADOS DE RECUPERAÇÃO DE SULA SPP. (PELICANIFORMES, SULIDAE) OCORRIDAS NO BRASIL ENTRE 1981 E 2000. ORNITHOLOGIA 1(2):125-133**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_etal_recuperacaoSula_2006.pdf) *Artigo completo*

- [**ROOS A.L. ET AL. 2006. AVIFAUNA DA REGIÃO DO LAGO DE SOBRADINHO: COMPOSIÇÃO, RIQUEZA E BIOLOGIA. ORNITHOLOGIA 1(2):135-160**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Roos_etal_Sobradinho_2006.pdf) *Artigo completo*

- [**MENEZES A.C. ET AL. 2006. MONITORAMENTO DA POPULAÇÃO DE ANODORYNCHUS LEARI (BONAPARTE, 1856), PSITTACIDAE, NA NATUREZA. ORNITHOLOGIA 1(2):109-114**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Menezes_etal_Ornithologia_2006.pdf) *Artigo completo*

- [**ARAUJO H.F.P. ET AL. 2006. COMPOSIÇÃO DA AVIFAUNA EM COMPLEXOS ESTUARINOS NO ESTADO DA PARAÍBA, BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 14(3):249-259**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Araujo_etal_2006.pdf) *Artigo completo*

- [**PEREIRA S.L. ET AL. 2006. BRAZIL. IN: CONSERVING CRACIDS: THE MOST THREATENED FAMILY OF BIRDS IN THE AMERICAS. HOUSTON MUSEUM OF NATURAL SCIENCE 6, HOUSTON, USA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cracideos_Brazil.pdf) *Capítulo*

- [**MESTRE L.A.M. 2006. MIGRAÇÕES DE FALCO PEREGRINUS ANILHADOS NA AMÉRICA DO NORTE E RECAPTURADOS NO BRASIL ENTRE 1967 E 2001. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/PainelCBO_LMestre2006ii.pdf) *Painel*

- [**MESTRE L.A.M. 2006. MIGRAÇÕES DA ÁGUIA-PESCADORA PANDION HALIAETUS ENTRE 1936 E 2003: RESULTADOS DAS RECUPERAÇÕES DE ANILHAS NORTE-AMERICANAS NO BRASIL. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/PandionMigration_LMestre.pdf) *Resumo expandido*

- [**CARVALHO P.J.B. & NASCIMENTO J.L.X. 2006. OBSERVAÇÃO DE ANILHAS COLORIDAS E CENSO DE CHARADRIIDAE, SCOLOPACIDAE E LARIDAE NA COROA DO AVIÃO, IGARASSU, PERNAMBUCO. III SEMINÁRIO DE INICIAÇÃO CIENTÍFICA DO IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_PedroJorge.pdf) *Resumo*

- [**CARDOSO T.A.L. & NASCIMENTO J.L.X. 2006. MONITORAMENTO DE AVES MIGRATÓRIAS NA ILHA DA COROA DO AVIÃO, NA COSTA NORTE DO ESTADO DE PERNAMBUCO, BRASIL. III SEMINÁRIO DE INICIAÇÃO CIENTÍFICA DO IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_Tiago.pdf) *Resumo*

- [**AMARAL A.C.A. ET AL. 2006. PRIMEIRA DESCRIÇÃO DE NINHO DE ARARA-AZUL-DE-LEAR ANODORHYNCHUS LEARI (BONAPARTE, 1856) PSITTACIDAE. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Amaral_etal_NinhoLeari_2006.pdf) *Resumo*

- [**BRAINER P.J. & NASCIMENTO J.L.X. 2006. OBSERVAÇÃO DE ANILHAS COLORIDAS E CENSO DE CHARADRIIDAE, SCOLOPACIDAE E LARIDAE NA COROA DO AVIÃO, IGARASSU, PERNAMBUCO. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Carvalho__Nascimento_2006.pdf) *Resumo*

- [**CARDOSO T.A.L. ET AL. 2006. AVALIAÇÃO DE UMA POPULAÇÃO DE CALIDRIS PUSILLA NA COROA DO AVIÃO, PERNAMBUCO, UTILIZANDO O PESO COMO PARÂMETRO. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cardoso_etal_2006.pdf) *Resumo*

- [**SANTOS-NETO J.R & AMARAL C.A. 2006. O PROJETO DE CONSERVAÇÃO DA ARARA-AZUL-DE-LEAR E O ENVOLVIMENTO DA POPULAÇÃO. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Santos__Amaral_2006.pdf) *Resumo*

- [**RAMOS S.R.A. ET AL. 2006. ECOTURISMO E OBSERVAÇÃO DE AVES NA FLORESTA NACIONAL DA RESTINGA DE CABEDELO - PB. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Ramos_etal_2006.pdf) *Resumo*

- [**SANTOS-NETO J.R. & CAMANDAROBA M. 2006. ARARA-AZUL-DE-LEAR ANODORHYNCHUS LEARI FORRAGEANDO CACHOS DE LICURI IMATUROS COMO FONTE DE RECURSO HÍDRICO. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Santos__Camandaroba_2006.pdf) *Resumo*

- [**SOUZA E.A. ET AL. 2006. ESTIMATIVAS POPULACIONAIS DE AVOANTES ZENAIDA AURICULATA (AVES COLUMBIDAE, DESMURS, 1847) EM COLÔNIAS REPRODUTIVAS NO NORDESTE DO BRASIL. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Souza_etal_2006.pdf) *Resumo*

- [**AMARAL A.C.A. & SOUZA E.A. 2006. NOTA SOBRE PREDAÇÃO DE GIRASSOL, HELIANTHUS ANNUS, POR ARRIBAÇÃS, ZENAIDA AURICULATA, EM MARINGÁ/PR. XIV CONGRESSO BRASILEIRO DE ORNITOLOGIA, OURO PRETO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Amaral__Souza_2006.pdf) *Resumo*

- RAMOS S.R.A. ET AL. 2006. **ECOTURISMO E LEVANTAMENTO DA AVIFAUNA NA FLORESTA NACIONAL DA RESTINGA DE CABEDELO - PARAÍBA**. XI CONGRESSO NORDESTINO DE ECOLOGIA, RECIFE, BRASIL. 

- PAZ R.J. ET AL. 2006. **UNIDADES DE CONSERVAÇÃO NO BRASIL - HISTÓRIA E LEGISLAÇÃO**. EDITORA UNIVERSITÁRIA UFPB, JOÃO PESSOA, BRASIL.

- [**SOUZA E.A. & SOUZA M.S.B. 2006. ERA UMA VEZ.... IN: FUNDAMENTOS, REFLEXÕES E EXPERIÊNCIAS EM EDUCAÇÃO AMBIENTAL. EDITORA UNIVERSITÁRIA UFPB, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Fundamentos_e_reflexoes_sobre_EA.pdf) *Capítulo*

- ANTAS P.T.Z. 2006. **PENELOPE OCHROGASTER**. IN: CONSERVING CRACIDS, BIOLOGY AND CONSERVATION OF THE MOST ENDANGERED FAMILY OF BIRDS IN THE NEW WORLD. MISCELLANEOUS PUBLICATIONS OF THE HOUSTON MUSEUM OF NATURAL SCIENCE 1, HOUSTON, USA.

- [**ROOS A.L. & ANTAS P.T.Z. 2006. WHITE-BROWED GUAN (PENELOPE JACUCACA). IN: CONSERVING CRACIDS: THE MOST THREATENED FAMILY OF BIRDS IN THE AMERICAS. MISCELLANEOUS PUBLICATIONS OF THE HOUSTON MUSEUM OF NATURAL SCIENCE 6, HOUSTON, USA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Roos_e_Antas_2006_White-browed_guan.pdf) *Resumo*

- [**EFE M.A. ET AL. 2005. ANÁLISE DAS FICHAS INDIVIDUAIS DE CONTROLE NO PROCESSO DE CAÇA DE ANATÍDEOS NO RIO GRANDE DO SUL. ORNITHOLOGIA 1(1):7-12**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_etal_AnaliseFichasCacaRS_2005.pdf) *Artigo completo*

- [**SERRANO I.L. & AZEVEDO JR S.M. 2005. DIETAS DAS AVES MARINHAS NO PARQUE NACIONAL DOS ABROLHOS, BAHIA, BRASIL. ORNITHOLOGIA 1(1):75-92**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_AzevedoJr_DietaAvesAbrolhos_2005.pdf) *Artigo completo*

- [**SERRANO I.L. ET AL. 2005. DIAGNOSTICO DA SITUAÇÃO NACIONAL DE COLISÕES DE AVES COM AERONAVES. ORNITHOLOGIA 1(1):93-104**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_ColisoesAeronaves_2005.pdf) *Artigo completo*

- [**SCHERER A. ET AL. 2005. ESTRUTURA TRÓFICA DA AVIFAUNA EM OITO PARQUES DA CIDADE DE PORTO ALEGRE, RIO GRANDE DO SUL, BRASIL. ORNITHOLOGIA 1(1):25-32**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Scherer_etal_AvifaunaParquesPOA_2005.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 2005. AVALIAÇÃO RÁPIDA DAS POTENCIALIDADES ECOLÓGICAS E ECONÔMICAS DO PARQUE NACIONAL DE UBAJARA, CEARÁ, USANDO AVES COMO INDICADORES. ORNITHOLOGIA 1(1):33-42 (ERRATA DISPONÍVEL)**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_PotencialidadesUbajara_2005_comErrata.pdf) *Artigo completo*

- [**LYRA-NEVES R.M. ET AL. 2005. INTERACOES ENTRE PHTHIRAPTERA (INSECTA) E AVES (EMBERIZIDAE) DE MATA ATLÂNTICA, PERNAMBUCO, BRASIL. ORNITHOLOGIA 1(1):43-47**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lyra-Neves_etal_InteracoesInsectaEmberizidae_2005.pdf) *Artigo completo*

- [**TELINO JR W.R. ET AL. 2005. BIOLOGIA E COMPOSIÇÃO DA AVIFAUNA EM UMA RESERVA PARTICULAR DE PATRIMÔNIO NATURAL DA CAATINGA PARAIBANA. ORNITHOLOGIA 1(1):49-57**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/TelinoJr_etal_AvesRPPN_2005.pdf) *Artigo completo*

- [**AMARAL A.C.A. ET AL. 2005. DINÂMICA DE NINHO DE ARARA-AZUL-DE-LEAR (ANDORHYNCHUS LEARI BONAPARTE, 1856) EM JEREMOABO, BAHIA. ORNITHOLOGIA 1(1):59-64**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Amaral_etal_NinhoLeari_2005.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 2005. CENSOS, ANILHAMENTOS E RECUPERAÇÕES DE DUAS MARRECAS NO RIO GRANDE DO SUL. ORNITHOLOGIA 1(1):65-74**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_MarrecasRS_2005.pdf) *Artigo completo*

- [**EFE M.A. ET AL. 2005. SUCESSO REPRODUTIVO DE THALASSEUS SANDVICENSIS EURYGNATHUS NO BRASIL. BIOCIÊNCIAS 13(1):63-68**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_etal_Tsandvicencis_2005.pdf) *Artigo completo*

- [**BAKER A.J. ET AL. 2005. ASSESSMENT OF THE WINTERING AREA OF RED KNOTS IN MARANHÃO NORTHERN BRAZIL IN FEBRUARY 2005. WADER STUDY GROUP BULLETIN 107:10-18**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Assessment_RedKnots_2005.pdf) *Artigo completo*

- [**NUNES M.F.C. ET AL. 2005. PLANO EMERGENCIAL PARA CONTROLE DO PERIGO AVIÁRIO NO ARQUIPÉLAGO DE FERNANDO DE NORONHA: MONITORAMENTO DE GARÇAS-VAQUEIRAS BULBUCUS IBIS (AVES: ARDEIDAE). XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_102.pdf) *Resumo*

- [**ROOS A.L. ET AL. 2005. AVES DO PARQUE NACIONAL DO CABO ORANGE, AP: RESULTADOS DA PRIMEIRA EXPEDIÇÃO CIENTÍFICA. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_103.pdf) *Resumo*

- [**SOUZA E.A. ET AL. 2005. AVES DA FLORESTA NACIONAL DA RESTINGA DE CABEDELO/PB. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_104.pdf) *Resumo*

- [**EFE M.A. ET AL. 2005. PROGRAMA INTERNACIONAL DE ANILHAMENTO E CONSERVAÇÃO DE TRINTA-RÉIS NO CONE-SUL. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_112.pdf) *Resumo*

- [**LACERDA R.C.A. ET AL. 2005. MONITORAMENTO DE AVES COM POTENCIAL CINEGÉTICO NO RIO GRANDE DO SUL: RESULTADOS DAS EXPEDIÇÕES 2004-2005. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_153.pdf) *Resumo*

- [**SOUZA E.A. 2005. PRESAS E PREDADORES EM COLÔNIAS DE ARRIBAÇÃS ZENAIDA AURICULATA (AVES, COLUMBIDAE) NO SEMI-ÁRIDO NORDESTINO. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_157.pdf) *Resumo*

- [**SANTOS-NETO J.R. ET AL. 2005. DESLOCAMENTO SAZONAL DAS ARARAS-AZUIS-DE-LEAR ANODORHYNCHUS LEARI (BONAPARTE, 1856) PSITTACIDAE. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_166.pdf) *Resumo*

- [**AMARAL A.C.A. ET AL. 2005. NOTA SOBRE A SITUAÇÃO ATUAL DA POPULAÇÃO DE ARARAS-AZUIS-DE-LEAR ANODORHYNCHUS LEARI EM UAUÁ, SENTO SÉ E CAMPO FORMOSO/BA. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_212.pdf) *Resumo*

- [**SANTOS-NETO J.R. ET AL. 2005. ESTIMATIVA DO SUCESSO REPRODUTIVO DAS ARARAS-AZUIS-DE-LEAR ANODORHYNCHUS LEARI (BONAPARTE, 1856) PSITTACIDAE, NA ESTAÇÃO REPRODUTIVA 2004/2005. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_41.pdf) *Resumo*

- [**EFE M.A. ET AL. 2005. AVALIAÇÃO DO STATUS DE CONSERVAÇÃO DO TRINTA-RÉIS-DE-BICO-AMARELO, THALASSEUS SANDVICENCIS NO BRASIL. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_XIIICBO_2005_47.pdf) *Resumo*

- [**SANTOS-NETO J.R. 2005. ATAQUE DE ARARAS-AZUIS-DE-LEAR, ANODORHYNCHUS LEARI (BONAPARTE, 1856) PSITTACIDAE, A MILHARAIS. XIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Santos_Neto_Resumo_XIIICBO.pdf) *Resumo*

- [**PIERSMA T. ET AL. 2005. FUEL STORAGE RATES BEFORE NORTHWARD FLIGTHS IN RED KNOTS WORLDWIDE - FACING THES EVEREST ECOLOGICAL CONSTRAINT IN TROPICAL INTERTIDAL ENVIRONMENTS? IN: BIRDS OF TWO WORLDS. JOHNS HOPKINS UNIVERSITY PRESS, BALTIMORE, USA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Piersma_etal_capitulo.pdf) *Capítulo*

- [**EFE M.A. ET AL. 2004. VARIAÇÕES MORFOLÓGICAS E PADRÕES DE CRESCIMENTO DE FILHOTES DE STERNA SANDVICENSIS EURYGNATHA NO BRASIL. BIOCIÊNCIAS 12(1):11-19**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_etal_Biociencias_2004.pdf) *Artigo completo*

- [**LYRA-NEVES R.M. ET AL. 2004. MONITORAMENTO DO MAÇARICO-BRANCO, CALIDRIS ALBA (PALLAS) (AVES, SCOLOPACIDAE), ATRAVÉS DE RECUPERAÇÕES DE ANILHAS COLORIDAS, NA COROA DO AVIAO, IGARASSU, PERNAMBUCO, BRASIL. REVISTA BRASILEIRA DE ZOOLOGIA 21(2):319-324**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lyra-Neves_etal_RBZ_2004.pdf) *Artigo completo*

- [**LYRA-NEVES R.M. ET AL. 2004. PRIMEIRO REGISTRO DE MYIARCHUS TUBERCULIFER (LAFRESNAYE & D'ORBIGNY) (AVES, TYRANNIDAE) PARA O ESTADO DE PERNAMBUCO, BRASIL. REVISTA BRASILEIRA DE ZOOLOGIA 21(2):405-407**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lyra-Neves_etal_nota_RBZ_2004.pdf) *Nota*

- [**LYRA-NEVES R.M. ET AL. 2004. COMUNIDADE DE AVES DA RESERVA ESTADUAL DE GURJAÚ, PERNAMBUCO, BRASIL. REVISTA BRASILEIRA DE ZOOLOGIA 21(3):581-592**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lyra-Neves_etal_RBZ_2004b.pdf) *Artigo completo*

- [**BAKER A.J. ET AL. 2004. RAPID POPULATION DECLINE IN RED KNOTS: FITNESS CONSEQUENCES OF DECREASED REFUELLING RATES AND LATE ARRIVAL IN DELAWARE BAY. PROCEEDINGS OF THE ROYAL SOCIETY: BIOLOGICAL SCIENCES 271:875-882**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Baker_etal_2004.pdf) *Artigo completo*

- [**RODRIGUES R.C. ET AL. 2004. AVES DO MACIÇO DO BATURITÉ, CEARÁ. IBAMA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/aves_maci%C3%A7o_baturite.pdf) *Guia*

- [**COELHO E.P. ET AL. 2004. O ATOBÁ-MARROM (SULA LEUCOGASTER) NA ILHA DE CABO FRIO, ARRAIAL DO CABO, RIO DE JANEIRO, BRASIL. AVES MARINHAS E INSULARES BRASILEIRAS: BIOECOLOGIA E CONSERVAÇÃO, EDITORA DA UNIVALI, ITAJAÍ, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Coelho_etal_OAtobaMarrom_2004.pdf) *Capítulo*

- [**EFE M.A. 2004. AVES MARINHAS DAS ILHAS DO ESPÌRITO SANTO. IN: AVES MARINHAS E INSULARES BRASILEIRAS: BIOECOLOGIA E CONSERVAÇÃO. EDITORA DA UNIVALI, ITAJAÌ, SC.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_M_Capitulo_5.pdf) *Capítulo*

- [**EFE M.A. 2004. PESQUISA E CONSERVAÇÃO DO TRINTA-RÉIS-DE-BICO-AMARELO (MESA REDONDA AVES MARINHAS: SITUAÇÃO ATUAL E PERSPECTIVAS NO BRASIL). XII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BLUMENAU, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Efe_MesaRedonda_2004.pdf) *Mesa Redonda*

- [**AMARAL A.C.A. ET AL. 2004. DINÂMICA DE NINHO DE ARARA-AZUL-DE-LEAR (ANDORHYNCHUS LEARI BONAPARTE, 1856) EM SERRA BRANCA, JEREMOABO, BAHIA. XII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BLUMENAU, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2004_-_dinamica_de_ninho_-_arara-lear.pdf) *Resumo*

- [**AMARAL A.C.A. ET AL. 2004. MORFOMETRIA DE DUAS POPULAÇÕES DISTINTAS DE CORAGYPS ATRATUS NO NORDESTE DO BRASIL. XII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BLUMENAU, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2004_-_Morfometria_de_urubus.pdf) *Resumo*

- [**AMARAL A.C.A. ET AL. 2004. OBSERVAÇÕES COMPORTAMENTAIS DE ARARA-AZUL-DE-LEAR, ANODORHYNCHUS LEARI (BONAPARTE, 1856), EM CATIVEIRO. XII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BLUMENAU, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2004_-_Observacoes_de_arara-lear.pdf) *Resumo*

- [**ROOS A.L. 2004. AVIFAUNA FLORESTAL DE SANTA CATARINA: ESTADO DO CONHECIMENTO (MESA REDONDA). XII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BLUMENAU, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Roos_XIICongressoMR_2004.pdf) *Mesa Redonda*

- [**ROOS A.L. ET AL. 2004. BIBLIOGRAFIA ORNITOLÓGICA CATARINENSE. XII CONGRESSO BRASILEIRO DE ORNITOLOGIA, BLUMENAU, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Roos_etal_Biblio_Resumo.pdf) *Resumo*

- SOUZA E.A. & PAGNOCCHESCHI B. 2003. **GESTÃO DE RECURSOS HÍDRICOS NOS ESTADOS (PARAÍBA)**. IN: POLITICAS AMBIENTAIS NO BRASIL: ANÁLISES, INSTRUMENTOS E EXPERIÊNCIAS. INSTITUTO INTERNACIONAL DE EDUCAÇÃO DO BRASIL, BRASÍLIA, BRASIL.

- [**SOTO J.M.R. & FILIPPINI A. 2003. OCORRÊNCIA E REPRODUÇÃO DA PARDELA-DE-AUDUBON, PUFFINUS LHERMINIERI LESSON, 1839 (PROCELLARIFORMES, PROCELLARIIDAE), NO ARQUIPÉLAGO FERNANDO DE NORONHA, COM A REVISÃO DOS REGISTROS DE P. LHERMINIERI E P. ASSIMILIS NO BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 11(2):112-115**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SotoFilippini_comErrata.pdf) *Artigo completo*

- [**SOTO J.M.R. & FILIPPINI A. 2003. DOCUMENTAÇÃO DA OCORRÊNCIA DA PERDIZ-DO-MAR, GLAREOLA PRATINCOLA (LINNAEUS, 1766) (CHARADRIIFORMES: GLAREOLIDAE), NO BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 11(1):131-145**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_ararajuba_11-1-2003.pdf) *Artigo completo*

- [**SOTO J.M.R. ET AL. 2003. ANÁLISE DAS CAPTURAS DE ALBATROZES E PETRÉIS (PROCELLARIIFORMES) NO ESPINHEL PELÁGICO OPERANTE NA COSTA SUL DO BRASIL E AO LARGO, UTILIZANDO MEDIDAS MITIGADORAS. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_analise_captura_de_albatroz.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2003. ÁREAS DE CONCENTRAÇÃO, DESLOCAMENTO E LONGEVIDADE DE DUAS ESPÉCIES DE MARRECAS (ANSERIFORMES: ANATIDAE) NO RIO GRANDE DO SUL. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_area_de_concentracao_de_marrecas.pdf) *Resumo*

- [**AMARAL A.C.A. & NASCIMENTO I.L.S. 2003. AVIFAUNA DE HÁBITO DIURNO DO AEROPORTO PRESIDENTE CASTRO PINTO/PB. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_avifauna_habito_aeroporto_jpa.pdf) *Resumo*

- [**OLIVEIRA A.C. ET AL. 2003. COMPOSIÇÃO DA AVIFAUNA DO PARQUE NACIONAL DA CHAPADA DOS VEADEIROS, GOIÁS. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_avifauna_parna_veadeiros.pdf) *Resumo*

- [**NASCIMENTO I.L.S. ET AL. 2003. AVIFAUNA DA REGIÃO DO PASSO DO LONTRA, CORUMBÁ, MATO GROSSO DO SUL. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_avifauna_passo_lontra_MT.pdf) *Resumo*

- [**NASCIMENTO I.L.S. ET AL. 2003. DIAGNÓSTICO DA SITUAÇÃO NACIONAL DE COLISÃO DE AVES COM AERONAVES. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_colisoes_aves_x_aeronaves.pdf) *Resumo*

- [**SOTO J.M.R. ET AL. 2003. SUBSÍDIOS PARA UM MAIOR CONHECIMENTO SOBRE O MERGULHÃO-GRANDE PODICEPS MAJOR (BODDAERT, 1783) (PODICIPEDIFORMES, PODICIPEDIDAE), NO SUL DO BRASIL. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_conhecimento_sobre_mergulhao.pdf) *Resumo*

- [**BOTELHO M.C.N. ET AL. 2003. ECTOPARASITOS EM PIPRA FASCIICAUDA HELLMAYR, 1906 (PIPRIDAE), NA ÁREA DE PROTEÇÃO AMBIENTAL DO MACIÇO DO BATURITÉ, CE. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_ectoparasita_em_Pipra_-_baturite.pdf) *Resumo*

- [**RODRIGUES R.C. ET AL. 2003. INVENTÁRIO DA AVIFAUNA NA ÁREA DE PROTEÇÃO AMBIENTAL DO MACIÇO DO BATURITÉ, CE. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_inventario_baturite.pdf) *Resumo*

- [**EFE M.A. ET AL. 2003. INVENTARIAMENTO E DISTRIBUIÇÃO DA AVIFAUNA DA ESTAÇÃO ECOLÓGICA DE CARIJÓS - SC. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_inventario_carijos.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2003. MONITORAMENTO DA MARRECA-PARDA, ANAS GEORGICA NO RIO GRANDE DO SUL. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_monitoramento_da_marreca_parda.pdf) *Resumo*

- [**NASCIMENTO I.L.S. ET AL. 2003. MUDA E PARÂMETROS BIOMÉTRICOS DE AVES MIGRATÓRIAS NO NORTE DO BRASIL. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_muda_e_biometria_aves_migratorias.pdf) *Resumo*

- [**SOTO J.M.R. ET AL. 2003. EVIDÊNCIAS DE PREDAÇÃO DE TUBARÃO DALATÍDEO EM ATOBÁ-MARROM, SULA LEUCOGASTER (BODDAERT, 1783) (PELECANIFORMES, SULIDAE), NA COSTA CENTRO-NORTE DE SANTA CATARINA, BRASIL. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_predacao_de_tubarao_em_atoba.pdf) *Resumo*

- [**FILIPPINI A. ET AL. 2003. RELAÇÃO DOS RESTOS ALIMENTARES DO GAIVOTÃO LARUS DOMINICANUS LICHTENSTEIN, 1823 (CHARADRIIFORMES, LARIDAE), ENCONTRADOS NOS SÍTIOS REPRODUTIVOS DAS ILHAS COSTEIRAS DE SANTA CATARINA. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_restos_alimentares_do_gaivotao.pdf) *Resumo*

- [**SOTO J.M.R. ET AL. 2003. REVISÃO DOS REGISTROS DE PETRÉIS-GIGANTES, MACRONECTES SPP. (PROCELLARIIFORMES, PROCELLARIIDAE), NO BRASIL, COM A INCLUSÃO DE M. GIGANTEUS SOLANDERI. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_revisao_de_registros_de_petreis.pdf) *Resumo*

- [**NASCIMENTO I.L.S. ET AL. 2003. TRANSLOCAÇÃO DE URUBUS-DE-CABEÇA-PRETA (CORAGYPS ATRATUS) NO AEROPORTO INTERNACIONAL AUGUSTO SEVERO, RIO GRANDE DO NORTE. XI CONGRESSO BRASILEIRO DE ONITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003_-_translocacao_urubu.pdf) *Resumo*

- [**FILIPPINI A. ET AL. 2003. UMA NOVA PROPOSTA DE CLASSIFICAÇÃO DA COMPOSIÇÃO DA AVIFAUNA DO ARQUIPÉLAGO FERNANDO DE NORONHA. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2003-_classificacao_avifauna_noronha.pdf) *Resumo*

- [**MENEZES A.C. ET AL. 2003. RESGATE E REINTEGRAÇÃO DE FILHOTES DE ANODORHYNCHUS LEARI NA NATUREZA. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Menezes_Resgate_Leari.pdf) *Resumo*

- [**MOHR L.V. & EFE M.A. 2003. LISTA COMENTADA DA AVIFAUNA DO MUNÍCIPIO DE PORTO ALEGRE, RIO GRANDE DO SUL. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mohr_e_Efe_Resumo_Avifauna_POA.pdf) *Resumo*

- [**MOHR L.V. & EFE M.A. 2003. REGISTRO DE VARIEGAÇÃO EM JOÃO-DE-BARRO FURNARIUS RUFUS EM CANOAS, REGIÃO METROPOLITANA DE PORTO ALEGRE, RS. XI CONGRESSO BRASILEIRO DE ORNITOLOGIA, FEIRA DE SANTANA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Mohr_e_Efe_Resumo_Variegacao.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2003. DADOS BIOLÓGICOS DE MARRECAS (AVES, ANATIDAE) NO RIO GRANDE DO SUL - ALGUNS RESULTADOS DO PROJETO CONSERVAÇÃO DE ANATÍDEOS NO CONE SUL-AMERICANO. 5O ENCONTRO NACIONAL DE BIÓLOGOS E 2O ENCONTRO NORDESTINO DE BIÓLOGOS, NATAL, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_enb_2003-joao_e_jussara.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 2003. TABELA DE VIDA DA MARRECA-CANELEIRA, DENDROCYGNA BICOLOR, COM BASE EM DADOS DE ANILHAMENTO. 5O ENCONTRO NACIONAL DE BIÓLOGOS E 2O ENCONTRO NORDESTINO DE BIÓLOGOS, NATAL, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_enb_2003_16_12_1-joao.pdf) *Resumo*

- [**BUGONI L. ET AL. 2002. BIOMETRY, MOLT AND BROOD PATCH PARAMETERS OF BIRDS IN SOUTHERN BRAZIL. REVISTA BRASILEIRA DE ORNITOLOGIA 10(1):85-94**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Bugoni_etal_2002.pdf) *Artigo completo*

- [**ANTAS P.T.Z. 2002. NOTAS SOBRE PENELOPE OCHROGASTER NA RESERVA PARTICULAR DO PATRIMÔNIO NATURAL DO SESC-PANTANAL, BRASIL. BOLETIM DO IUCN/BIRDLIFE/WPA GRUPO DE ESPECIALISTAS EM CRACÍDEOS 14:4-6**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/BWPA_Antas_2002.pdf) *Nota*

- [**FILIPPINI A. 2002. COMENTÁRIOS SOBRE OS MOVIMENTOS REALIZADOS PELAS AVES MARINHAS DO ARQUIPÉLAGO DE FERNANDO DE NORONHA E DOS ROCHEDOS E SÃO PEDRO E SÃO PAULO EM FUNÇÃO DAS RECUPERAÇÕES DE AVES ANILHADAS. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r10_-_filippini.pdf) *Resumo*

- [**OLIVEIRA A.C. ET AL. 2002. ANÁLISE DOS DADOS DE RECUPERAÇÃO DO GÊNERO SULA (PELICANIFORMES, SULIDAE) OCORRIDAS NO BRASIL ENTRE 1981 E 2000. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r111_-_ailton.pdf) *Resumo*

- [**SOUZA E.A. & AMARAL A.C.A. 2002. OCORRÊNCIAS DE COLÔNIAS REPRODUTIVAS (POMBAIS) DE ZENAIDA AURICULATA NO NORDESTE DO BRASIL. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r43_-_elivan.pdf) *Resumo*

- [**SOUZA E.A. ET AL. 2002. NOVOS REGISTROS PARA A AVIFAUNA DA ESTAÇÃO ECOLÓGICA DE AIUABA, CEARÁ. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r44_-_elivan.pdf) *Resumo*

- [**FLORES J.M. ET AL. 2002. RESULTADOS DO SEGUNDO ANO DE ESTUDOS SOBRE OS IMPACTOS DECORRENTES DA IMPLANTAÇÃO DA USINA HIDRELÉTRICA SÉRGIO MOTTA - SP SOBRE AS AVES DA REGIÃO. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r71_-_jussara.pdf) *Resumo*

- [**MOHR L.V. & EFE M.A. 2002. LISTA COMENTADA DA AVIFAUNA DO MUNICÍPIO DE PORTO ALEGRE, RIO GRANDE DO SUL. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r77_-_leonardo.pdf) *Resumo*

- [**MOHR L.V. 2002. PRIMEIRO REGISTRO DOCUMENTADO DA GARÇA-AZUL EGRETTA CAERULEA NO RIO GRANDE DO SUL. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r78_-_leonardo.pdf) *Resumo*

- [**MOHR L.V. & EFE M.A. 2002. REGISTRO DE VARIEGAÇÃO EM JOÃO-DE-BARRO FURNARIUS RUFUS EM CANOAS, REGIÃO METROPOLITANA DE PORTO ALEGRE, RS. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r79-leonardo.pdf) *Resumo*

- [**EFE M.A. ET AL. 2002. ANÁLISE DAS FICHAS INDIVIDUAIS DE CONTROLE NO PROCESSO DE CAÇA DE ANATÍDEOS NO RIO GRANDE DO SUL. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r95_-_marcio.pdf) *Resumo*

- [**EFE M.A. & FILIPPINI A. 2002. IMPACTO DO NINHO DE FURNARIUS RUFUS EM ÁREAS RURAIS DE SANTA CATARINA. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r96_-_marcio.pdf) *Resumo*

- [**EFE M.A. ET AL. 2002. REAVISTAGEM DE FLAMINGOS NO LITORAL DE SANTA CATARINA. X CONGRESSO BRASILEIRO DE ORNITOLOGIA, FORTALEZA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2002-r97_-_marcio.pdf) *Resumo*

- BARBIERI E. ET AL. 2002. **CAPTURAS ACIDENTAIS DE ALBATROZES E PETRÉIS, EFETUADAS PELO ESPINHEL PELÁGICO NO SUL DO BRASIL.** 1^O^ SIMPÓSIO BRASILEIRO DE OCEANOGRAFIA, SÃO PAULO, BRASIL.

- [**EFE M.A. ET AL. 2001. FIRST-KNOWN RECORD OF BREEDING FOR THE BLACK SKIMMER (RYNCHOPS NIGER) IN A MIXED COLONY IN IBICUI RIVER, RIO GRANDE DO SUL STATE, SOUTHERN BRAZIL. INTERNATIONAL JOURNAL OF ORNITHOLOGY 4(2):103-107**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/2001_First_Skimmer_Int_Jour_Ornit_4.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 2001. BIOLOGICAL ASPECTS OF THE BLACK-NECKED SWAN (CYGNUS MELANCORYPHUS) AND COSCOROBA SWAN IN RIO GRANDE DO SUL STATE. MELOPSITTACUS 4(1):31-38**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_melopsittacus_v4_n1_2001.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 2001. CENSOS DE ARARAS-AZUIS-DE-LEAR (ANODORHYNCHUS LEARI) NA NATUREZA. TANGARA 1(3):135-138**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Tangara_v1n3_135-138_2001.pdf) *Artigo completo*

- [**MOHR L.V. 2001. REGISTROS DE VARIEGAÇÃO EM MARRECA-PIADEIRA, DENDROCYGNA VIDUATA, COLETADA EM SANTA VITÓRIA DO PALMAR, RIO GRANDE DO SUL. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r132-leonardo.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 2001. MONITORAMENTO DE COLÔNIAS DE AVOANTE, ZENAIDA AURICULATA, NO NORDESTE DO BRASIL, ENTRE 1991 E 1999. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r139-joao_luiz.pdf) *Resumo*

- [**NASCIMENTO I.L.S. & AZEVEDO JR S.M. 2001. DIETA DAS AVES MARINHAS NO PARQUE NACIONAL DOS ABROLHOS, BAHIA. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r140-ines.pdf) *Resumo*

- [**NASCIMENTO J.L.X. & FLORES J.M. 2001. LEVANTAMENTO AVIFAUNÍSTICO DO PARQUE NACIONAL DO ARAGUAIA, TOCANTINS. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r141-joao_luiz.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2001. ESTUDO DOS IMPACTOS DECORRENTES DA IMPLANTAÇÃO DA USINA HIDRELÉTRICA DE PORTO PRIMAVERA (SÉRGIO MOTTA) SOBRE A AVIFAUNA DA REGIÃO. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r142-joao_luiz.pdf) *Resumo*

- [**OLIVEIRA A.C. ET AL. 2001. AVIFAUNA DA ÁREA DE PROTEÇÃO AMBIENTAL DE IBIRAPUITÃ, RIO GRANDE DO SUL. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r146-ailton.pdf) *Resumo*

- [**SALES JR L.G. & NASCIMENTO J.L.X. 2001. AVALIAÇÃO RÁPIDA DAS POTENCIALIDADES ECOLÓGICAS E ECONÔMICAS DAS AVES DO PARQUE NACIONAL DE UBAJARA, CEARÁ, E ASPECTOS DE SUA BIOLOGIA. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r183-joao_luiz.pdf) *Resumo*

- [**SOTO J.M.R. & FILIPPINI A. 2001. A NECESSIDADE DE IMPLANTAÇÃO DE UMA ÁREA DE PROTEÇÃO, DIRECIONADA À AVES LIMNÍCOLAS, NA DESEMBOCADURA DO RIO ARARANGUÁ, ESTADO DE SANTA CATARINA, BRASIL. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r205-filippini.pdf) *Resumo*

- [**EFE M.A. ET AL. 2001. PARÂMETROS POPULACIONAIS DE STERNA SANDVICENSIS EURYGNATHA NO BRASIL. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r62-marcio.pdf) *Resumo*

- [**EFE M.A. ET AL. 2001. VARIAÇÕES MORFOLÓGICAS E PADRÕES DE CRESCIMENTO EM STERNA SANDVICENSIS EURYGNATHA NO BRASIL. IX CONGRESSO BRASILEIRO DE ORNITOLOGIA, CURITIBA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/cbo_2001-r63-marcio.pdf) *Resumo*

- [**EFE M.A. ET AL. 2001. INVENTÁRIO E DISTRIBUIÇÃO DA AVIFAUNA DO PARQUE SAINT HILAIRE, VIAMÃO, RIO GRANDE DO SUL, BRASIL. TANGARA 1(1):12-25**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Inventario_e_distribuicao_da_avifauna_SaintHilaire.pdf) *Artigo completo*

- [**NASCIMENTO I.L.S. 2001. MIGRATION AND OTHER BIOLOGICAL DATA OF CALIDRIS CANUTUS RUFA FROM BRAZIL. WADER STUDY GROUP BULLETIM (ABSTRACT) 95:11**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_WSG_abstract_2001.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2000. MIGRAÇÃO E DADOS DEMOGRÁFICOS DO MARRECÃO NETTA PEPOSACA (ANSERIFORMES, ANATIDAE) NO SUL DO BRASIL, URUGUAI, PARAGUAI E NORTE DA ARGENTINA. MELOPSITTACUS 3(4):143-158**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Artigo_-_Melopsittacus_v3n4_-_JoaoLuiz_-_2000.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 2000. AVES DA CHAPADA DO ARARIPE (BRASIL): BIOLOGIA E CONSERVAÇÃO. REVISTA BRASILEIRA DE ORNITOLOGIA 8(2):115-125**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_Aves_Araripe.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 2000. AVES AQUÁTICAS DA REGIÃO DO LAGO DE SOBRADINHO, BAHIA - CONSERVAÇÃO E POTENCIAL DE MANEJO. MELOPSITTACUS 3(2):53-63**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Artigo_Melopsittacus_v3n2_-_Joao_luiz_2000.pdf) *Artigo completo*

- [**AZEVEDO JR S.M. ET AL. 2000. NOVOS REGISTROS DE ANTILOPHIA BOKERMANNI COELHO E SILVA, 1999 NA CHAPADA DO ARARIPE, CEARÁ, BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 8(2):133-134**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_ararajuba-8_p133-134_12_2000.pdf) *Nota*

- [**NASCIMENTO J.L.X. 2000. ESTUDO COMPARATIVO DA AVIFAUNA EM DUAS ESTAÇÕES ECOLÓGICAS DA CAATINGA: AIUABA E SERIDÓ. MELOPSITTACUS 3(1):12-35**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_melopsittacus_v3_n1_-_Jo%C3%A3o_Luiz_2000.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. & LARRAZÁBAL M.E.L. 2000. ALIMENTAÇÃO DE AVES LIMÍCOLAS EM BARRA DE CUNHAÚ, CANGUARETAMA, RIO GRANDE DO NORTE. MELOPSITTACUS 3(3):91-109**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_melopsittacus_v3_n3_Joao_Luiz_2000.pdf) *Artigo completo*

- [**EFE M.A. ET AL. 2000. DISTRIBUIÇÃO E ECOLOGIA REPRODUTIVA DE STERNA SANDVICENSIS EURYGNATHA NO BRASIL. MELOPSITTACUS 3(3):110-121**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_melopsittacus_v3_n3_Marcio_Efe_2000.pdf) *Artigo completo*

- [**ALVES V.S. ET AL. 2000. AS AVES DO ARQUIPÉLAGO DE ABROLHOS (BAHIA - BRASIL). EDIÇÕES IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Aves_do_Arquipelago_de_Abrolhos.pdf) *Guia*

- [**NASCIMENTO I.L.S. 2000. DIETA DAS AVES MARINHAS COMO CONTRIBUIÇÃO AO MANEJO DO PARQUE NACIONAL DOS ABROLHOS, BA, BRASIL. DISSERTAÇÃO DE MESTRADO. UFPE, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Dissertacao_de_mestrado_-_ines_serrano.pdf) *Dissertação de mestrado*

- [**SOUZA E.A. 2000. MATA DA AMEM, CABEDELO-PB: POSSIBILIDADES DE CO-GESTÃO. DISSERTAÇÃO DE MESTRADO. UFPB, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/dissertacao_mata_amem-Elivan.pdf) *Dissertação de mestrado*

- [**MOHR L.V. ET AL. 2000. NOVOS REGISTROS DE AVES PARA O RIO GRANDE DO SUL, EM PARQUES URBANOS DE PORTO ALEGRE E VIAMÃO. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_VIII_CBO_2000_R154.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 2000. ESTUDO COMPARATIVO DA AVIFAUNA EM DUAS ESTAÇÕES ECOLÓGICAS DA CAATINGA: AIUABA (CEARÁ) E SERIDÓ (RIO GRANDE DO NORTE). VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_VIII_CBO_2000_R17.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2000. MIGRAÇÃO E PARÂMETROS DEMOGRÁFICOS DO MARRECÃO NETTA PEPOSACA (ANATIDAE, ANSERIFORMES) NO SUL DO BRASIL, URUGUAI, PARAGUAI E NORTE DA ARGENTINA. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_VIII_CBO_2000_R227.pdf) *Resumo*

- [**EFE M.A. ET AL. 2000. REGISTRO DE REPRODUÇÃO DE TALHA-MAR (RYNCHOPS NIGER) EM COLÔNIA MISTA COM OUTRAS TRÊS ESPÉCIES EM ILHA DO RIO IBICUÍ, RIO GRANDE DO SUL. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_VIII_CBO_2000_R66.pdf) *Resumo*

- [**EFE M.A. ET AL. 2000. INVENTÁRIO E DISTRIBUIÇÃO DA AVIFAUNA DO PARQUE SAINT HILAIRE, VIAMAO, RIO GRANDE DO SUL. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_VIII_CBO_2000_R67.pdf) *Resumo*

- [**EFE M.A. ET AL. 2000. PROJETO AVES URBANAS: AS AVES DOS PARQUES DE PORTO ALEGRE, RIO GRANDE DO SUL. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_VIII_CBO_2000_R68.pdf) *Resumo*

- [**NASCIMENTO J.L.X. & LARRAZÁBAL M.E.L. 2000. ESTUDO DE ALIMENTAÇÃO DE AVES LIMÍCOLAS EM BARRA DE CUNHAÚ, CANGUARETAMA, RIO GRANDE DO NORTE. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_VIII_CBO_2000_R78.pdf) *Resumo*

- [**SOTO J.M.R. & FILIPPINI A. 2000. O GÊNERO PUFFINUS NO ARQUIPÉLAGO FERNANDO DE NORONHA E O COMPLEXO P. ASSIMILIS - P. LHERMINIERI. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SotoFilippini_VIIICBO.pdf) *Resumo*

- [**SOTO J.M.R. ET AL. 2000. LISTA SISTEMÁTICA DAS AVES REGISTRADAS NO ARQUIPÉLAGO FERNANDO DE NORONHA, COM NOVAS INCLUSÕES. VIII CONGRESSO BRASILEIRO DE ORNITOLOGIA, FLORIANÓPOLIS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Soto_etal_VIIICBO.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 2000. BIOMETRIA, MUDA E REPRODUÇÃO DA MARRECA-PARDA ANAS GEORGICA GMELIN, 1789 (ANSERIFORMES, ANATIDAE) NO RIO GRANDE DO SUL. A ORNITOLOGIA NO BRASIL: PESQUISA ATUAL E PERSPECTIVAS. EDUERJ, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_Biometria_2000.pdf) *Capítulo*

**1999 - 1990**

- [**ANTAS P.T.Z. 1999. COMUNIDADE DE AVES DOS CERRADOS DO PLANALTO CENTRAL E PORÇÃO OCIDENTAL DO MÉDIO RIO SÃO FRANCISCO. TESE DE DOUTORADO, UNB, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_Tese.pdf) *Tese*

- [**BAKER A.J. ET AL. 1999. NORTHBOUND MIGRATION OF RED KNOTS CALIDRIS CANUTUS RUFA IN ARGENTINA AND BRAZIL: REPORT ON RESULTS OBTAINED BY NA INTERNATIONAL EXPEDITION IN MARCH-APRIL 1997. WADER STUDY GROUP BULLETIN 88:64-75**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Baker_etal_WSGB_99.pdf) *Artigo completo*

- [**LYRA-NEVES R.M. ET AL. 1999. AVES DA FAZENDA TAMANDUÁ, SANTA TEREZINHA - PARAÍBA. OS AUTORES, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/livro_aves_faz_tamandua.pdf) *Guia*

- [**NASCIMENTO J.L.X. 1999. REGISTROS DE NINHAIS DE GARÇAS (CICONIIFORMES, ARDEIDAE) NA PARAIBA, BRASIL. AIRO 10:39-42**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_1999.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 1999. AVES DA CHAPADA DO ARARIPE, BRASIL: BIOLOGIA E CONSERVAÇÃO. VIII CONGRESSO NORDESTINO DE ECOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_etal_Aves_Araripe_Resumo.pdf) *Resumo*

- [**NASCIMENTO I.L.S. ET AL. 1999. LAGOA DO PEIXE NATIONAL PARK, BRAZIL: ANALYSIS OF SHOREBIRD DATA, 1984-1997. VI CONGRESSO DE ORNITOLOGIA NEOTROPICAL, MONTERREY, MÉXICO.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_VI_CON_S153_1999.pdf) *Resumo*

- [**BAKER A. ET AL. 1999. HEMISPHERIC PROBLEMS IN THE CONSERVATION OF RED KNOTS (CALIDRIS CANUTUS RUFA). VI CONGRESSO DE ORNITOLOGIA NEOTROPICAL, MONTERREY, MEXICO.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Baker_etal_Hemispheric_Ploblems_CALIDRIS_CANUTUS_RUFA.pdf) *Resumo expandido*

- [**NASCIMENTO J.L.X. 1998. MUDA DE CHARADRIIDAE E SCOLOPACIDAE (CHARADRIIFORMES) NO NORTE DO BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 6(2):141-144**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_1998_RBO6_141_144.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. ET AL. 1998. BIOMETRIA, MUDA E REPRODUÇÃO DA MARRECA-PARDA ANAS GEORGICA (ANSERIFORMES, ANATIDAE) NO RIO GRANDE DO SUL. VII CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_VII_CBO_1998_144.pdf) *Resumo*

- [**FLORES J.M.& SCHERER S.B. 1998. CENSOS DE AVES MIGRATÓRIAS NEÁRTICAS NA REGIÃO COSTEIRA DO RIO GRANDE DO SUL. VII CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_VII_CBO_1998_149.pdf) *Resumo*

- [**SCHULZ-NETO A. 1998. NOVOS REGISTROS DE AVES PARA O NOVO MUNDO, PARA A AMÉRICA DO SUL, PARA O BRASIL E PARA FERNANDO DE NORONHA. VII CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_VII_CBO_1998_50.pdf) *Resumo*

- [**SCHULZ-NETO A. 1998. CENSOS DE AVES COSTEIRAS NA ÁREA DE PROTEÇÃO AMBIENTAL DAS REENTRÂNCIAS MARANHENSES. VII CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_VII_CBO_1998_51.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 1998. REGISTROS DE NINHAIS DE GARÇAS (ARDEIDAE) NA PARAIBA. VII CONGRESSO BRASILEIRO DE ORNITOLOGIA, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_VII_CBO_1998_94.pdf) *Resumo*

- [**NASCIMENTO I.L.S. 1998. IMPACTOS DO FOGO SOBRE A AVIFAUNA DO PARQUE NACIONAL DOS ABROLHOS, BAHIA, BRASIL. XXII CONGRESSO BRASILEIRO DE ZOOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_XXII_CBZ_R1177_1998.pdf) *Resumo*

- ALVES M.A.S. & ANTAS P.T.Z. 1998. **BIRD COMMUNITIES IN ATLANTIC FOREST FRAGMENTS IN THE SOUTH OF BAHIA STATE, BRAZIL**. 22^O^ CONGRESSO INTERNACIONAL DE ORNITOLOGIA, DURBAN, AFRICA DO SUL.

- [**NASCIMENTO I.L.S. ET AL. 1998. WATERBIRD COLONIES IN THE PANTANAL AREA WITH NA EMPHASIS ON THEIR TEMPORAL AND SPATIAL SCALES. MEETING OF THE COLONIAL WATERBIRD SOCIETY AND THE FLAMINGO SPECIALIST GROUP, FLORIDA INTERNATIONAL UNIVERSITY, MIAMI, USA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_1998_Waterbirds_colonies.pdf) *Resumo*

- [**NASCIMENTO I.L.S. & NASCIMENTO J.L.X. 1998. DATA BANK OF THE BIRDS COLONIES IN BRAZIL. MEETING OF THE COLONIAL WATERBIRD SOCIETY AND THE FLAMINGO SPECIALIST GROUP, FLORIDA INTERNACIONAL UNIVERSITY, MIAMI, USA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_Nascimento_Data_Bank_Bird_Colony.pdf) *Resumo*

- [**SCHULZ-NETO A. 1998. ASPECTOS BIOLOGICOS DA AVIFAUNA MARINHA NA RESERVA BIOLOGICA DO ATOL DAS ROCAS, RIO GRANDE DO NORTE, BRASIL. EL HORNERO 15(1):17-28**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SchulzNeto_ELHonero_V15N1.pdf) *Artigo completo*

- [**HAYS H. ET AL. 1997. RECOVERIES OF ROSEATE AND COMMON TERNS IN SOUTH AMERICA. JOURNAL OF FIELD ORNITHOLOGY 68(1):79-90**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Artigo_J_field_ornitolg_-_68-1-_joao_luiz_1997.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. 1997. MUDA DE CHARADRIUS SEMIPALMATUS E CALIDRIS PUSILLA (AVES, CHARADRIIFORMES) NA ILHA DO PARAZINHO, AMAPÁ. VII CONGRESSO LATINO-AMERICANO SOBRE CIÊNCIAS DO MAR, SANTOS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_VII_COLACMAR_1997.pdf) *Resumo expandido*

- [**RODRIGUES R.C. & NASCIMENTO J.L.X. 1997. OBSERVAÇÕES SOBRE A DIETA DE CORYPHOSPINGUS PILEATUS (AVES, EMBEREZIDAE) NO NORDESTE DO BRASIL. VI CONGRESSO BRASILEIRO DE ORNITOLOGIA, BELO HORIZONTE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rodrigues_Nascimento_resumo_Cpileatus1997.pdf) *Resumo*

- [**CORDEIRO P.H.C. ET AL. 1996. ANÁLISE DAS RECUPERAÇÕES DE STERNA HIRUNDO NO BRASIL ENTRE 1980 E 1994. REVISTA BRASILEIRA DE ORNITOLOGIA 4(1):3-7**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Cordeiro_etal_RecuperacoesSterna_1996.pdf) *Artigo completo*

- [**ANTAS P.T.Z. 1996. THE BRAZILIAN MERGANSER (MERGUS OCTOSETACEUS) THE MOST THREATENED DUCK IN SOUTH AMERICA. GIBIER FAUNE SAUVAGE GAME WILDLIFE 13:799-800**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_Mergus_1996.pdf) *Resumo*

- [**ANTAS P.T.Z. & NASCIMENTO I.L.S. 1996. ANALYSIS OF RED KNOT CALIDRIS CANUTUS RUFA BANDING DATA IN BRAZIL. INTERNATIONAL WADER STUDIES 8:63-70**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Antas_Nascimento_1996.pdf) *Artigo completo*

- [**ANTAS P.T.Z. ET AL. 1996. MONITORING ANATIDAE POPULATIONS IN RIO GRANDE DO SUL STATE, SOUTH BRAZIL. GIBIER FAUNE SAUVAGE GAME WILDLIFE 13(1):513-530**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Gibier_Antas_etal_1996.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. & SCHULZ-NETO A. 1996. AVES DA ESTAÇÃO ECOLÓGICA DE AIUABA, CEARÁ. EDIÇÕES IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AVES_Estacao_Ecologica_Aiuaba.pdf) *Guia*

- [**NASCIMENTO J.L.X. 1996. AVES DA FLORESTA NACIONAL DO ARARIPE, CEARÁ. EDIÇÕES IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/aves_flona_araripe.pdf) *Guia*

- [**KOCH M. ET AL. 1996. ASPECTOS ETOLÓGICOS E MORFOMÉTRICOS DO CISNE-DE-PESCOÇO-PRETO CYGNUS MELANCORYPHUS E DA CAPOROROCA COSCOROBA COSCOROBA NO RIO GRANDE DO SUL. V CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_V_CBO_1996_48.pdf) *Resumo*

- [**NASCIMENTO J.L.X. & SCHULZ-NETO A. 1996. AVES DA ESTAÇÃO ECOLÓGICA DE AIUABA, CE. V CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_V_CBO_1996_77.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 1996. AVES DA FLORESTA NACIONAL DO ARARIPE, CE. V CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_V_CBO_1996_78.pdf) *Resumo*

- [**ANTAS P.T.Z. & NASCIMENTO I.L.S. 1996. SOB OS CÉUS DO PANTANAL: BIOLOGIA E CONSERVAÇÃO DO TUIUIÚ JABIRU MYCTERIA. EMPRESA DAS ARTES, SÃO PAULO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Sob_os_ceus_do_Pantanal.pdf) *Livro*

- MARQUES E.J. ET AL. 1996. **PANTANAL - ASPECTOS RELACIONADOS ÀS AVES AQUÁTICAS E ÁREAS DE REPRODUÇÃO COLONIAL**. II SIMPÓSIO SOBRE RECURSOS NATURAIS E SÓCIO-ECONÔMICOS DO PANTANAL - MANEJO E CONSERVAÇÃO, EMBRAPA/CPAP, CORUMBÁ, BRASIL.

- [**NASCIMENTO J.L.X. & ANTAS P.T.Z. 1995. ANILHAMENTO DE DENDROCYGNA SPP. NO BRASIL ENTRE 1973 E 1994 (ANSERIFORMES, ANATIDAE). REVISTA BRASILEIRA DE ORNITOLOGIA 3(1):62-65**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_Antas_Anilhamento_Dendrocygna_1995.pdf) *Artigo completo*

- [**NASCIMENTO I.L.S. 1995. AS AVES DO PARQUE NACIONAL DA LAGOA DO PEIXE. IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Aves_da_Lagoa_Peixe.pdf) *Guia*

- [**ANTAS P.T.Z. 1995. AVES DO PARQUE NACIONAL DE BRASÍLIA. IBAMA (COLEÇÃO MEIO AMBIENTE. SÉRIE FAUNA BRASILEIRA), BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Aves_do_Parna_de_Brasilia.pdf) *Guia*

- [**SCHULZ-NETO A. 1995. LISTA DAS AVES DA PARAÍBA. IBAMA, JOÃO PESSOA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/livreto_aves_paraiba.pdf) *Guia*

- [**SCHULZ-NETO A. 1995. OBSERVANDO AVES NO PARQUE NACIONAL MARINHO DE FERNANDO DE NORONHA: GUIA DE CAMPO. IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/livreto_Observ_Aves_Noronha_.pdf) *Guia*

- [**NASCIMENTO J.L.X. & ANTAS P.T.Z. 1995. BANDING OF DENDROCYGNA SPP. (ANSERIFORMES, ANATIDAE) IN BRAZIL, FROM 1980 TO 1994. V CONGRESSO DE ORNITOLOGIA NEOTROPICAL, ASSUNÇÃO, PARAGUAI.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_V_CON_R97_1995.pdf) *Resumo*

- [**ANTAS P.T.Z. 1994. MIGRATION AND OTHER MOVEMENTS AMONG THE LOWER PARANÁ RIVER VALLEY WETLANDS, ARGENTINA AND SOUTH BRASIL/PANTANAL WETLANDS. BIRD CONSERVATION INTERNATIONAL 4:181-190**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Antas_1994_BCI.pdf) *Artigo completo*

- [**NASCIMENTO I.L.S. ET AL. 1994. MANUAL DE ANILHAMENTO DE AVES SILVESTRES. 2ED., EDIÇÕES IBAMA, BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Manual_de_Anilhamento_-_Geral.pdf) *Manual*

- [**NASCIMENTO J.L.X. ET AL. 1994. BIOLOGIA E SITUAÇÃO ATUAL DA MARRECA-PARDA ANAS GEORGICA NO BRASIL. IV CONGRESSO BRASILEIRO DE ORNITOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo-IV_CBO_1994_P103.pdf) *Resumo*

- [**EFE M.A. ET AL. 1994. PROJETO ANDORINHAS DO MAR - CONSERVAÇÃO DE STERNA SPP. NO ESPÍRITO SANTO. IV CONGRESSO BRASILEIRO DE ORNITOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo-IV_CBO_1994_P144.pdf) *Resumo*

- [**CORDEIRO P.H.C. ET AL. 1994. TRINTA-RÉIS-BOREAL STERNA HIRUNDO. UMA ANÁLISE DAS RECUPERAÇÕES ENTRE 1980 E 1994. IV CONGRESSO BRASILEIRO DE ORNITOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo-IV_CBO_1994_P153.pdf) *Resumo*

- [**EFE M.A. & MUSSO C.M. 1994. CRESCIMENTO DE FILHOTES DE STERNA (SANDVICENSIS) EURYGNATHA, NA ILHA ESCALVADA, ES. IV CONGRESSO BRASILEIRO DE ORNITOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo-IV_CBO_1994_P44.pdf) *Resumo*

- [**SCHULZ-NETO A. 1994. LEVANTAMENTO DE AVES COSTEIRAS NO LITORAL CEARENSE. IV CONGRESSO BRASILEIRO DE ORNITOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo-IV_CBO_1994_P60.pdf) *Resumo*

- [**EFE M.A. & MUSSO C.M. 1994. REGISTRO DE REPRODUÇÃO DE PUFFINUS LHERMINIERI (LESSON, 1939) NO BRASIL. IV CONGRESSO BRASILEIRO DE ORNITOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo-IV_CBO_1994_P82.pdf) *Resumo*

- [**SCHULZ-NETO A. 1994. ASPECTOS BIOLÓGICOS DAS AVES MARINHAS DO ATOL DAS ROCAS. IV CONGRESSO BRASILEIRO DE ORNITOLOGIA, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo-IV_CBO_1994_P95.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 1993. A AVIFAUNA DA REGIÃO DO LAGO DE SOBRADINHO, BAHIA. III CONGRESSO BRASILEIRO DE ORNITOLOGIA, PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_III_CBO_1993_33.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 1993. MONITORAMENTO DA COSTA DO RIO GRANDE DO SUL ATRAVÉS DE CENSO AÉREO DE AVES. III CONGRESSO BRASILEIRO DE ORNITOLOGIA, PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_III_CBO_1993_34.pdf) *Resumo*

- [**ANTAS P.T.Z. ET AL. 1993. CENSOS AÉREOS E TERRESTRES DE TUIUIÚS (JABIRU MYCTERIA) NO PANTANAL DE MATO GROSSO DO SUL. III CONGRESSO BRASILEIRO DE ORNITOLOGIA. PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_III_CBO_1993_36.pdf) *Resumo*

- [**SCHULZ-NETO A. & SOUZA E.A. 1993. LEVANTAMENTO PRELIMINAR DE AVES AQUÁTICAS NO LITORAL SUL SERGIPANO. III CONGRESSO BRASILEIRO DE ORNITOLOGIA. PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_III_CBO_1993_P21.pdf) *Resumo*

- NASCIMENTO J.L.X. 1993. **DEVELOPING AN INTEGRATED MONITORING PROGRAM FOR WATERBIRDS IN BRAZIL**. PROCEEDINGS OF AN IWRB SIMPOSIUM, IWRB SPEC.PUBL., MIAMI, EUA.

- [**ANTAS P.T.Z. ET AL. 1992. MIGRAÇÃO DE NETTA PEPOSACA ENTRE O SUL DO BRASIL E A ARGENTINA. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_24.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 1992. MOVIMENTAÇÃO DE DENDROCYGNA BICOLOR ENTRE O RIO GRANDE DO SUL E ARGENTINA. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_25.pdf) *Resumo*

- [**NASCIMENTO I.L.S. ET AL. 1992. DINÂMICA DE MUDA E MOVIMENTAÇÃO DE CALIDRIS ALBA NA COSTA DO BRASIL. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_27.pdf) *Resumo*

- [**ANTAS P.T.Z. ET AL. 1992. DINÂMICA DE MUDA E PESO DE ADULTOS DE CALIDRIS PUSILLA NA COROA DO AVIÃO, IGARASSU - PERNAMBUCO. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_43.pdf) *Resumo*

- [**ANTAS P.T.Z. & NASCIMENTO I.L.S. 1992. MONITORAMENTO DO TUIUIÚ JABIRU MYCTERIA NO PANTANAL DA NHECOLANDIA, CORUMBA, MS, NO ANO DE 1989. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_46.pdf) *Resumo*

- [**ANTAS P.T.Z. ET AL. 1992. NOVOS REGISTROS DE AVES PARA O BRASIL. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_51.pdf) *Resumo*

- [**ANTAS P.T.Z. 1992. NOVOS REGISTROS PARA A AVIFAUNA DO RIO GRANDE DO SUL. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_67.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 1992. ENCONTRO DE HÍBRIDOS DE DENDROCYGNA VIDUATA E DENDROCYGNA BICOLOR EM SANTA VITÓRIA DO PALMAR. VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_VI_enav_68.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 1992. O PAPEL DO CEMAVE NA CAPACITAÇÃO DO ORNITÓLOGO.VI ENCONTRO NACIONAL DE ANILHADORES DE AVES (1990), PELOTAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_VI_ENAV.pdf) *Resumo expandido*

- [**EFE M.A. ET AL. 1992. PRIMEIRO REGISTRO DE NIDIFICAÇÃO DE PHAETON LEPTURUS DAUDIN, 1802 NO ARQUIPÉLAGO DOS ABROLHOS, BAHIA, BRASIL. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/EFE_etal_1992_PrimeiroRegistroNidificacaoPhaethon.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 1992. CENSO AÉREO DE FLAMINGOS PHOENICOPTERUS RUBER E GUARÁS EUDOCIMUS RUBER NA COSTA DO AMAPÁ. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_II_CBO_R100.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 1992. CONSERVAÇÃO DE STERNA (SANDVICENSIS) EURYGNATHA NO ESPÍRITO SANTO. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_II_CBO_R101.pdf) *Resumo*

- [**PEREIRA S.F.T. & NASCIMENTO I.L.S. 1992. CENSO E ANILHAMENTO DE AVES LIMICOLAS NA AREA DE PROTEÇÃO AMBIENTAL DE PIAÇABUÇU, AL. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_II_CBO_R84.pdf) *Resumo*

- [**CASTRO I.N. & ANTAS P.T.Z. 1992. ANILHAMENTO DE AVES SILVESTRES EM MATA CILIAR NO PARQUE NACIONAL DE BRASÍLIA, DF. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_II_CBO_R96.pdf) *Resumo*

- [**NASCIMENTO J.L.X. ET AL. 1992. INFORMAÇÕES SOBRE MUDA DE RÊMIGES EM ANATÍDEOS NO AMAPÁ E RIO GRANDE DO SUL. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_II_CBO_R97.pdf) *Resumo*

- [**ATAGUILE B.S. ET AL. 1992. DADOS REFERENTES AO CENSO AEREO EM REGIÕES DE BANHADO NO ESTADO DO RIO GRANDE DO SUL, BRASIL. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_II_CBO_R98.pdf) *Resumo*

- [**ATAGUILE B.S. ET AL. 1992. LEVANTAMENTO PRELIMINAR DA AVIFAUNA EM REGIÃO NATURAL DE BANHADO, NA ESTÂNCIA IPIRANGA, RIO GRANDE DO SUL. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/resumo_-_II_CBO_R99.pdf) *Resumo*

- [**SCHULZ-NETO A. ET AL. 1992. NOVAS OCORRÊNCIAS REPRODUTIVAS DE CHARADRIUS COLLARIS E CHARADRIUS WILSONIA. II CONGRESSO BRASILEIRO DE ORNITOLOGIA, CAMPO GRANDE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/SchulzNeto_etal_1992_NovasOcorrenciasReprCharadrius.pdf) *Resumo*

- [**SCHULZ-NETO A. & INTERAMINENSE L.J.L. 1992. ANILHAMENTO DE AVES MARINHAS NA RESERVA BIOLÓGICA DO ATOL DAS ROCAS. IX ENCONTRO DE ZOOLOGIA DO NORDESTE, RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_IX_EZN_140_1992.pdf) *Resumo*

- [**ANTAS P. 1992. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 19:12**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_19.pdf) *Nota de divulgação*

- [**ANTAS P.T.Z. 1991. STATUS AND CONSERVATION OF SEABIRDS BREEDING IN BRAZILIAN WATERS. SEABIRD STATUS AND CONSERVATION: A SUPPLEMENT, INTERNATIONAL COUNCIL OF BIRD PRESERVATION, TECH. PUBLICATION 11:141-158**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_Seabirds_1991.pdf) *Artigo completo*

- [**ANTAS P.T.Z. & NASCIMENTO I.L.S. 1991. ANÁLISIS DE DATOS DE ANILLADO DE CALIDRIS CANUTUS EN BRASIL. IV CONGRESO ORNITOLOGIA NEOTROPICAL, QUITO, EQUADOR.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas__Nascimento_1991_Calidris_canutus.pdf) *Resumo*

- [**ANTAS P.T.Z. & NASCIMENTO J.L.X. 1991. MOVIMENTAÇÃO E SITUAÇÃO ATUAL DE ANAS GEORGICA NO SUL DO BRASIL. IV CONGRESO ORNITOLOGIA NEOTROPICAL, QUITO, EQUADOR.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas__Nascimento_1991_Anas_georgica.pdf) *Resumo*

- [**ANTAS P. 1991. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 16:13-14**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_16.pdf) *Nota de divulgação*

- [**ANTAS P.T.Z. 1991. USO DE AMBIENTES AQUÁTICOS DO BAIXO RIO PARANÁ, ARGENTINA, POR AVES DO SUL DO BRASIL E DO PANTANAL. IV CONGRESO ORNITOLOGIA NEOTROPICAL, QUITO, EQUADOR.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_1991_Aves_sul.pdf) *Resumo*

- [**NASCIMENTO J.L.X. & ANTAS P.T.Z. 1990. ANÁLISE DOS DADOS DE ANILHAMENTO DE AMAZONETTA BRASILIENSIS NO BRASIL. REVISTA BRASILEIRA DE ORNITOLOGIA 1(1):85-90**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_Antas_RBO1.pdf) *Artigo completo*

- [**NASCIMENTO J.L.X. 1990. REPRODUÇÃO DE AGAMIA AGAMI NA USINA HIDRELÉTRICA BALBINA. REVISTA BRASILEIRA DE ORNITOLOGIA 1(1):79-83**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_1990_RBO1.pdf) *Artigo completo*

- [**MYERS J.P. ET AL. 1990. MIGRATION ROUTES OF NEW WORLD SANDERLINGS (CALIDRIS ALBA). THE AUK 107:172-180**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Myers_etal_1990.pdf) *Artigo completo*

- [**ANTAS P.T.Z. ET AL. 1990. STATUS AND CONSERVATION OF THE SCARLET IBIS (EUDOCIMUS RUBER) IN BRASIL. IN: THE SCARLET IBIS (EUDOCIMUS RUBER): STATUS, CONSERVATION AND RECENT RESEARCH, INTERNATIONAL WATERFOWL RESEARCH BUREAU, CAMBRIDGE, REINO UNIDO.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Antas_etal_1990.pdf) *Artigo completo*

- [**ANTAS P.T.Z. ET AL. 1990. ANILHAMENTO DE AVES OCEÂNICAS E/OU MIGRATÓRIAS NO ARQUIPÉLAGO DE FERNANDO DE NORONHA EM 1987 E 1988. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_13-17_-_1990.pdf) *Resumo*

- [**ANTAS P.T.Z. ET AL. 1990. ANILHAMENTO DE AVES OCEÂNICAS E/OU MIGRATÓRIAS NO ARQUIPÉLAGO DE FERNANDO DE NORONHA EM 1987 E 1988. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_etal_Anilhamento_Noronha_87_e_88.pdf) *Resumo expandido*

- [**NASCIMENTO J.L.X. & ANTAS P.T.Z. 1990. ANALISE DOS DADOS DE ANILHAMENTO DE AMAZONETTA BRASILIENSIS NO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_1-5_-1990.pdf) *Resumo*

- [**NASCIMENTO J.L.X. & ANTAS P.T.Z. 1990. ANALISE DOS DADOS DE ANILHAMENTO DE AMAZONETTA BRASILIENSIS NO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_Antas_Artigo_IVENAV.pdf) *Resumo expandido*

- [**ANTAS P.T.Z. ET AL. 1990. AVES ENDÊMICAS ANILHADAS NO ARQUIPÉLAGO DE FERNANDO DE NORONHA EM 1987 E 1988. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_35-43_-_1990.pdf) *Resumo*

- [**ANTAS P.T.Z. ET AL. 1990. AVES ENDÊMICAS ANILHADAS NO ARQUIPÉLAGO DE FERNANDO DE NORONHA EM 1987 E 1988. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_etal_Anilhamento_Noronha_87_e_88.pdf) *Resumo expandido*

- [**AZEVEDO JR S.M. & ANTAS P.T.Z. 1990. NOVAS INFORMAÇÕES SOBRE A ALIMENTAÇÃO DA ZENAIDA AURICULATA NO NORDESTE DO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_59-64_-_1990.pdf) *Resumo*

- [**AZEVEDO JR S.M. & ANTAS P.T.Z. 1990. NOVAS INFORMAÇÕES SOBRE A ALIMENTAÇÃO DA ZENAIDA AURICULATA NO NORDESTE DO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AzevedoJR_Antas_ResumoExpandido_1990.pdf) *Resumo expandido*

- [**ANTAS P.T.Z. & NASCIMENTO I.L.S. 1990. ANÁLISE DOS DADOS DE ANILHAMENTO DE CALIDRIS PUSILLA NO BRASIL, DE 1981 A 1988. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_6-12_-_1990.pdf) *Resumo*

- [**ANTAS P.T.Z. & NASCIMENTO I.L.S. 1990. ANÁLISE DOS DADOS DE ANILHAMENTO DE CALIDRIS PUSILLA. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_Nascimento_Artigo_IVENAV.pdf) *Resumo expandido*

- [**AZEVEDO JR S.M. & ANTAS P.T.Z. 1990. OBSERVAÇÕES SOBRE A REPRODUÇÃO DE ZENAIDA AURICULATA NO NORDESTE DO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_65-72_-_1990.pdf) *Resumo*

- [**AZEVEDO JR S.M. & ANTAS P.T.Z. 1990. OBSERVAÇÕES SOBRE A REPRODUÇÃO DE ZENAIDA AURICULATA NO NORDESTE DO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AzevedoJR_Antas_ResumoExpandido_1990b.pdf) *Resumo expandido*

- [**NASCIMENTO J.L.X. 1990. PRIMEIRO ENCONTRO DE UM NINHAL DE AGAMIA AGAMI NO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_73-77_-_1990.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 1990. PRIMEIRO ENCONTRO DE UM NINHAL DE AGAMIA AGAMI NO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nascimento_1990.pdf) *Resumo expandido*

- [**AZEVEDO JR S.M. & ANTAS, P.T.Z. 1990. TÉCNICAS DE CAPTURA PARA ANILHAMENTO DE ZENAIDA AURICULATA NO NORDESTE DO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_IV_enav_78-84_-_1990.pdf) *Resumo*

- [**AZEVEDO JR S.M. & ANTAS, P.T.Z. 1990. TÉCNICAS DE CAPTURA PARA ANILHAMENTO DE ZENAIDA AURICULATA NO NORDESTE DO BRASIL. IV ENCONTRO NACIONAL DE ANILHADORES DE AVES (1988), RECIFE, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/AzevedoJR_Antas_ResumoExpandido_1990c.pdf) *Resumo expandido*

**1989-1980**

- [**NASCIMENTO I.L.S. & ANTAS P.T.Z. 1989. ANILHAMENTO DE AVES LIMÍCOLAS NO BRASIL. V ENCONTRO NACIONAL DE ANILHADORES DE AVES (1989), BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_V_enav_13_-_1989.pdf) *Resumo*

- [**NASCIMENTO J.L.X. 1989. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 13:12**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_13.pdf) *Nota de divulgação*

- [**NASCIMENTO J.L.X. & ANTAS P.T.Z. 1989. RESULTADOS DO ANILHAMENTO DE DENDROCYGNA SPP NO BRASIL. V ENCONTRO NACIONAL DE ANILHADORES DE AVES (1989), BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_V_enav_14_-_1989.pdf) *Resumo*

- [**SOUZA M.A.B. ET AL. 1989. DADOS DE ANILHAMENTO, CENSO E BIOMETRIA DE AVES AQUÁTICAS DO JARDIM ZOOLÓGICO DE BRASÍLIA, DF. V ENCONTRO NACIONAL DE ANILHADORES DE AVES (1989), BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_V_enav_30_-_1989.pdf) *Resumo*

- [**ANTAS P.T.Z. & NASCIMENTO I.L.S. 1989. ANILHAMENTO DO TUIUIÚ JABIRU MYCTERIA NO PANTANAL DE MATO GROSSO. V ENCONTRO NACIONAL DE ANILHADORES DE AVES (1989), BRASÍLIA, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo-V_enav_7_-_1989.pdf) *Resumo*

- [**LARA-RESENDE S. & LEEUWENBERG F. 1989. RECUPERACION DE AVES MIGRATORIAS ANILLADAS EM BRASIL: UN AUMENTO SIGNIFICATIVO. EL VOLANTE MIGRATORIO 13:21-24**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_13_LaraResende.pdf) *Artigo completo*

- ANTAS P.T.Z. 1989. **AVES LIMÍCOLAS DO BRASIL**. SEMINÁRIO INTERNACIONAL SOBRE MANEJO E CONSERVAÇÃO DE MAÇARICOS E AMBIENTES AQUÁTICOS NAS AMÉRICAS, IBAMA/UFRPE/FUNATURA/MBO, RECIFE, BRASIL.

- MORRISON R.I.G. ET AL. 1989. **CAPÍTULO DE INTRODUÇÃO**. ATLAS OF NEARTIC SHOREBIRDS ON THE COAST OF SOUTH AMERICA, CANADIAN WILDLIFE SERVICE, V, I E II, OTTAWA, CANADÁ.

- [**MORRISON R.I.G. ET AL. 1989. BRAZIL. ATLAS OF NEARTIC SHOREBIRDS ON THE COAST OF SOUTH AMERICA, CANADIAN WILDLIFE SERVICE, V, I E II, OTTAWA, CANADÁ.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/MorrisonRoss_Brazil_1989.pdf) *Capítulo*

- [**ANTAS P.T.Z. 1988. DEZ ANOS DA CRIAÇÃO DO CENTRO DE ESTUDOS DE MIGRAÇÕES DE AVES. III ENCONTRO NACIONAL DE ANILHADORES DE AVES (1987), SÃO LEOPOLDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_-_3_enav_dez_anos_-_1988.pdf) *Resumo expandido*

- [**ANTAS P.T.Z. 1988. MUDA E PESO DE SCOLOPACIDAE E CHARADRIIDAE CAPTURADOS NA LAGOA DO PEIXE, TAVARES, RS, ENTRE 1985 E 1987. III ENCONTRO NACIONAL DE ANILHADORES DE AVES (1987), SÃO LEOPOLDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_-_3_enav_Scolopacidae_-_1988.pdf) *Resumo*

- [**ANTAS P.T.Z. 1988. ANÁLISE DOS DADOS DE ANILHAMENTO DE STERNA HIRUNDO NA LAGOA DO PEIXE, TAVARES, RS. III ENCONTRO NACIONAL DE ANILHADORES DE AVES (1987), SÃO LEOPOLDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_-_3_enav_Sterna_-_1988.pdf) *Resumo*

- [**ANTAS P.T.Z. & LEEUWENBERG S.L.R. 1988. DADOS SOBRE A BIOLOGIA REPRODUTIVA DE ANTILOPHIA GALEATA NO PARQUE NACIONAL DE BRASÍLIA. III ENCONTRO NACIONAL DE ANILHADORES DE AVES (1987), SÃO LEOPOLDO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_-_III_ENAV_1987_105-6_-_1987.pdf) *Resumo*

- [**ANTAS P.T.Z. ET AL. 1988. AVES COMUNS DO PLANALTO CENTRAL. ED. UNIVERSIDADE DE BRASÍLIA, BRASÍLIA, BRASIL. 238P.**](https://www.amazon.com.br/Aves-Comuns-do-Planalto-Central/dp/8523012516) *Guia*

- LARA-RESENDE S.M. 1988. **NONBREEDING STRATEGIES OF MIGRATORY BIRDS AT LAGOA DO PEIXE, RIO GRANDE DO SUL, BRAZIL**. DISSERTAÇÃO DE MESTRADO. UNIVERSIDADE DE CORNELL, ITHACA, ESTADOS UNIDOS.

- [**ANTAS P.T.Z. 1987. NIDIFICAÇÃO NO CHÃO DA ROLINHA-ROXA MIRIM, COLUMBINA MINUTA, EM PEDRO AVELINO, RIO GRANDE DO NORTE, BRASIL. REVISTA BRASILEIRA DE ZOOLOGIA 3(7):465-466**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nota_Antas_1986.pdf) *Nota*

- [**LARA-RESENDE S. & LEEUWENBERG F. 1987. ESTRELLA LAGOA DO PEIXE: UMA ALTERNATIVA. EL VOLANTE MIGRATORIO 9:24-27**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_9_LaraResende.pdf) *Nota*

- [**ANTAS P.T.Z. 1987. A NIDIFICAÇÃO DA AVOANTE ZENAIDA AURICULATA NO NORDESTE DO BRASIL, RELACIONADA COM O SUBSTRATO FORNECIDO PELA VEGETAÇÃO. REVISTA BRASILEIRA DE ZOOLOGIA 3(7):467-470**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Nota_Antas_1987_v3n7a06.pdf) *Nota*

- [**AZEVEDO JR S.M. ET AL. 1987. CENSO DA ZENAIDA AURICULATA NORONHA FORA DA ÉPOCA DE REPRODUÇÃO NO NORDESTE. CAD. ÔMEGA UNIV. FED. RURAL PE. SER. BIOL. 2:157-168**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Artigo_-_Censo_Zenaida_1987.pdf) *Artigo completo*

- [**ANTAS P.T.Z. 1987. MIGRAÇÃO DE AVES NO BRASIL. II ENCONTRO NACIONAL DE ANILHADORES DE AVES (1986), RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_II_enav_153-87_-_1986.pdf) *Palestra*

- [**YAMASHITA C. & VALLE M.P. 1987. SOBRE ANILHAMENTO E MIGRAÇÃO DE MYCTERIA AMERICANA NO PANTANAL. II ENCONTRO NACIONAL DE ANILHADORES DE AVES (1986), RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_II_enav_196-7_-_1986.pdf) *Resumo*

- [**VALLE M.P. & YAMASHITA C. 1987. MIGRAÇÃO DE COLUMBA PICAZURO. II ENCONTRO NACIONAL DE ANILHADORES DE AVES (1986), RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_II_enav_201_-_1986.pdf) *Resumo*

- [**YAMASHITA C. 1987. TÉCNICAS DE CAPTURA PARA MARCAÇÕES QUALITATIVAS. II ENCONTRO NACIONAL DE ANILHADORES DE AVES (1986), RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_II_enav_76-97_-_1986.pdf) *Resumo expandido*

- [**MYERS J.P. ET AL. 1987. CONSERVATION STRATEGY FOR MIGRATORY SPECIES. AMERICAN SCIENTIST 75:19-26**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Myers_etal_1987.pdf) *Artigo completo*

- [**MYERS J.P. ET AL. 1987. THE WESTERN HEMISPHERE SHOREBIRD RESERVE NETWORK. WADER STUDY GROUP BULLETIN 49, SUPPL./IWRB SPECIAL PUBL. 7:122-124**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Myers_etal_1987a.pdf) *Nota*

- [**ANTAS P.T.Z. & VALLE M.P. 1987. DADOS PRELIMINARES SOBRE TURDUS NIGRICEPS NO DISTRITO FEDERAL. II ENCONTRO NACIONAL DE ANILHADORES DE AVES (1986), RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_Valle_IIEnav.pdf) *Resumo expandido*

- [**ANTAS P.T.Z. 1987. ORGANIZACION DE LOS CURSOS DE ANILLAMIENTO DE AVES EN BRASIL. EL VOLANTE MIGRATORIO 9:29-31**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteVoador_9.pdf) *Artigo de divulgação*

- [**MORRISON R.I.G. ET AL. 1987. MIGRATORY ROUTES IN THE AMAZONIAN COAST. IN: DESENVOLVIMENTO ECONÔMICO E IMPACTO AMBIENTAL EM ÁREAS DE TRÓPICO ÚMIDO BRASILEIRO - A EXPERIÊNCIA DA COMPANHIA VALE DO RIO DOCE. SEMINÁRIO SEMA/IWRB/CVRD, RIO DE JANEIRO, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Morrison_etal_1987.pdf) *Capítulo*

- [**ANTAS P.T.Z. ET AL. 1986. FIRST RERCORD OF PURPLE MARTIN (PROGNE SUBIS) IN MATO GROSSO STATE, BRAZIL. JOURNAL OF FIELD ORNITHOLOGY 57(2):171-172**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_etal_1985.pdf) *Nota*

- [**HARRINGTON B.A. ET AL. 1986. OBSERVATIONS OF COMMON TERNS IN SOUTHERN BRAZIL, 29 APRIL-3 MAY 1984. JOURNAL FIELD ORNITHOLOGY 57(3):222-240**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_jio-57-3-observations_of_common_-_1986.pdf) *Nota*

- [**ANTAS P.T.Z. ET AL. 1986. COUNTRY REPORT: BRAZIL. IN: A DIRECTORY OF NEOTROPICAL WETLANDS (D. A. SCOTT & M. CARBONELL). INTERNATIONAL UNION FOR CONSERVATION OF NATURE AND NATURAL RESOURCES, CAMBRIDGE, INGLATERRA.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Antas_etal_1986.pdf) *Artigo completo*

- [**HARRINGTON B.A. ET AL. 1986. NORTHWARD SHOREBIRD MIGRATION ON THE ATLANTIC COAST OF SOUTHERN BRAZIL. VIDA SILVESTRE NEOTROPICAL 1(1):45-54**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_Harrington_etal_1986.pdf) *Artigo completo*

- [**ANTAS P.T.Z. ET AL. 1986. THE MIGRATION PATTERNS OF THE EARED DOVE IN NORTHEASTERN BRASIL. XIX CONGRESSUS INTERNATIONALIS ORNITHOLOGICUS, OTTAWA, CANADÁ.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_etal_1986_EaredDove.pdf) *Resumo*

- [**MORRISON R.I.G. ET AL. 1986. DISTRIBUIÇÃO DE MAÇARICOS, BATUÍRAS E OUTRAS AVES COSTEIRAS NA REGIÃO DO SALGADO PARAENSE E REENTRÂNCIAS MARANHENSES. ESPAÇO, AMBIENTE E PLANEJAMENTO 1(4):1-136**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Morrison_EspacoAmbienteePlanejamento.pdf) *Artigo completo*

- [**ANTAS P.T.Z. 1986. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 6:13-14**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_6.pdf) *Nota de divulgação*

- [**ANTAS P.T.Z. 1986. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 7:14-15**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_7.pdf) *Nota de divulgação*

- [**LARA-RESENDE S.M. & ANTAS P.T.Z. 1985. AVES ANILHADAS NO BRASIL EM 1981 E RECUPERAÇÕES DE ANILHAS DESDE 1980. REVISTA BRASILEIRA DE ZOOLOGIA 3(1):51-59**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lara_Resende_Antas_1985.pdf) *Artigo completo*

- [**ANTAS P.T.Z. & LARA-RESENDE S.M. 1985. THE CENTRO DE ESTUDOS DE MIGRAÇÕES DE AVES (CEMAVE). XXXI ANNUAL MEETING DO INTERNATIONAL WATERFOWL RESEARCH BUREAU, PARACAS, PERU.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas_1985.pdf) *Resumo expandido*

- [**MORRISON R.I.G. ET AL. 1985. AERIAL SURVEYS OF SHOREBIRDS AND OTHER WILDLIFE IN SOUTH AMERICA: SOME PRELIMINARY RESULTS. CANADIAN WILDLIFE SERVICE PROGRESS NOTES 148:1-22**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/CW69-9-148-eng.pdf) *Artigo completo*

- [**AZEVEDO JR S.M. ET AL. 1985. CENSO DA ZENAIDA AURICULATA NORONHA FORA DA ÉPOCA DE REPRODUÇÃO, NO NORDESTE. V ENCONTRO NORDESTINO DE ZOOLOGIA, NATAL, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_V_ENZ_1985.pdf) *Resumo*

- [**YAMASHITA C. & ANTAS P.T.Z. 1985. SOBRE INTERMEDIÁRIOS ENTRE ARATINGA JANDAYA E ARATINGA AURICAPPILLA (PSITTACIDAE, AVES). XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_526_1985.pdf) *Resumo*

- [**YAMASHITA C. & VALLE M.P. 1985. NINHAIS COLONIAIS NO MUNICÍPIO DE POCONÉ, MT. XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_534_1985.pdf) *Resumo*

- [**YAMASHITA C. 1985. SOBRE O COMPORTAMENTO DE ANODORHYNCHUS LEARI (BONAPARTE) (PSITTACIFORMES). XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_539_1985.pdf) *Resumo*

- [**SANDER M. & ANTAS P.T.Z. 1985. PROGRAMA DE ANILHAMENTO DE AVES NA ANTÁRTICA. XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_552_1985.pdf) *Resumo*

- [**VALLE M.P. & YAMASHITA C. 1985. COLUMBIDEOS DA FAZENDINHA, POCONÉ, MT. XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_556_1985.pdf) *Resumo*

- [**YAMASHITA C. & ANTAS P.T.Z. 1985. OCORRÊNCIA DE AEGOLIUS HARISSI (CASSIN, 1849) EM BRASÍLIA (STRIGIFORMES, STRIGIDAE). XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_558_1985.pdf) *Resumo*

- [**VALLE M.P. ET AL. 1985. CONTRIBUIÇÃO AO CONHECIMENTO DE ANDORINHAS NO MUNICÍPIO DE POCONÉ, MT. XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_562_1985.pdf) *Resumo*

- [**YAMASHITA C. & VALLE M.P. 1985. SOBRE AS AVES DE HÁBITO SAPRÓFAGO. XII CONGRESSO BRASILEIRO DE ZOOLOGIA, CAMPINAS, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/XII_Congresso_Zoologia_R_578_1985.pdf) *Resumo*

- [**ANTAS P.T.Z. 1985. BRASIL. EL VOLANTE MIGRATORIO (SUPLEMENTO) 4:21**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_4.pdf) *Nota de divulgação*

- [**YAMASHITA C. 1985. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 5:11-12**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_5.pdf) *Nota de divulgação*

- [**ANTAS P.T.Z. 1984. AVES ANILHADAS NO BRASIL EM 1982 E RECUPERAÇÕES DE ANILHAS BRASILEIRAS. XI CONGRESSO BRASILEIRO DE ZOOLOGIA, BELÉM, BRASIL.**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Resumo_-_XI_CBZ_R333_1984.pdf) *Resumo*

- [**LARA-RESENDE S.M. 1984. ANILLAMENTO DE AVES EM EL CONTINENTE AMERICANO. EL VOLANTE MIGRATORIO 2:10-11**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteVoador_2_Lara-Resende.pdf) *Nota de divulgação*

- [**ANTAS P.T.Z. 1984. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 2:15**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteVoador_2Nota.pdf) *PNota de divulgação*

- [**ANTAS P.T.Z. 1984. EL CENTRO DE ESTUDOS DE MIGRACIONES DE AVES EN EL BRASIL. EL VOLANTE MIGRATORIO 2:22-24**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteVoador_2.pdf "Artigo de divulgação")

- [**LARA-RESENDE S.M. 1984. NECESIDAD DE DIFUNDIR LAS TECNICAS DE ANILLAMENTO DE AVES MIGRATORIAS. EL VOLANTE MIGRATORIO 3:25-26**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteVoador_3_Lara-Resende.pdf) *PNota de divulgação*

- [**ANTAS P.T.Z. 1984. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 3:13**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteMigratorio_3.pdf) *PNota de divulgação*

- [**ANTAS P.T.Z. 1983. MIGRAÇÃO DE AVES NA REGIÃO DO CERRADO DO BRASIL CENTRAL. REVISTA DO SERVIÇO PÚBLICO 111(4):159-161**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antasa_1983.pdf "Artigo de divulgação")

- [**ANTAS P.T.Z. 1983. MIGRATION OF NEARTIC SHOREBIRDS (CHARADRIIDAE AND SCOLOPACIDAE) IN BRAZIL - FLYWAYS AND THEIR DIFFERENT SEASONAL USE. WADER STUDY GROUP BULLETIN 39:52-56**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antasb_1983.pdf) *Artigo completo*

- [**LARA-RESENDE S.M. &. ANTAS P.T.Z. 1983. FIRST RECORD OF THE SOUTH AMERICAN POCHARD IN CENTRAL BRAZIL. THE AUK 100:220-221**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/artigo_auk-first_record_of_the_american_-_1983.pdf) *Artigo completo*

- [**LARA-RESENDE S.M. 1983. RECUPERAÇÕES DE ANILHAS ESTRANGEIRAS NO BRASIL. REVISTA BRASILEIRA DE ZOOLOGIA 1(3):231-237**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Rec_anilhas_estrangeiras.pdf) *Artigo completo*

- [**ANTAS P.T.Z. & LARA-RESENDE S.M. 1983. AVES ANILHADAS NO BRASIL EM 1980 E SUAS RECUPERAÇÕES. REVISTA BRASILEIRA DEE ZOOLOGIA 1(3):223-229**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Antas__Lara_Resende_1983.pdf) *Artigo completo*

- [**ANTAS P.T.Z. 1983. BRASIL - LOS PAÍSES NOS ESCRIBEN. EL VOLANTE MIGRATORIO 1:9**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/ElVolanteVoador_1.pdf) *PNota de divulgação*

- [**LARA-RESENDE S.M. & LEAL R.P. 1982. RECUPERAÇÃO DE ANILHAS ESTRANGEIRAS NO BRASIL. BRASIL FLORESTAL 52:27-53**](https://www.icmbio.gov.br/cemave/images/stories/Publica%C3%A7%C3%B5es_cient%C3%ADficas/Lara_Resende_Leal_1982.pdf) *Artigo completo*

- [**LEAL R.P. ET AL. 1981. MANUAL DE ANILHAMENTO DE AVES. MINISTÉRIO DA AGRICULTURA, INSTITUTO BRASILEIRO DE DESENVOLVIMENTO FLORESTAL, CENTRO DE ESTUDOS DE MIGRAÇÕES DE AVES, BRASÍLIA, BRASIL.**](https://drive.google.com/file/d/1Aec5524IdDHDLVV-MBPjDvjRA8Pp9zi6/view?usp=sharing) *Manual*

**1979-1970**

- ANTAS P.T.Z. 1979. **PRESENT SITUATION OF BIRD BANDING IN BRAZIL**. THE RING 9(101):96-98

- [**ANTAS P.T.Z. 1979. SITUACION ACTUAL DEL ANILLADO EM BRASIL, SU ORGANIZACION A NIVEL NACIONAL Y PERSPECTIVAS FUTURAS. I ENCUENTRO IBEROAMERICANO DE ORNITOLOGIA Y MUNDIAL SOBRE ECOLOGIA Y COMPORTAMIENTO DE LAS AVES. BUENOS AIRES, ARGENTINA.**](https://drive.google.com/file/d/1e7FUMOtyBCmx2XsrK9xj-lWHQ9KL3bJm/view?usp=sharing) *Resumo*
